/**
 * The detector battery (FR-062 "Mutations", FR-062-AC-1).
 *
 * One detector per test case. Each is a function of a *loaded backend* rather
 * than of the checked-out one, so the same assertion runs twice: the suite runs
 * it against the modules in the working tree, and the mutation harness runs it
 * against a mutated scratch copy. A mutation is detected when a detector that
 * passes on the pristine copy fails on the mutant.
 *
 * Writing the assertion once is the point. A detector the suite does not run is
 * a mutation score nobody earned, and a case the harness does not run is a
 * detection claim nobody checked; the register binds the two by name, and
 * `cli.mjs mutations --check` fails when a detector names a case the suite does
 * not carry.
 *
 * The oracles are the mapping table, the applicability table and the diagnostic
 * registry — the artefacts that *declare* the mapping — never the emitter's own
 * output. The one exception is the corpus-bytes detector, which compares a
 * mutant against the pristine emitter and is a change detector by construction;
 * it is named as such and no branch-register row rests on it alone.
 */

import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { CONSTRUCT_KINDS } from "../../../constructs.mjs";
import { KEYWORD_APPLICABILITY } from "../../../ir/applicability.mjs";

/** The contract 1.2.0 fixture carrying every construct kind and model member. */
const CONSTRUCTS_FIXTURE = new URL(
	"../../../../../fixtures/semantic/v1/positive/semantic-ir-v1-2-constructs.json",
	import.meta.url,
);

/** The nine kernel scalar names, read from the table rather than restated. */
function kernelScalars(table) {
	return table.rows
		.filter((row) => row.axis === "scalar")
		.map((row) => row.selector);
}

/** The kind names, read from the table. */
function kinds(table) {
	return table.rows
		.filter((row) => row.axis === "kind")
		.map((row) => row.selector);
}

function assert(condition, message) {
	if (condition !== true) throw new Error(message);
}

/**
 * Loads one backend copy.
 *
 * `directory` is the backend directory — the working tree's, or a scratch copy
 * the mutation harness made. Every module is imported from that directory, so
 * a mutated module is the one the detectors run against.
 */
export async function loadBackend(directory, options = {}) {
	const load = (name) => import(pathToFileURL(join(directory, name)).href);
	const [
		mapping,
		crate,
		diagnostics,
		names,
		graph,
		patterns,
		constraints,
		degradation,
		generator,
		properties,
	] = await Promise.all([
		load("mapping.mjs"),
		load("crate.mjs"),
		load("diagnostics.mjs"),
		load("names.mjs"),
		load("graph.mjs"),
		load("patterns.mjs"),
		load("constraints.mjs"),
		load("degradation.mjs"),
		load("generator.mjs"),
		load("properties.mjs"),
	]);
	return {
		directory,
		mapping,
		crate,
		diagnostics,
		names,
		graph,
		patterns,
		constraints,
		degradation,
		generator,
		properties,
		table: JSON.parse(
			readFileSync(join(directory, "mapping-table.json"), "utf8"),
		),
		publishedCodes: options.publishedCodes ?? [],
		licenseText: options.licenseText ?? "",
		bases: options.bases ?? [],
		baseline: options.baseline ?? new Map(),
		sources: readSources(directory),
	};
}

/** Every module's text, for the detectors that ask what a module names. */
function readSources(directory) {
	const sources = new Map();
	for (const name of readdirSync(directory)) {
		if (!name.endsWith(".mjs")) continue;
		sources.set(name, readFileSync(join(directory, name), "utf8"));
	}
	return sources;
}

/** The bytes one request emits, as one string. */
function bytesOf(backend, ir, outputRoot) {
	const request = backend.properties.requestForIr(ir, outputRoot);
	const result = backend.crate.emitCrate(request, {
		licenseText: backend.licenseText,
	});
	return [...result.files].map(([path, text]) => `${path}\n${text}`).join("");
}

/** The emission of one document, diagnostics included. */
function emitted(backend, ir, outputRoot = "generated") {
	return backend.crate.emitCrate(
		backend.properties.requestForIr(ir, outputRoot),
		{
			licenseText: backend.licenseText,
		},
	);
}

/** A document generated by the loaded copy's own generator. */
function document(backend, index = 0) {
	return backend.generator.generateDocument(
		backend.generator.DEFAULT_SEED,
		index,
	);
}

function mapped(backend, ir) {
	const { model, diagnostics } = backend.mapping.mapDocument(ir, {});
	assert(
		model !== undefined,
		`the generated document was refused: ${diagnostics.map((one) => one.code).join(", ")}`,
	);
	return model;
}

/** A minimal well-formed document carrying `types`. */
function documentOf(types) {
	return {
		contractVersion: "1.1.0",
		source: {
			identity: "ix://agent-ix/filament-core-data/source/typespec",
			version: "1.0.0",
			dialect: "typespec",
			digest: `sha256:${"0".repeat(64)}`,
		},
		package: {
			identity: "agent-ix/detector",
			version: "1.0.0",
			manifestDigest: `sha256:${"1".repeat(64)}`,
			mappingVersions: ["1.0.0"],
			profileVersions: ["1.0.0"],
			lockDigest: `sha256:${"2".repeat(64)}`,
		},
		types,
		occurrences: [],
		extensions: [],
	};
}

const NS = "ix://agent-ix/detector";

function scalarType(name, scalar, constraints = []) {
	return {
		identity: `${NS}/type/${name}`,
		displayName: name,
		kind: "scalar",
		roles: [],
		constraints,
		extensions: [],
		unknownPolicy: "reject",
		scalar,
	};
}

/** The operand a keyword takes over a subject, chosen so the operand is valid. */
function operandsFor(keyword, subject) {
	if (["min", "max", "exclusiveMin", "exclusiveMax"].includes(keyword)) {
		if (subject === "date") return { value: "2020-01-01" };
		if (subject === "datetime") return { value: "2020-01-01T00:00:00Z" };
		if (subject === "duration") return { value: "P1D" };
		if (subject === "number") return { value: 1.5 };
		return { value: 1 };
	}
	if (keyword === "minLength" || keyword === "maxLength") return { value: 2 };
	if (keyword === "pattern") return { regex: "^[a-z]+$" };
	if (keyword === "format") return { name: "agent-ix:plain-text" };
	if (keyword === "enumValues") {
		if (subject === "boolean") return { values: [true] };
		if (subject === "integer") return { values: [1] };
		if (subject === "number") return { values: [1.5] };
		return { values: ["a"] };
	}
	return {};
}

/** The resolved subject an applicability entry names. */
function resolvedFor(subject, table) {
	return kernelScalars(table).includes(subject)
		? { kind: "scalar", scalar: subject }
		: { kind: subject };
}

/**
 * The detectors, in a fixed order. `caseId` is the exact title of the suite
 * case that runs it; `branches` is what the register binds.
 */
export const DETECTORS = Object.freeze([
	{
		caseId:
			"TC-727 the corpus bases emit the bytes the pristine emitter produced",
		oracle: "change-detector",
		run(backend) {
			assert(
				backend.bases.length > 0,
				"the harness resolved no corpus base, so this detector fails rather than passing over an empty population",
			);
			for (const base of backend.bases) {
				const observed = bytesOf(backend, base.bundle.ir, base.name);
				const expected = backend.baseline.get(base.name);
				assert(
					expected !== undefined,
					`no pristine baseline was captured for ${base.name}`,
				);
				assert(
					observed === expected,
					`${base.name} no longer emits the bytes the pristine emitter produced`,
				);
			}
		},
	},
	{
		caseId:
			"TC-725 every kind row selects the Rust form the mapping table states",
		run(backend) {
			const declared = kinds(backend.table);
			assert(
				declared.length === 18,
				`the table declares ${declared.length} kinds, not eighteen`,
			);
			const ir = document(backend);
			const model = mapped(backend, ir);
			const observed = new Set(model.types.map((one) => one.kind));
			for (const kind of declared) {
				// The generated 1.1.0 document carries no construct kind; the
				// constructs case measures those rows.
				if (
					kind === "reference" ||
					CONSTRUCT_KINDS.includes(kind) ||
					observed.has(kind)
				)
					continue;
				assert(
					false,
					`no generated declaration selected the kind row \`${kind}\``,
				);
			}
			// Each kind row's declared Rust form is the one the model carries.
			const forms = new Map(
				backend.table.rows
					.filter((row) => row.axis === "kind")
					.map((row) => [row.selector, row.rustForm]),
			);
			for (const type of model.types) {
				const form = forms.get(type.kind);
				assert(
					form !== undefined,
					`the kind \`${type.kind}\` selects no table row`,
				);
				if (type.kind === "sequence")
					assert(
						type.inner.startsWith("Vec<"),
						`a sequence carries ${type.inner}, and the table says ${form}`,
					);
				if (type.kind === "map")
					assert(
						type.inner.includes("BTreeMap<String, "),
						`a map carries ${type.inner}, and the table says ${form}`,
					);
				if (type.kind === "reference")
					assert(
						type.inner === "crate::support::SemanticIdentity",
						`a reference carries ${type.inner}, and the table says ${form}`,
					);
				if (type.kind === "record")
					assert(Array.isArray(type.fields), "a record carries no member list");
				if (type.kind === "enum" || type.kind === "union")
					assert(
						Array.isArray(type.variants),
						`a ${type.kind} carries no variant list`,
					);
				if (type.kind === "alias")
					assert(
						typeof type.inner === "string",
						"an alias carries no target type",
					);
				if (type.kind === "scalar")
					assert(
						typeof type.inner === "string",
						"a scalar carries no base type",
					);
			}
			// The contract 1.2.0 `entity` construct, which the generated 1.1.0
			// document cannot carry: its own row, the record's member list and its
			// identity field names in declared order.
			const entity = backend.mapping.mapDocument(
				{
					...documentOf([
						scalarType("Key", "string"),
						{
							identity: `${NS}/type/Account`,
							displayName: "Account",
							kind: "entity",
							roles: [],
							constraints: [],
							extensions: [],
							unknownPolicy: "reject",
							identityFields: [`${NS}/field/account-key`],
							fields: [
								{
									identity: `${NS}/field/account-key`,
									name: "key",
									typeRef: `${NS}/type/Key`,
									presence: "required",
									nullable: false,
									defaultKind: "none",
									multiplicity: { lower: 1, upper: 1 },
								},
							],
						},
					]),
					contractVersion: "1.2.0",
				},
				{},
			);
			const account = entity.model?.types.find(
				(one) => one.identity === `${NS}/type/Account`,
			);
			assert(
				account?.row === "kind:entity" &&
					forms.has("entity") &&
					Array.isArray(account.fields) &&
					account.fields.length === 1 &&
					JSON.stringify(account.identityFields) === '["key"]',
				`an entity selected ${account?.row} with identity fields ${JSON.stringify(account?.identityFields)}`,
			);
			// The one kind the generated document cannot carry inside itself: a
			// kind outside the eight is refused rather than mapped.
			const invalid = backend.mapping.mapDocument(
				documentOf([{ ...scalarType("Odd", "string"), kind: "widget" }]),
				{},
			);
			assert(
				invalid.model === undefined,
				"a kind outside the eight was mapped",
			);
			assert(
				invalid.diagnostics.some((one) =>
					one.code.endsWith(".UNSUPPORTED_CONSTRUCT"),
				),
				"a kind outside the eight raised no UNSUPPORTED_CONSTRUCT",
			);
		},
	},
	{
		caseId:
			"TC-1772 every construct kind and model member selects the Rust form the mapping table states",
		run(backend) {
			const rows = new Map(backend.table.rows.map((row) => [row.rowKey, row]));
			for (const kind of CONSTRUCT_KINDS)
				assert(rows.has(`kind:${kind}`), `no kind row for \`${kind}\``);
			const ir = JSON.parse(readFileSync(CONSTRUCTS_FIXTURE, "utf8"));
			const result = emitted(backend, ir);
			assert(
				result.state === "success",
				`the constructs fixture was refused: ${result.diagnostics.map((one) => `${one.code} ${one.message}`).join("; ")}`,
			);
			assert(
				result.diagnostics.length === 0,
				`the constructs fixture raised ${result.diagnostics.map((one) => one.code).join(", ")}`,
			);
			const file = (name) => {
				const text = result.files.get(`src/types/${name}.rs`);
				assert(typeof text === "string", `no module ${name}.rs was emitted`);
				return text;
			};
			const has = (name, needle, row) => {
				assert(rows.has(row), `the table carries no row \`${row}\``);
				assert(
					file(name).includes(needle),
					`${name}.rs carries no \`${needle}\`, which the row \`${row}\` states`,
				);
			};
			has(
				"order_line",
				"#[derive(Clone, Debug, PartialEq, Serialize)]",
				"kind:value_object",
			);
			has("shipment", "pub const OWNER: &str", "kind:nested_entity");
			has(
				"shipment",
				"pub const IDENTITY_FIELDS: &[&str]",
				"kind:nested_entity",
			);
			has(
				"order_aggregate",
				"pub const MEMBERS: &[&str]",
				"kind:aggregate_root",
			);
			has("order_status", "pub enum OrderStatus {", "kind:enumeration");
			has("order_placed", "pub const OCCURRENCE_FIELD: &str", "kind:event");
			has("order_placed", "pub fn placed_at(&self)", "kind:event");
			assert(
				!file("order_placed").includes("    pub placed_at:"),
				"an event's member is public, so a value can change after construction",
			);
			has(
				"order_lifecycle",
				"pub enum OrderLifecycleState {",
				"kind:state_machine",
			);
			has("order_lifecycle", "pub const TRANSITIONS:", "kind:state_machine");
			has("fulfilment", "pub const STEPS:", "kind:process");
			has("order_repository", "pub trait OrderRepository {", "kind:repository");
			has(
				"order_repository",
				"fn find_by_id(&mut self, id:",
				"kind:repository",
			);
			has("order_repository", "pub const PERSISTS: &[&str]", "kind:repository");
			has("ordering", "pub struct Ordering;", "kind:domain");
			has("ordering", "pub const VOCABULARY:", "kind:domain");
			has("order", "pub const SUPERTYPES: &[&str]", "construct:supertypes");
			has("order", "    pub labels:", "construct:supertypes");
			has("party", "pub const ABSTRACT: bool = true;", "construct:abstract");
			has("order", "pub const FIELD_SUBSETS:", "construct:subsets");
			has("order", "pub const FIELD_REDEFINES:", "construct:redefines");
			has(
				"order_lifecycle",
				"pub const OPERATION_CONTRACTS:",
				"construct:operation-contract",
			);
			assert(rows.has("construct:populations"), "no populations row");
			assert(
				result.files
					.get("src/identity.rs")
					.includes("pub const POPULATIONS: &[PopulationMeta]"),
				"identity.rs carries no POPULATIONS, which the row `construct:populations` states",
			);
			const model = mapped(backend, ir);
			for (const type of model.types) {
				if (!CONSTRUCT_KINDS.includes(type.kind)) continue;
				assert(
					type.row === `kind:${type.kind}`,
					`the ${type.kind} ${type.identity} selected ${type.row}`,
				);
			}
		},
	},
	{
		caseId:
			"TC-725 every kernel scalar maps to the Rust base the mapping table states",
		run(backend) {
			const rows = backend.table.rows.filter((row) => row.axis === "scalar");
			assert(
				rows.length === 10,
				`the table declares ${rows.length} kernel scalars, not ten`,
			);
			for (const row of rows) {
				const result = backend.mapping.mapDocument(
					documentOf([scalarType(`S${row.selector}`, row.selector)]),
					{},
				);
				if (row.rustForm === null) {
					assert(
						result.model === undefined,
						`the refused scalar \`${row.selector}\` was mapped`,
					);
					assert(
						result.diagnostics.some((one) => one.code === row.diagnosticCode),
						`the scalar \`${row.selector}\` raised no ${row.diagnosticCode}`,
					);
					continue;
				}
				assert(
					result.model !== undefined,
					`the scalar \`${row.selector}\` was refused: ${result.diagnostics.map((one) => one.message).join("; ")}`,
				);
				const expected = backend.degradation.expectedScalarType(row.rustForm);
				const observed = result.model.types[0].inner;
				assert(
					observed === expected,
					`the scalar \`${row.selector}\` carries ${observed}, and the table states ${expected}`,
				);
			}
			// A scalar outside the kernel is refused rather than admitted.
			const outside = backend.mapping.mapDocument(
				documentOf([scalarType("Odd", "decimal")]),
				{},
			);
			assert(
				outside.model === undefined,
				"a scalar outside the kernel was mapped",
			);
			assert(
				outside.diagnostics.some((one) =>
					one.code.endsWith(".UNSUPPORTED_SCALAR"),
				),
				"a scalar outside the kernel raised no UNSUPPORTED_SCALAR",
			);
		},
	},
	{
		caseId:
			"TC-725 the eight field-axis rows produce the member type and the serde attributes the table states",
		run(backend) {
			const rows = backend.table.rows.filter((row) =>
				/^field:(single|collection)\//.test(row.rowKey),
			);
			assert(
				rows.length === 8,
				`the table declares ${rows.length} axis rows, not eight`,
			);
			const ir = document(backend);
			const model = mapped(backend, ir);
			const record = model.types.find((one) => one.typeName.startsWith("Axes"));
			assert(
				record !== undefined && record.fields.length === 8,
				"the generated document carries no eight-member axis record",
			);
			const seen = new Set();
			for (const field of record.fields) {
				const row = rows.find((one) => one.rowKey === field.row);
				assert(
					row !== undefined,
					`the member ${field.ident} selected ${field.row}, which is no axis row`,
				);
				const expected = backend.degradation.expectedMemberType(
					row.rustForm,
					field.element,
				);
				assert(
					field.rustType === expected,
					`the member ${field.ident} on row ${row.rowKey} carries ${field.rustType}, and the table states ${expected}`,
				);
				seen.add(row.rowKey);
				// The attributes the table states, compared as sets: the table
				// writes `present_or_absent` by its name and the emitter by its
				// path, so the comparison is on the attribute's head.
				const heads = (list) => list.map((one) => one.split(" = ")[0]).sort();
				assert(
					heads(row.serdeAttributes).join(",") ===
						heads(field.serdeAttributes).join(","),
					`the member ${field.ident} on row ${row.rowKey} carries the attributes [${field.serdeAttributes.join(", ")}], and the table states [${row.serdeAttributes.join(", ")}]`,
				);
			}
			assert(
				seen.size === 8,
				`the axis record selected ${seen.size} distinct rows, not eight`,
			);
			assert(
				new Set(record.fields.map((one) => one.rustType)).size === 8,
				"the eight axis rows did not produce eight distinct member types",
			);

			// The ninth field row: an upper bound of zero is refused.
			const zero = backend.mapping.mapDocument(
				documentOf([
					scalarType("Text", "string"),
					{
						identity: `${NS}/type/Holder`,
						displayName: "Holder",
						kind: "record",
						roles: [],
						constraints: [],
						extensions: [],
						unknownPolicy: "reject",
						fields: [
							{
								identity: `${NS}/field/holder-none`,
								name: "none",
								typeRef: `${NS}/type/Text`,
								presence: "optional",
								nullable: false,
								defaultKind: "none",
								multiplicity: { lower: 0, upper: 0 },
							},
						],
					},
				]),
				{},
			);
			assert(
				zero.model === undefined,
				"a member whose multiplicity.upper is 0 was mapped",
			);
			assert(
				zero.diagnostics.some((one) =>
					one.code.endsWith(".UNSUPPORTED_MULTIPLICITY"),
				),
				"a member whose multiplicity.upper is 0 raised no UNSUPPORTED_MULTIPLICITY",
			);
		},
	},
	{
		caseId: "TC-725 the unknownPolicy rows dispose each kind exactly once",
		run(backend) {
			const rows = backend.table.rows.filter(
				(row) => row.axis === "unknownPolicy",
			);
			const policies = ["reject", "preserve", "surface"];
			const covered = new Map();
			for (const row of rows) {
				for (const kind of String(row.selector.kind).split("|")) {
					for (const policy of row.selector.policy === "any"
						? policies
						: [row.selector.policy]) {
						const key = `${kind}/${policy}`;
						assert(
							!covered.has(key),
							`the unknownPolicy rows dispose \`${key}\` twice: ${covered.get(key)} and ${row.rowKey}`,
						);
						covered.set(key, row.rowKey);
					}
				}
			}
			for (const kind of kinds(backend.table)) {
				for (const policy of policies) {
					assert(
						covered.has(`${kind}/${policy}`),
						`no unknownPolicy row disposes \`${kind}/${policy}\``,
					);
				}
			}
			// And the disposition the mapper takes is the one the row names.
			const records = {
				reject: "record-reject",
				preserve: "record-retain",
				surface: "record-retain",
			};
			const variants = {
				reject: "variant-closed",
				preserve: "variant-catchall",
				surface: "variant-catchall",
			};
			const expected = {
				value_object: records,
				nested_entity: records,
				aggregate_root: records,
				event: records,
				state_machine: records,
				process: records,
				enumeration: variants,
				record: {
					reject: "record-reject",
					preserve: "record-retain",
					surface: "record-retain",
				},
				entity: {
					reject: "record-reject",
					preserve: "record-retain",
					surface: "record-retain",
				},
				enum: {
					reject: "variant-closed",
					preserve: "variant-catchall",
					surface: "variant-catchall",
				},
				union: {
					reject: "variant-closed",
					preserve: "variant-catchall",
					surface: "variant-catchall",
				},
			};
			for (const kind of kinds(backend.table)) {
				for (const policy of policies) {
					const observed = backend.mapping.unknownDisposition(kind, policy);
					const wanted = expected[kind]?.[policy] ?? "inert";
					assert(
						observed === wanted,
						`\`${kind}/${policy}\` is disposed ${observed}, and the table's row says ${wanted}`,
					);
				}
			}
		},
	},
	{
		caseId:
			"TC-725 every defaultKind, extension and metadata row reaches the emitted crate",
		run(backend) {
			const ir = document(backend);
			const model = mapped(backend, ir);
			const defaults = new Set(
				model.types.flatMap((one) =>
					(one.fields ?? []).map((field) => field.defaultKind),
				),
			);
			for (const row of backend.table.rows.filter(
				(one) => one.axis === "defaultKind",
			)) {
				if (row.selector === "semantic") {
					// The one defaultKind the table refuses when the value is not one
					// the mapped type admits.
					continue;
				}
				assert(
					defaults.has(row.selector),
					`no generated member carries the defaultKind \`${row.selector}\``,
				);
			}
			const text = bytesOf(backend, ir, "generated");
			assert(
				text.includes("default_kind"),
				"the emitted crate carries no default-kind metadata",
			);
			assert(
				model.extensions.length > 0,
				"the generated document carries no extension node",
			);
			assert(
				text.includes("ExtensionMeta") || text.includes("extensions"),
				"the emitted crate carries no extension metadata",
			);
			for (const member of [
				"roles",
				"origin",
				"relationships",
				"operations",
				"clauses",
				"occurrences",
			]) {
				assert(
					text.includes(member),
					`the emitted crate carries no \`${member}\` contract metadata`,
				);
			}
			// A semantic default whose value the mapped type does not admit is
			// refused rather than emitted. The check is in the emitter, because
			// it needs the member's rendered Rust type, so the refusal is read
			// off an emission rather than off a mapping.
			const bad = emitted(
				backend,
				documentOf([
					scalarType("Count", "integer"),
					{
						identity: `${NS}/type/Holder`,
						displayName: "Holder",
						kind: "record",
						roles: [],
						constraints: [],
						extensions: [],
						unknownPolicy: "reject",
						fields: [
							{
								identity: `${NS}/field/holder-count`,
								name: "count",
								typeRef: `${NS}/type/Count`,
								presence: "required",
								nullable: false,
								defaultKind: "semantic",
								defaultValue: "not-an-integer",
								multiplicity: { lower: 1, upper: 1 },
							},
						],
					},
				]),
			);
			assert(
				bad.files.size === 0 &&
					bad.diagnostics.some((one) =>
						one.code.endsWith(".INVALID_DEFAULT_VALUE"),
					),
				"a semantic default outside the member's Rust type raised no INVALID_DEFAULT_VALUE",
			);
		},
	},
	{
		caseId:
			"TC-725 every indirection row materializes at the position the table names",
		run(backend) {
			const rows = backend.table.rows.filter(
				(row) => row.axis === "indirection",
			);
			assert(
				rows.length === 8,
				`the table declares ${rows.length} indirection rows, not eight`,
			);
			const ir = document(backend);
			const edges = backend.graph.collectEdges(ir);
			const positions = new Set(edges.map((one) => one.position));
			for (const position of ["direct", "collection", "identity"]) {
				assert(
					positions.has(position),
					`no generated edge materializes at the \`${position}\` position`,
				);
			}
			const graph = backend.graph.buildGraph(ir);
			assert(
				graph.boxed.size > 0,
				"the generated document closes a cycle through direct positions and no edge was boxed",
			);
			for (const key of graph.boxed) {
				const edge = edges.find((one) => one.edgeKey === key);
				assert(
					edge !== undefined,
					`the boxed edge \`${key}\` is in no edge list`,
				);
				assert(
					edge.position === "direct",
					`the edge \`${key}\` is boxed at the \`${edge.position}\` position, and only a direct position may be boxed`,
				);
			}
			const model = mapped(backend, ir);
			const boxedMembers = model.types.flatMap((one) =>
				(one.fields ?? []).filter((field) => field.boxed === true),
			);
			assert(
				boxedMembers.length > 0,
				"no member of the cyclic record is boxed",
			);
			for (const field of boxedMembers) {
				assert(
					field.element.startsWith("Box<"),
					`the member ${field.ident} is boxed by the graph and carries ${field.element}`,
				);
			}
			for (const type of model.types) {
				for (const field of type.fields ?? []) {
					if (field.boxed === true || !field.collection) continue;
					assert(
						!field.element.startsWith("Box<"),
						`the collection member ${field.ident} carries a Box the table says a Vec already provides`,
					);
				}
			}
		},
	},
	{
		caseId:
			"TC-725 every constraint keyword lowers onto every subject its applicability row admits",
		run(backend) {
			for (const [keyword, subjects] of Object.entries(KEYWORD_APPLICABILITY)) {
				for (const subject of subjects) {
					const resolved = resolvedFor(subject, backend.table);
					const definition = {
						identity: `${NS}/type/${keyword}-${subject}`,
						constraints: [
							{
								identity: `${NS}/constraint/${keyword}-${subject}`,
								keyword,
								operands: operandsFor(keyword, subject),
								appliesTo: `${NS}/type/${keyword}-${subject}`,
							},
						],
					};
					const lowered = backend.constraints.lowerConstraints(
						definition,
						resolved,
						{},
					);
					const notApplicable = lowered.diagnostics.filter((one) =>
						one.code.endsWith(".CONSTRAINT_NOT_APPLICABLE"),
					);
					assert(
						notApplicable.length === 0,
						`\`${keyword}\` on a ${subject} subject is admitted by the applicability table and was refused as not applicable`,
					);
					const lowerable = lowered.checks.length === 1;
					const refused = lowered.diagnostics.length === 1;
					assert(
						lowerable !== refused,
						`\`${keyword}\` on a ${subject} subject produced ${lowered.checks.length} checks and ${lowered.diagnostics.length} diagnostics, which is neither a lowering nor a named refusal`,
					);
					if (refused) {
						const code = lowered.diagnostics[0].code;
						const named = ["UNORDERED_SUBJECT", "UNKNOWN_FORMAT"].some((leaf) =>
							code.endsWith(`.${leaf}`),
						);
						assert(
							named,
							`\`${keyword}\` on a ${subject} subject was refused with the unnamed ${code}`,
						);
					}
				}
			}
			// The negative half: a keyword its applicability row does not admit is
			// refused, so a widened row is a failing case rather than a quiet one.
			const outside = backend.constraints.lowerConstraints(
				{
					identity: `${NS}/type/pattern-on-integer`,
					constraints: [
						{
							identity: `${NS}/constraint/pattern-on-integer`,
							keyword: "pattern",
							operands: { regex: "^[a-z]+$" },
							appliesTo: `${NS}/type/pattern-on-integer`,
						},
					],
				},
				{ kind: "scalar", scalar: "integer" },
				{},
			);
			assert(
				outside.diagnostics.some((one) =>
					one.code.endsWith(".CONSTRAINT_NOT_APPLICABLE"),
				),
				"`pattern` on an integer subject is outside the applicability table and was not refused",
			);
		},
	},
	{
		caseId:
			"TC-725 every registered diagnostic code is disposed as its severity requires and named by a live path",
		run(backend) {
			const entries = backend.diagnostics.REGISTERED_ENTRIES;
			// The count is a lower bound, not an equality: the exact census of the
			// registry is the branch register's job, and a code added there
			// without a case is already a failing gate. Restating the number here
			// would make adding a code fail twice and say less the second time.
			assert(
				entries.length >= 21,
				`the registry carries ${entries.length} codes, fewer than the twenty-one FR-058 declares`,
			);
			assert(
				new Set(entries.map((one) => one.code)).size === entries.length,
				"the registry carries one code twice",
			);
			// Every module, the registry included: `DIAGNOSTIC_LIMIT_REACHED` is
			// constructed inside `applyDiagnosticLimit`, which is as live a path
			// as any. The form searched for is the *member access*, which is the
			// only way this bundle is allowed to name a code, so a code named
			// only as a declaration key is still reported unreachable.
			const sources = [...backend.sources.entries()];
			const published = new Set(backend.publishedCodes);
			assert(
				published.size > 0,
				"the published code set was not resolved, so the reader's half of the registry is checked against nothing",
			);
			for (const entry of entries) {
				assert(
					entry.blocking === (entry.severity === "error"),
					`${entry.code} is severity \`${entry.severity}\` and blocking \`${entry.blocking}\`, which the refusal rule cannot act on`,
				);
				assert(
					typeof entry.rule === "string" && entry.rule.length > 0,
					`${entry.code} states no rule`,
				);
				const leaf = entry.code.split(".").at(-1);
				if (entry.code.startsWith("agent-ix.semantic-ir.")) {
					// The published half is decided by the reader in `crates/`, not
					// by this generator, so its liveness is the published set
					// carrying the code — a generator path would be the wrong
					// evidence and the wrong namespace.
					assert(
						published.has(entry.code),
						`${entry.code} is carried as published and the published set does not declare it`,
					);
					continue;
				}
				const named = sources.some(([, text]) =>
					text.includes(`RUST_BACKEND_CODES.${leaf}`),
				);
				assert(
					named,
					`${entry.code} is registered and no live generator path names it`,
				);
			}
			// A blocking code blocks: a refused document emits nothing.
			const refused = backend.mapping.mapDocument(
				documentOf([scalarType("Blob", "bytes")]),
				{},
			);
			assert(
				refused.model === undefined,
				"a document carrying a blocking diagnostic was mapped anyway",
			);
			assert(
				backend.diagnostics.hasBlocking(refused.diagnostics),
				"the bytes refusal is not blocking",
			);
		},
	},
	{
		caseId:
			"TC-725 every identifier renderer derives from the source the requirement names and refuses a collision",
		run(backend) {
			const type = (displayName) => ({
				identity: `${NS}/type/FR-001`,
				displayName,
			});
			assert(
				backend.names.typeName(type("http-status-code")).value ===
					"HttpStatusCode",
				"typeName does not derive UpperCamelCase from the display name",
			);
			assert(
				backend.names.moduleName(type("HTTPStatusCode")).value ===
					"http_status_code",
				"moduleName does not derive snake_case from the display name",
			);
			assert(
				backend.names.constantName({
					identity: `${NS}/type/Status`,
					name: "Status",
				}).value === "STATUS",
				"constantName does not derive SCREAMING_SNAKE_CASE",
			);
			assert(
				backend.names.memberName({
					identity: `${NS}/field/x`,
					name: "createdAt",
				}).value === "created_at",
				"memberName does not derive snake_case from the wire name",
			);
			assert(
				backend.names.variantName({
					identity: `${NS}/variant/x`,
					name: "in-review",
				}).value === "InReview",
				"variantName does not derive UpperCamelCase from the wire name",
			);
			assert(
				backend.names.crateName("agent-ix/conformance").value ===
					"agent-ix-conformance",
				"crateName does not replace the separator Cargo forbids",
			);
			// A member whose derived identifier differs from its wire name carries
			// the rename, and one that does not, does not.
			assert(
				backend.names.serdeRename("created_at", "createdAt") === "createdAt",
				"a derived identifier that differs from the wire name emits no rename",
			);
			assert(
				backend.names.serdeRename("draft", "draft") === undefined,
				"a derived identifier equal to the wire name emits a rename that says nothing",
			);
			// Each declared scope refuses a collision rather than suffixing it.
			for (const scope of Object.values(backend.names.SCOPES)) {
				const collisions = backend.names.collisionsIn(scope, [
					{ identifier: "Thing", identity: `${NS}/type/thing` },
					{ identifier: "Thing", identity: `${NS}/type/Thing` },
				]);
				assert(
					collisions.length === 1,
					`a collision in ${scope} was not refused`,
				);
				assert(
					collisions[0].code.endsWith(".NAME_COLLISION"),
					`a collision in ${scope} raised ${collisions[0].code}`,
				);
			}
			// An unrenderable character is a refusal, never a deletion.
			// `名前` renders faithfully — Rust admits it — so the refusal case is
			// a character `XID_Continue` does not admit, which is dropped by no
			// renderer.
			const refused = backend.names.typeName(type("a€b"));
			assert(
				refused.ok !== true,
				"a character outside XID_Continue was rendered rather than refused",
			);
			assert(
				refused.diagnostic.code.endsWith(".UNRENDERABLE_NAME"),
				"an unrenderable character raised no UNRENDERABLE_NAME",
			);
		},
	},
	{
		caseId:
			"TC-725 a bound and a length render the comparison their keyword names",
		run(backend) {
			const ir = documentOf([
				scalarType("Bounded", "integer", [
					{
						identity: `${NS}/constraint/min`,
						keyword: "min",
						operands: { value: 3 },
						appliesTo: `${NS}/type/Bounded`,
					},
					{
						identity: `${NS}/constraint/max`,
						keyword: "max",
						operands: { value: 9 },
						appliesTo: `${NS}/type/Bounded`,
					},
				]),
				scalarType("Named", "string", [
					{
						identity: `${NS}/constraint/minLength`,
						keyword: "minLength",
						operands: { value: 2 },
						appliesTo: `${NS}/type/Named`,
					},
					{
						identity: `${NS}/constraint/maxLength`,
						keyword: "maxLength",
						operands: { value: 8 },
						appliesTo: `${NS}/type/Named`,
					},
				]),
			]);
			const text = bytesOf(backend, ir, "generated");
			// A minimum is violated below it and a maximum above it. The emitted
			// comparison is stated here rather than read back from the emitter.
			assert(
				/if value < 3i64 \{/.test(text),
				"a `min` of 3 does not render `value < 3`",
			);
			assert(
				/if value > 9i64 \{/.test(text),
				"a `max` of 9 does not render `value > 9`",
			);
			assert(
				/chars\(\)\.count\(\) < 2usize \{/.test(text),
				"a `minLength` of 2 does not render `count() < 2`",
			);
			assert(
				/chars\(\)\.count\(\) > 8usize \{/.test(text),
				"a `maxLength` of 8 does not render `count() > 8`",
			);
		},
	},
	{
		caseId:
			"TC-725 a record that rejects unknown members denies unknown fields and one that retains them flattens",
		run(backend) {
			const record = (name, policy) => ({
				identity: `${NS}/type/${name}`,
				displayName: name,
				kind: "record",
				roles: [],
				constraints: [],
				extensions: [],
				unknownPolicy: policy,
				fields: [
					{
						identity: `${NS}/field/${name}-id`,
						name: "id",
						typeRef: `${NS}/type/Text`,
						presence: "required",
						nullable: false,
						defaultKind: "none",
						multiplicity: { lower: 1, upper: 1 },
					},
				],
			});
			// The record's own module, not the whole crate: the pinned support
			// module carries the attribute on structures of its own, and a scan
			// over every emitted byte would find it there whatever the record's
			// policy said.
			const moduleOf = (name, policy) => {
				const result = emitted(
					backend,
					documentOf([scalarType("Text", "string"), record(name, policy)]),
					name.toLowerCase(),
				);
				const text = result.files.get(`src/types/${name.toLowerCase()}.rs`);
				assert(
					text !== undefined,
					`the crate emitted no module for the ${policy} record`,
				);
				return text;
			};
			const closed = moduleOf("Closed", "reject");
			const open = moduleOf("Open", "preserve");
			const attribute = `${"deny_unknown"}_fields`;
			assert(
				closed.includes(attribute),
				"a record whose unknownPolicy is `reject` does not deny unknown fields",
			);
			assert(
				!open.includes(attribute),
				"a record whose unknownPolicy is `preserve` denies unknown fields, so the members it must retain are refused",
			);
			assert(
				open.includes("unknown_members"),
				"a record whose unknownPolicy is `preserve` retains no unknown members",
			);
		},
	},
	{
		caseId:
			"TC-725 a pattern outside the expressible subset is classified unsupported and refused",
		run(backend) {
			// A backreference: outside the declared subset by construction, and
			// not a registry key, so the only honest classification is a refusal.
			const inexpressible = "^(a)\\1$";
			assert(
				backend.patterns.classifyPattern(inexpressible) === "unsupported",
				"a backreference is not classified unsupported, so a pattern this backend cannot express would be emitted as one it can",
			);
			assert(
				backend.patterns.classifyPattern("^[a-z]+$") === "expressible",
				"a plain character class is not classified expressible",
			);
			// And the expressible half lowers rather than being refused: the guard
			// that names `unsupported` must name that classification and no other.
			const expressible = backend.constraints.lowerConstraints(
				{
					identity: `${NS}/type/Plain`,
					constraints: [
						{
							identity: `${NS}/constraint/plain`,
							keyword: "pattern",
							operands: { regex: "^[a-z]+$" },
							appliesTo: `${NS}/type/Plain`,
						},
					],
				},
				{ kind: "scalar", scalar: "string" },
				{},
			);
			assert(
				expressible.diagnostics.length === 0,
				`an expressible pattern was refused: ${expressible.diagnostics.map((one) => one.message).join("; ")}`,
			);
			assert(
				expressible.checks.length === 1 &&
					expressible.checks[0].form === "matcher",
				"an expressible pattern did not lower to a matcher",
			);
			const lowered = backend.constraints.lowerConstraints(
				{
					identity: `${NS}/type/Odd`,
					constraints: [
						{
							identity: `${NS}/constraint/odd`,
							keyword: "pattern",
							operands: { regex: inexpressible },
							appliesTo: `${NS}/type/Odd`,
						},
					],
				},
				{ kind: "scalar", scalar: "string" },
				{},
			);
			assert(
				lowered.checks.length === 0,
				"an inexpressible pattern was lowered to a check",
			);
			assert(
				lowered.diagnostics.some((one) =>
					one.code.endsWith(".UNSUPPORTED_PATTERN"),
				),
				"an inexpressible pattern raised no UNSUPPORTED_PATTERN",
			);
		},
	},
	{
		caseId:
			"TC-725 an operation's parameter and return metadata carry the mapped type its axes state",
		run(backend) {
			const ir = document(backend);
			const model = mapped(backend, ir);
			const owner = model.types.find(
				(one) => (one.operations ?? []).length > 0,
			);
			assert(
				owner !== undefined,
				"the generated document declares no operation, so the operation edge is exercised by nothing",
			);
			const operation = owner.operations[0];
			assert(
				operation.params.length >= 2,
				"the generated operation carries too few parameters to exercise the axes",
			);
			const text = bytesOf(backend, ir, "generated");
			// The metadata type an operation edge carries is composed by the same
			// three axes as a member's, so the table's rows state it. `hints` is
			// optional, nullable and collection-valued; `size` is none of those.
			const hints = operation.params.find((one) => one.name === "hints");
			const size = operation.params.find((one) => one.name === "size");
			assert(
				hints !== undefined && size !== undefined,
				"the generated operation does not carry the two declared parameters",
			);
			const row = backend.table.rows.find(
				(one) => one.rowKey === "field:collection/nullable/optional",
			);
			const element = `crate::${model.types.find((one) => one.identity === hints.typeRef).typeName}`;
			const expected = backend.degradation.expectedMemberType(
				row.rustForm,
				element,
			);
			assert(
				text.includes(`rust_type: "${expected}"`),
				`the metadata of the optional, nullable, collection-valued parameter does not carry ${expected}`,
			);
			const plain = `crate::${model.types.find((one) => one.identity === size.typeRef).typeName}`;
			assert(
				text.includes(`rust_type: "${plain}"`),
				`the metadata of the required parameter does not carry ${plain}`,
			);
			// The return is optional, so its metadata type is wrapped once.
			const returned = `crate::${model.types.find((one) => one.identity === operation.returns.typeRef).typeName}`;
			assert(
				text.includes(`rust_type: "Option<${returned}>"`),
				`the metadata of the optional return does not carry Option<${returned}>`,
			);
			// The parameter scope is one of the four the derivation is injective
			// over, and the metadata carries the derived name.
			assert(
				text.includes('rust_name: "size"'),
				"the parameter metadata carries no derived identifier",
			);
		},
	},
	{
		caseId:
			"TC-729 the degradation scan names a declaration that carries a degraded type",
		run(backend) {
			const ir = document(backend);
			const model = mapped(backend, ir);
			const clean = backend.degradation.scanDegradation(model, backend.table);
			assert(
				clean.length === 0,
				`the pristine model scans degraded: ${backend.degradation.describeDegradation(clean).join("; ")}`,
			);
			// The scan's own negative control, run here so that a scan which
			// cannot fail fails this case: a declaration edited to carry `String`
			// where the table states a generated newtype must be named.
			const injected = {
				...model,
				types: model.types.map((one) =>
					one.kind === "scalar" && one.scalar === "uuid"
						? { ...one, inner: "String" }
						: one,
				),
			};
			const found = backend.degradation.scanDegradation(
				injected,
				backend.table,
			);
			assert(
				found.length === 1,
				`the injected substitution was named ${found.length} times, not once`,
			);
			assert(
				found[0].observed === "String" &&
					found[0].expected === "crate::support::Uuid",
				"the scan does not name the degraded declaration's expected and observed types",
			);
		},
	},
]);

/** Runs the battery, optionally suppressing named cases (FR-062-AC-4). */
export function runDetectors(backend, options = {}) {
	const suppress = new Set(options.suppress ?? []);
	const results = [];
	for (const detector of DETECTORS) {
		if (suppress.has(detector.caseId)) {
			results.push({ caseId: detector.caseId, ok: true, suppressed: true });
			continue;
		}
		try {
			detector.run(backend);
			results.push({ caseId: detector.caseId, ok: true });
		} catch (error) {
			results.push({
				caseId: detector.caseId,
				ok: false,
				failure: String(error?.message ?? error),
			});
		}
	}
	return results;
}
