/**
 * FR-137 — semantic identity is spelled alike in every generated package.
 * Test cases TC-1538, TC-1540..TC-1544 of `spec/tests.md`.
 *
 * ADR-0007 rules that the emitted set is a contract over *concepts* realised
 * idiomatically per language, and that the retired `metadata` name is not
 * used for any of them. This file is the gate on that.
 *
 * It reads the committed goldens rather than generating into a temporary
 * directory. That is deliberate and is not the stub failure mode: the goldens
 * exist *to be byte-compared*, they are regenerated by `make rust-goldens` and
 * the TypeScript generator rather than written by this file, and `make
 * rust-check` already proves that regenerating them reproduces their bytes. A
 * test that generated its own package and then asserted against it would assert
 * only that the generator agrees with itself.
 *
 * Requirement ids are written on each case rather than in this header, so that
 * each binds the row it names rather than binding nothing.
 */

import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
	FIXED_API_SURFACE,
	PACKAGE_FILES,
} from "../src/compiler/backends/typescript-v1/package-layout.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (path: string): string => readFileSync(path, "utf8");

const RUST_GOLDENS = resolve(root, "test/fixtures/rust-serde/goldens");
const TS_EXPECTED = resolve(root, "test/fixtures/backends/typescript/expected");

const rustGoldens = (): string[] =>
	readdirSync(RUST_GOLDENS).filter((name) =>
		statSync(join(RUST_GOLDENS, name)).isDirectory(),
	);

/** The semantic identity declarations a generated crate carries. */
const RUST_IDENTITY_DECLARATIONS = ["TypeMeta", "FieldMeta", "TYPES"];

/**
 * Every export the retired `metadata.ts` declared, read off that file before it
 * was retired. This is the evidence for the no-loss criterion: the list is
 * historical fact, not a restatement of what the package exports today.
 */
const RETIRED_METADATA_EXPORTS = [
	"DOCUMENT_EXTENSIONS",
	"OCCURRENCES",
	"TYPE_OPERATIONS",
	"TYPE_CLAUSES",
	"TYPE_VARIANTS",
	"TYPE_CONSTRAINTS",
	"FIELD_DEFAULT",
];

const exportedNames = (source: string): Set<string> => {
	const names = new Set<string>();
	for (const match of source.matchAll(
		/^export\s+(?:const|type|interface|function|class)\s+([A-Za-z_$][\w$]*)/gm,
	)) {
		names.add(match[1]);
	}
	return names;
};

describe("FR-137 identity is spelled alike in every package", () => {
	/** Traces: FR-137-AC-2 */
	it("TC-1538 emits the Rust semantic identity in src/identity.rs and emits no src/metadata.rs", () => {
		for (const golden of rustGoldens()) {
			const crate = join(RUST_GOLDENS, golden, "src");
			const emitted = readdirSync(crate);
			expect(emitted, `${golden} must not emit metadata.rs`).not.toContain(
				"metadata.rs",
			);
			const identity = read(join(crate, "identity.rs"));
			for (const declaration of RUST_IDENTITY_DECLARATIONS) {
				expect(
					identity,
					`${golden}: identity.rs must declare ${declaration}`,
				).toMatch(new RegExp(`\\b(?:struct|const) ${declaration}\\b`));
			}
			const lib = read(join(crate, "lib.rs"));
			expect(lib).toMatch(/^pub mod identity;$/m);
			expect(lib).not.toMatch(/\bmetadata\b/);
		}
	});

	/** Traces: FR-137-AC-4, FR-137-CON-1 */
	it("TC-1540 still declares every export the retired metadata.ts carried, under the same name", () => {
		const declared = new Set<string>();
		for (const file of PACKAGE_FILES.filter((name) => name.endsWith(".ts"))) {
			for (const name of exportedNames(read(join(TS_EXPECTED, file)))) {
				declared.add(name);
			}
		}
		for (const name of RETIRED_METADATA_EXPORTS) {
			expect(declared, `${name} must still be declared`).toContain(name);
		}
	});

	/** Traces: FR-137-AC-5 */
	it("TC-1541 emits no artifact whose name denotes metadata, in any implemented target", () => {
		const offenders: string[] = [];
		const walk = (directory: string): void => {
			for (const entry of readdirSync(directory)) {
				const path = join(directory, entry);
				if (statSync(path).isDirectory()) {
					walk(path);
					continue;
				}
				if (/(^|[^a-z])metadata([^a-z]|$)/i.test(entry)) {
					offenders.push(path);
				}
			}
		};
		walk(RUST_GOLDENS);
		walk(TS_EXPECTED);
		walk(resolve(root, "packages/semantic-kernel"));
		expect(offenders).toEqual([]);
	});

	/** Traces: FR-137-AC-6 */
	it("TC-1542 names where every ADR-0007 concept lands, in every implemented backend's specification", () => {
		const CONCEPTS = [
			"Types",
			"Validation",
			"Diagnostics",
			"Semantic identity",
		];
		const BACKEND_SPECS = [
			"spec/functional/FR-056-emit-the-generated-rust-crate.md",
			"spec/functional/FR-065-generate-the-esm-package-and-export-surface.md",
			"spec/functional/FR-100-map-semantic-ir-to-json-schema.md",
			"spec/functional/FR-136-register-the-python-backends-in-the-generation-seam.md",
		];
		for (const spec of BACKEND_SPECS) {
			const source = read(resolve(root, spec));
			expect(source, `${spec} must carry an emitted-set section`).toContain(
				"## Emitted set (ADR-0007)",
			);
			const section = source.split("## Emitted set (ADR-0007)")[1];
			for (const concept of CONCEPTS) {
				const row = section
					.split("\n")
					.find((line) => line.startsWith(`| ${concept} |`));
				expect(row, `${spec} must name where ${concept} lands`).toBeTruthy();
				// A row naming the concept and leaving the answer blank says
				// nothing. This gates that an answer is present and not a
				// placeholder; whether it is the right answer is a review
				// judgement, and claiming otherwise here would be the tautology
				// the standing stub guard names.
				expect(
					(row as string).split("|")[2].trim().length,
					`${spec}: the ${concept} row must say where it lands`,
				).toBeGreaterThan(7);
			}
		}

		// JSON Schema realizes semantic identity as an annotation keyword on
		// each delegated schema. Read the artifacts, not merely the specification
		// that describes them: otherwise the TypeSpec-emitted tree could silently
		// lose the concept.
		const schemas = resolve(
			root,
			"packages/semantic-core/generated/json-schema",
		);
		for (const name of readdirSync(schemas).filter((entry) =>
			entry.endsWith(".json"),
		)) {
			const typeName = name.replace(/\.json$/, "");
			const schema = JSON.parse(read(join(schemas, name))) as Record<
				string,
				unknown
			>;
			expect(schema["x-agent-ix-semantic-id"], name).toBe(
				`ix://agent-ix/semantic-core/${typeName}`,
			);
		}
	});

	/** Traces: FR-137-AC-8, FR-137-CON-2 */
	it("TC-1544 keeps the retired metadata name out of the TypeScript export surface", () => {
		const surface = new Set(FIXED_API_SURFACE);
		expect(surface).not.toContain("SEMANTIC_METADATA");
		const barrel = read(join(TS_EXPECTED, "index.ts"));
		expect(barrel).not.toMatch(/metadata/);
	});
});
