//! The semantic identity of everything this crate declares, emitted beside
//! the types it belongs to.
//!
//! Every member the IR carries survives generation into a `const` here:
//! `roles`, `origin`, `relationships`, `operations`, `clauses`,
//! `occurrences` and `extensions`. An `operation` reaches the crate as
//! data and never as a Rust function: it has no body in the IR, so a
//! generated function would have nothing to put in one.
//!
//! The crate's *provenance* — what it was generated from and by — is a
//! different concept and lives in `provenance.rs` (FR-137, ADR-0007). The two
//! were once named `identity.rs` and `metadata.rs` here and the opposite way
//! round in the generated TypeScript package, which is the defect that
//! renaming repairs.

/// A source locus the IR carried.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SourceLocusMeta {
    /// The identity of the source the node came from.
    pub source_identity: &'static str,
    /// The path inside that source.
    pub path: &'static str,
    /// The one-based start line.
    pub start_line: u64,
    /// The one-based start column.
    pub start_column: u64,
    /// The one-based end line, where the IR carried one.
    pub end_line: Option<u64>,
    /// The one-based end column, where the IR carried one.
    pub end_column: Option<u64>,
}

/// A generated origin the IR carried.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct GeneratedOriginMeta {
    /// The generator's semantic identity.
    pub generator_identity: &'static str,
    /// The generator's version.
    pub generator_version: &'static str,
    /// The identities the generator consumed.
    pub input_identities: &'static [&'static str],
}

/// The origin of a node: a source locus, or a generation record.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct OriginMeta {
    /// The source locus, where the node came from a source.
    pub source: Option<SourceLocusMeta>,
    /// The generation record, where the node was generated.
    pub generated: Option<GeneratedOriginMeta>,
}

/// A multiplicity the IR carried.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct MultiplicityMeta {
    /// The lower bound.
    pub lower: u64,
    /// The upper bound, where the IR declared one.
    pub upper: Option<u64>,
    /// Whether the collection is ordered, where the IR declared it.
    pub ordered: Option<bool>,
    /// Whether the collection's items are unique, where the IR declared it.
    pub unique: Option<bool>,
}

/// An extension the IR carried.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ExtensionMeta {
    /// The extension's semantic identity.
    pub identity: &'static str,
    /// The extension's version.
    pub version: &'static str,
    /// Whether a consumer must understand the extension.
    pub required: bool,
    /// The capability the extension claims.
    pub capability: Option<&'static str>,
    /// The extension payload, as canonical JSON text.
    pub payload: &'static str,
}

/// A relationship the IR carried.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RelationshipMeta {
    /// The relationship's semantic identity.
    pub identity: &'static str,
    /// The verb.
    pub verb: &'static str,
    /// The edge category.
    pub category: &'static str,
    /// Whether the relationship is composite.
    pub composite: bool,
    /// The target type's semantic identity.
    pub target: &'static str,
    /// The relationship's multiplicity.
    pub multiplicity: MultiplicityMeta,
    /// The relationship's origin.
    pub origin: OriginMeta,
}

/// One parameter of an operation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ParamMeta {
    /// The parameter's semantic identity.
    pub identity: &'static str,
    /// The parameter's wire name.
    pub name: &'static str,
    /// The derived Rust identifier.
    pub rust_name: &'static str,
    /// The parameter type's semantic identity.
    pub type_ref: &'static str,
    /// The mapped Rust type, as text.
    pub rust_type: &'static str,
    /// Whether the parameter is nullable.
    pub nullable: bool,
    /// The parameter's multiplicity.
    pub multiplicity: MultiplicityMeta,
}

/// An operation's return.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ReturnMeta {
    /// The return type's semantic identity.
    pub type_ref: &'static str,
    /// The mapped Rust type, as text.
    pub rust_type: &'static str,
    /// Whether the return is nullable.
    pub nullable: bool,
    /// The return's multiplicity.
    pub multiplicity: MultiplicityMeta,
}

/// An operation the IR carried.
///
/// It is metadata, not a function: the IR gives an operation no body.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct OperationMeta {
    /// The operation's semantic identity.
    pub identity: &'static str,
    /// The operation's wire name.
    pub name: &'static str,
    /// The parameters.
    pub params: &'static [ParamMeta],
    /// The return, where the operation declares one.
    pub returns: Option<ReturnMeta>,
    /// The identifiers of the precondition clauses.
    pub pre: &'static [&'static str],
    /// The identifiers of the postcondition clauses.
    pub post: &'static [&'static str],
    /// The operation's origin.
    pub origin: OriginMeta,
}

/// A clause the IR carried.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ClauseMeta {
    /// The clause's semantic identity.
    pub identity: &'static str,
    /// The clause language.
    pub language: &'static str,
    /// The clause identifier operations refer to it by.
    pub clause_id: &'static str,
    /// The clause text.
    pub text: &'static str,
    /// The clause's source span, where the IR carried one.
    pub source_span: Option<SourceLocusMeta>,
    /// The clause's origin.
    pub origin: OriginMeta,
}

/// One generated field.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FieldMeta {
    /// The field's semantic identity.
    pub identity: &'static str,
    /// The field's wire name.
    pub name: &'static str,
    /// The derived Rust identifier.
    pub rust_name: &'static str,
    /// The field type's semantic identity.
    pub type_ref: &'static str,
    /// The mapped Rust member type, as text.
    pub rust_type: &'static str,
    /// The mapping-table row the member type came from.
    pub row: &'static str,
    /// The derived presence.
    pub presence: &'static str,
    /// Whether the field is nullable.
    pub nullable: bool,
    /// The field's multiplicity.
    pub multiplicity: MultiplicityMeta,
    /// The UCUM symbol the field carries, where it carries one.
    pub unit: Option<&'static str>,
    /// The field's default kind.
    pub default_kind: &'static str,
    /// The field's default value as canonical JSON text, where it carries one.
    pub default_value: Option<&'static str>,
    /// The field's origin.
    pub origin: OriginMeta,
}

/// One generated type.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct TypeMeta {
    /// The type's semantic identity.
    pub identity: &'static str,
    /// The type's display name.
    pub display_name: &'static str,
    /// The IR kind.
    pub kind: &'static str,
    /// The derived Rust type name.
    pub rust_name: &'static str,
    /// The roles the IR carried, in document order.
    pub roles: &'static [&'static str],
    /// The unknown-member policy.
    pub unknown_policy: &'static str,
    /// The type's origin.
    pub origin: OriginMeta,
    /// The type's fields, for a record.
    pub fields: &'static [FieldMeta],
    /// The type's relationships.
    pub relationships: &'static [RelationshipMeta],
    /// The type's operations.
    pub operations: &'static [OperationMeta],
    /// The type's clauses.
    pub clauses: &'static [ClauseMeta],
    /// The type's extensions.
    pub extensions: &'static [ExtensionMeta],
}

/// An occurrence the IR carried.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct OccurrenceMeta {
    /// The occurrence's semantic identity.
    pub identity: &'static str,
    /// The type the occurrence is an instance of.
    pub definition: &'static str,
    /// The observation timestamp the IR carried.
    pub observed_at: &'static str,
    /// The observed value, as canonical JSON text.
    pub value: &'static str,
}

/// Every generated type, in the order the contract declares them.
pub const TYPES: &[TypeMeta] = &[
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/ClauseLanguage",
        display_name: "ClauseLanguage",
        kind: "scalar",
        rust_name: "ClauseLanguage",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/ClauseLanguage.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/ClauseRef",
        display_name: "ClauseRef",
        kind: "record",
        rust_name: "ClauseRef",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/ClauseRef.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::clause_ref::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/ConstraintDecl",
        display_name: "ConstraintDecl",
        kind: "union",
        rust_name: "ConstraintDecl",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/ConstraintDecl.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/ConstraintKeyword",
        display_name: "ConstraintKeyword",
        kind: "enum",
        rust_name: "ConstraintKeyword",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/ConstraintKeyword.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/DecimalPolicy",
        display_name: "DecimalPolicy",
        kind: "record",
        rust_name: "DecimalPolicy",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/DecimalPolicy.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::decimal_policy::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/DecimalPolicyPrecision",
        display_name: "DecimalPolicyPrecision",
        kind: "scalar",
        rust_name: "DecimalPolicyPrecision",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/DecimalPolicy.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/DecimalPolicyScale",
        display_name: "DecimalPolicyScale",
        kind: "scalar",
        rust_name: "DecimalPolicyScale",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/DecimalPolicy.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/DefaultDecl",
        display_name: "DefaultDecl",
        kind: "record",
        rust_name: "DefaultDecl",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/DefaultDecl.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::default_decl::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/DefaultDeclValue",
        display_name: "DefaultDeclValue",
        kind: "record",
        rust_name: "DefaultDeclValue",
        roles: &[],
        unknown_policy: "preserve",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/DefaultDecl.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::default_decl_value::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/DefaultKind",
        display_name: "DefaultKind",
        kind: "enum",
        rust_name: "DefaultKind",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/DefaultKind.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/EdgeCategory",
        display_name: "EdgeCategory",
        kind: "enum",
        rust_name: "EdgeCategory",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/EdgeCategory.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/EnumValue",
        display_name: "EnumValue",
        kind: "record",
        rust_name: "EnumValue",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/EnumValue.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::enum_value::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/EnumValueDoc",
        display_name: "EnumValueDoc",
        kind: "scalar",
        rust_name: "EnumValueDoc",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/EnumValue.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/EnumValuesConstraint",
        display_name: "EnumValuesConstraint",
        kind: "record",
        rust_name: "EnumValuesConstraint",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/EnumValuesConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::enum_values_constraint::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/EnumValuesConstraintKeyword",
        display_name: "EnumValuesConstraintKeyword",
        kind: "enum",
        rust_name: "EnumValuesConstraintKeyword",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/EnumValuesConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/EnumValuesConstraintValues",
        display_name: "EnumValuesConstraintValues",
        kind: "union",
        rust_name: "EnumValuesConstraintValues",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/EnumValuesConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/ExclusiveMaxConstraint",
        display_name: "ExclusiveMaxConstraint",
        kind: "record",
        rust_name: "ExclusiveMaxConstraint",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/ExclusiveMaxConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::exclusive_max_constraint::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/ExclusiveMaxConstraintKeyword",
        display_name: "ExclusiveMaxConstraintKeyword",
        kind: "enum",
        rust_name: "ExclusiveMaxConstraintKeyword",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/ExclusiveMaxConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/ExclusiveMaxConstraintValue",
        display_name: "ExclusiveMaxConstraintValue",
        kind: "union",
        rust_name: "ExclusiveMaxConstraintValue",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/ExclusiveMaxConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/ExclusiveMinConstraint",
        display_name: "ExclusiveMinConstraint",
        kind: "record",
        rust_name: "ExclusiveMinConstraint",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/ExclusiveMinConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::exclusive_min_constraint::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/ExclusiveMinConstraintKeyword",
        display_name: "ExclusiveMinConstraintKeyword",
        kind: "enum",
        rust_name: "ExclusiveMinConstraintKeyword",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/ExclusiveMinConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/ExclusiveMinConstraintValue",
        display_name: "ExclusiveMinConstraintValue",
        kind: "union",
        rust_name: "ExclusiveMinConstraintValue",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/ExclusiveMinConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/FieldDecl",
        display_name: "FieldDecl",
        kind: "record",
        rust_name: "FieldDecl",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/FieldDecl.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::field_decl::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/FieldDeclIdentity",
        display_name: "FieldDeclIdentity",
        kind: "scalar",
        rust_name: "FieldDeclIdentity",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/FieldDecl.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/FieldDeclNullable",
        display_name: "FieldDeclNullable",
        kind: "scalar",
        rust_name: "FieldDeclNullable",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/FieldDecl.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/FieldDeclDoc",
        display_name: "FieldDeclDoc",
        kind: "scalar",
        rust_name: "FieldDeclDoc",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/FieldDecl.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/FormatConstraint",
        display_name: "FormatConstraint",
        kind: "record",
        rust_name: "FormatConstraint",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/FormatConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::format_constraint::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/FormatConstraintKeyword",
        display_name: "FormatConstraintKeyword",
        kind: "enum",
        rust_name: "FormatConstraintKeyword",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/FormatConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/FormatConstraintName",
        display_name: "FormatConstraintName",
        kind: "scalar",
        rust_name: "FormatConstraintName",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/FormatConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/Identifier",
        display_name: "Identifier",
        kind: "scalar",
        rust_name: "Identifier",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/Identifier.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/KernelScalar",
        display_name: "KernelScalar",
        kind: "enum",
        rust_name: "KernelScalar",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/KernelScalar.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MaxConstraint",
        display_name: "MaxConstraint",
        kind: "record",
        rust_name: "MaxConstraint",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/MaxConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::max_constraint::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MaxConstraintKeyword",
        display_name: "MaxConstraintKeyword",
        kind: "enum",
        rust_name: "MaxConstraintKeyword",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/MaxConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MaxConstraintValue",
        display_name: "MaxConstraintValue",
        kind: "union",
        rust_name: "MaxConstraintValue",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/MaxConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MaxLengthConstraint",
        display_name: "MaxLengthConstraint",
        kind: "record",
        rust_name: "MaxLengthConstraint",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/MaxLengthConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::max_length_constraint::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MaxLengthConstraintKeyword",
        display_name: "MaxLengthConstraintKeyword",
        kind: "enum",
        rust_name: "MaxLengthConstraintKeyword",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/MaxLengthConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MaxLengthConstraintValue",
        display_name: "MaxLengthConstraintValue",
        kind: "scalar",
        rust_name: "MaxLengthConstraintValue",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/MaxLengthConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MinConstraint",
        display_name: "MinConstraint",
        kind: "record",
        rust_name: "MinConstraint",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/MinConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::min_constraint::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MinConstraintKeyword",
        display_name: "MinConstraintKeyword",
        kind: "enum",
        rust_name: "MinConstraintKeyword",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/MinConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MinConstraintValue",
        display_name: "MinConstraintValue",
        kind: "union",
        rust_name: "MinConstraintValue",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/MinConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MinLengthConstraint",
        display_name: "MinLengthConstraint",
        kind: "record",
        rust_name: "MinLengthConstraint",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/MinLengthConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::min_length_constraint::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MinLengthConstraintKeyword",
        display_name: "MinLengthConstraintKeyword",
        kind: "enum",
        rust_name: "MinLengthConstraintKeyword",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/MinLengthConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MinLengthConstraintValue",
        display_name: "MinLengthConstraintValue",
        kind: "scalar",
        rust_name: "MinLengthConstraintValue",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/MinLengthConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/Multiplicity",
        display_name: "Multiplicity",
        kind: "record",
        rust_name: "Multiplicity",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/Multiplicity.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::multiplicity::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MultiplicityLower",
        display_name: "MultiplicityLower",
        kind: "scalar",
        rust_name: "MultiplicityLower",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/Multiplicity.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MultiplicityUpper",
        display_name: "MultiplicityUpper",
        kind: "scalar",
        rust_name: "MultiplicityUpper",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/Multiplicity.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MultiplicityOrdered",
        display_name: "MultiplicityOrdered",
        kind: "scalar",
        rust_name: "MultiplicityOrdered",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/Multiplicity.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/MultiplicityUnique",
        display_name: "MultiplicityUnique",
        kind: "scalar",
        rust_name: "MultiplicityUnique",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/Multiplicity.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/NonEmptyConstraint",
        display_name: "NonEmptyConstraint",
        kind: "record",
        rust_name: "NonEmptyConstraint",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/NonEmptyConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::non_empty_constraint::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/NonEmptyConstraintKeyword",
        display_name: "NonEmptyConstraintKeyword",
        kind: "enum",
        rust_name: "NonEmptyConstraintKeyword",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/NonEmptyConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/OperationDecl",
        display_name: "OperationDecl",
        kind: "record",
        rust_name: "OperationDecl",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/OperationDecl.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::operation_decl::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/PatternConstraint",
        display_name: "PatternConstraint",
        kind: "record",
        rust_name: "PatternConstraint",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/PatternConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::pattern_constraint::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/PatternConstraintKeyword",
        display_name: "PatternConstraintKeyword",
        kind: "enum",
        rust_name: "PatternConstraintKeyword",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/PatternConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/PatternConstraintRegex",
        display_name: "PatternConstraintRegex",
        kind: "scalar",
        rust_name: "PatternConstraintRegex",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/PatternConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/PatternConstraintDialect",
        display_name: "PatternConstraintDialect",
        kind: "enum",
        rust_name: "PatternConstraintDialect",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/PatternConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/RelationDecl",
        display_name: "RelationDecl",
        kind: "record",
        rust_name: "RelationDecl",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/RelationDecl.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::relation_decl::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/RelationDeclComposite",
        display_name: "RelationDeclComposite",
        kind: "scalar",
        rust_name: "RelationDeclComposite",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/RelationDecl.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/SemanticId",
        display_name: "SemanticId",
        kind: "scalar",
        rust_name: "SemanticId",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/SemanticId.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/SourceLocus",
        display_name: "SourceLocus",
        kind: "record",
        rust_name: "SourceLocus",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/SourceLocus.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::source_locus::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/SourceLocusPath",
        display_name: "SourceLocusPath",
        kind: "scalar",
        rust_name: "SemanticCoreSourceLocusPath",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/SourceLocus.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/SourceLocusStartLine",
        display_name: "SourceLocusStartLine",
        kind: "scalar",
        rust_name: "SourceLocusStartLine",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/SourceLocus.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/SourceLocusStartColumn",
        display_name: "SourceLocusStartColumn",
        kind: "scalar",
        rust_name: "SourceLocusStartColumn",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/SourceLocus.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/SourceLocusEndLine",
        display_name: "SourceLocusEndLine",
        kind: "scalar",
        rust_name: "SourceLocusEndLine",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/SourceLocus.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/SourceLocusEndColumn",
        display_name: "SourceLocusEndColumn",
        kind: "scalar",
        rust_name: "SourceLocusEndColumn",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/SourceLocus.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/TypeRef",
        display_name: "TypeRef",
        kind: "record",
        rust_name: "TypeRef",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/TypeRef.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::type_ref::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/TypeRefTarget",
        display_name: "TypeRefTarget",
        kind: "union",
        rust_name: "TypeRefTarget",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/TypeRef.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/UniqueConstraint",
        display_name: "UniqueConstraint",
        kind: "record",
        rust_name: "UniqueConstraint",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/UniqueConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: crate::types::unique_constraint::FIELDS,
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/UniqueConstraintKeyword",
        display_name: "UniqueConstraintKeyword",
        kind: "enum",
        rust_name: "UniqueConstraintKeyword",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/UniqueConstraint.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
    crate::identity::TypeMeta {
        identity: "ix://agent-ix/semantic-core/type/UnitSymbol",
        display_name: "UnitSymbol",
        kind: "scalar",
        rust_name: "UnitSymbol",
        roles: &[],
        unknown_policy: "reject",
        origin: crate::identity::OriginMeta {
            source: Some(crate::identity::SourceLocusMeta {
                source_identity: "ix://agent-ix/semantic-core",
                path: "packages/semantic-core/generated/json-schema/UnitSymbol.json",
                start_line: 1,
                start_column: 1,
                end_line: None,
                end_column: None,
            }),
            generated: None,
        },
        fields: &[],
        relationships: &[],
        operations: &[],
        clauses: &[],
        extensions: &[],
    },
];

/// Every occurrence the contract carried, in document order.
pub const OCCURRENCES: &[OccurrenceMeta] = &[];

/// Every extension the contract package carried, in document order.
pub const PACKAGE_EXTENSIONS: &[ExtensionMeta] = &[];
