/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Generated by the Agent IX TypeScript semantic backend. Do not edit.
 * backend: ix://agent-ix/filament-core-data/backend/typescript@0.1.0
 * contract: 2.0.0
 * package: agent-ix/semantic-kernel@0.2.0
 * fingerprint: sha256:8939ef5559a1ff9d7265a65fd3e958a0ca52f47b91555f9865e819627e040c91
 */

/**
 * The validation vocabulary of this generated package: the closed structural
 * code register, the error and result shapes, the declared recursion bound, and
 * the small runtime the generated checks share.
 *
 * A constraint failure never draws from this register. It reports the
 * constraint's own `diagnosticCode`, which the semantic document carries, so a
 * consumer switching on a code is switching on the contract's vocabulary rather
 * than on this generator's.
 */

/** Every structural failure this package can report, as declared data. */
export const VALIDATION_CODES = {
	NOT_AN_OBJECT: "agent-ix.typescript-backend.NOT_AN_OBJECT",
	NOT_AN_ARRAY: "agent-ix.typescript-backend.NOT_AN_ARRAY",
	NOT_A_STRING: "agent-ix.typescript-backend.NOT_A_STRING",
	NOT_A_NUMBER: "agent-ix.typescript-backend.NOT_A_NUMBER",
	NOT_A_BOOLEAN: "agent-ix.typescript-backend.NOT_A_BOOLEAN",
	MISSING_REQUIRED: "agent-ix.typescript-backend.MISSING_REQUIRED",
	EXPLICIT_UNDEFINED: "agent-ix.typescript-backend.EXPLICIT_UNDEFINED",
	NULL_NOT_PERMITTED: "agent-ix.typescript-backend.NULL_NOT_PERMITTED",
	ACCESSOR_MEMBER: "agent-ix.typescript-backend.ACCESSOR_MEMBER",
	UNKNOWN_MEMBER: "agent-ix.typescript-backend.UNKNOWN_MEMBER",
	UNKNOWN_MEMBER_SURFACED:
		"agent-ix.typescript-backend.UNKNOWN_MEMBER_SURFACED",
	NOT_AN_INTEGER: "agent-ix.typescript-backend.NOT_AN_INTEGER",
	NOT_A_NUMBER_VALUE: "agent-ix.typescript-backend.NOT_A_NUMBER_VALUE",
	NOT_FINITE: "agent-ix.typescript-backend.NOT_FINITE",
	INTEGER_OUT_OF_SAFE_RANGE:
		"agent-ix.typescript-backend.INTEGER_OUT_OF_SAFE_RANGE",
	NOT_BASE64: "agent-ix.typescript-backend.NOT_BASE64",
	NOT_A_DECLARED_VARIANT: "agent-ix.typescript-backend.NOT_A_DECLARED_VARIANT",
	MISSING_DISCRIMINANT: "agent-ix.typescript-backend.MISSING_DISCRIMINANT",
	COLLECTION_TOO_SHORT: "agent-ix.typescript-backend.COLLECTION_TOO_SHORT",
	COLLECTION_TOO_LONG: "agent-ix.typescript-backend.COLLECTION_TOO_LONG",
	COLLECTION_NOT_UNIQUE: "agent-ix.typescript-backend.COLLECTION_NOT_UNIQUE",
	DEPTH_LIMIT_EXCEEDED: "agent-ix.typescript-backend.DEPTH_LIMIT_EXCEEDED",
	SHAPE_MISMATCH: "agent-ix.typescript-backend.SHAPE_MISMATCH",
} as const;

/** One structural code. A constraint code is any string the document declares. */
export type StructuralCode =
	(typeof VALIDATION_CODES)[keyof typeof VALIDATION_CODES];

/** The declared recursion bound. A value nested past it is refused, not chased. */
export const MAX_VALIDATION_DEPTH = 256;

/** The member a record admitting unknowns carries them in. */
export const PRESERVED_MEMBER = "__unknown";

/** One failure: where, which rule, and what it says. */
export interface ValidationError {
	readonly pointer: string;
	readonly code: string;
	readonly message: string;
}

/**
 * The verdict.
 *
 * `surfaced` carries the findings a record declaring `unknownPolicy: "surface"`
 * reports without rejecting the value, which is why they sit on the accepting
 * arm: they are distinguishable from a rejection by their code and by leaving
 * `ok` true.
 */
export type ValidationResult<T> =
	| {
			readonly ok: true;
			readonly value: T;
			readonly surfaced: readonly ValidationError[];
	  }
	| { readonly ok: false; readonly errors: readonly ValidationError[] };

/** How a member of an untrusted object presented itself. */
export type MemberState = "value" | "absent" | "accessor";

/** A member read without invoking anything. */
export interface Member {
	readonly state: MemberState;
	readonly value: unknown;
}

/**
 * Read one member as an own property, without invoking an accessor.
 *
 * A getter that throws cannot make a validator throw, and a getter returning a
 * different value on each read cannot make the check disagree with the value
 * returned, because neither is ever called. An inherited member is absent: a
 * prototype-chain member does not satisfy a declared field.
 */
export function ownMember(value: object, key: string): Member {
	const descriptor = Object.getOwnPropertyDescriptor(value, key);
	if (descriptor === undefined) return { state: "absent", value: undefined };
	if (!("value" in descriptor)) return { state: "accessor", value: undefined };
	return { state: "value", value: descriptor.value };
}

/**
 * Copy one member's *descriptor* onto an accumulator without reading it.
 *
 * An accessor member is carried through the prepare pass this way rather than
 * dropped, so the check that follows can report it instead of mistaking it for
 * an absent property — and so a getter that throws is still never invoked.
 */
export function copyAccessor(
	out: Record<string, unknown>,
	source: object,
	key: string,
): void {
	const descriptor = Object.getOwnPropertyDescriptor(source, key);
	if (descriptor !== undefined) Object.defineProperty(out, key, descriptor);
}

/** The own enumerable string keys of a value, in insertion order. */
export function ownKeys(value: object): readonly string[] {
	return Object.keys(value);
}

/** True for an object that is not an array and not null, whatever its prototype. */
export function isPlainObject(value: unknown): value is object {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** An RFC 6901 pointer, extended by one already-escaped reference token. */
export function join(pointer: string, token: string): string {
	return `${pointer}/${token.replaceAll("~", "~0").replaceAll("/", "~1")}`;
}

/** Record one failure. */
export function fail(
	into: ValidationError[],
	pointer: string,
	code: string,
	message: string,
): void {
	into.push({ pointer, code, message });
}

/** Unicode code points, so an astral character counts once. */
export function codePointLength(value: string): number {
	let count = 0;
	for (const _character of value) count += 1;
	return count;
}

/**
 * Well-formed standard base64, RFC 4648 §4.
 *
 * A declared decision of this backend pending
 * agent-ix/filament-core-data#58, which records that the published contract
 * states no wire form for the `bytes` kernel scalar.
 */
export function isBase64(value: string): boolean {
	if (value.length % 4 !== 0) return false;
	return /^[A-Za-z0-9+/]*={0,2}$/.test(value) && !/=[^=]/.test(value);
}

/** The octets a well-formed base64 string decodes to. */
export function base64OctetLength(value: string): number {
	if (!isBase64(value)) return -1;
	const padding = value.endsWith("==") ? 2 : value.endsWith("=") ? 1 : 0;
	return (value.length / 4) * 3 - padding;
}

/**
 * The canonical byte form of a value, used to decide collection uniqueness.
 *
 * Object keys are ordered by code unit, `undefined` members are dropped, and
 * negative zero renders as `0`, so two members that differ only in key order or
 * in the sign of a zero are one member.
 */
function canonicalJson(value: unknown): string {
	if (value === null) return "null";
	if (typeof value === "boolean") return value ? "true" : "false";
	if (typeof value === "number") {
		if (!Number.isFinite(value)) return "null";
		return JSON.stringify(Object.is(value, -0) ? 0 : value);
	}
	if (typeof value === "string") return JSON.stringify(value);
	if (Array.isArray(value)) {
		return `[${value.map((member) => canonicalJson(member)).join(",")}]`;
	}
	if (typeof value === "object") {
		const members: string[] = [];
		for (const key of Object.keys(value).sort()) {
			const member = ownMember(value, key);
			if (member.state !== "value" || member.value === undefined) continue;
			members.push(`${JSON.stringify(key)}:${canonicalJson(member.value)}`);
		}
		return `{${members.join(",")}}`;
	}
	return "null";
}

/** True when no two members of a collection share a canonical form. */
export function isUniqueCollection(value: unknown): boolean {
	if (!Array.isArray(value)) return true;
	const seen = new Set<string>();
	for (const member of value) {
		const form = canonicalJson(member);
		if (seen.has(form)) return false;
		seen.add(form);
	}
	return true;
}

/** Order by pointer then code, by code unit, so the list is host-stable. */
export function sortErrors(
	errors: readonly ValidationError[],
): readonly ValidationError[] {
	return [...errors].sort((left, right) => {
		if (left.pointer !== right.pointer) {
			return left.pointer < right.pointer ? -1 : 1;
		}
		if (left.code !== right.code) return left.code < right.code ? -1 : 1;
		return 0;
	});
}
