/**
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * Generated by the Agent IX TypeScript semantic backend. Do not edit.
 * backend: ix://agent-ix/filament-core-data/backend/typescript@0.1.0
 * contract: 1.1.0
 * package: agent-ix/semantic-kernel@0.1.0
 * fingerprint: sha256:625aaebb0ff08305a9819ab8640471833f406081d0a2720fe506ebec5decc556
 */

/**
 * The semantic identity of everything this package renders, and the contract
 * data a TypeScript type cannot carry: roles, unknown policies, units,
 * relationship descriptors, and extensions at type and field level.
 *
 * Identities are copied from the semantic document verbatim. They are never
 * minted, shortened or re-cased here: an identity that moves when a display
 * name changes is exactly the defect `conformance/defects.json` records as
 * DEF-PROTO-008, and the generated identifier moving while the identity does not
 * is what makes such a rename visible.
 *
 * This module imports nothing, so a consumer reading identity data reaches no
 * validator.
 */

/** One extension the document declares, at any of its three levels. */
export interface ExtensionDescriptor {
	readonly identity: string;
	readonly version: string;
	readonly required: boolean;
	readonly capability?: string;
	readonly payload: unknown;
}

/** One relationship a record declares. Rendered here and nowhere else. */
export interface RelationshipDescriptor {
	readonly identity: string;
	readonly verb: string;
	readonly category: string;
	readonly composite: boolean;
	readonly target: string;
	readonly lower: number;
	/** `null` where the document declares no upper bound. */
	readonly upper: number | null;
}

/** One operation parameter, or an operation's return. */
export interface FieldDescriptor {
	readonly identity: string;
	readonly name: string;
	readonly typeRef: string;
	readonly optional: boolean;
	readonly nullable: boolean;
	readonly collection: boolean;
	readonly lower: number;
	readonly upper: number | null;
}

/**
 * One operation a record declares, as data.
 *
 * No executable function is generated for it: the generated surface is data,
 * and an operation is contract data a consumer may dispatch on.
 */
export interface OperationDescriptor {
	readonly identity: string;
	readonly name: string;
	readonly params: readonly FieldDescriptor[];
	readonly returns: {
		readonly typeRef: string;
		readonly nullable: boolean;
		readonly lower: number;
		readonly upper: number | null;
	} | null;
	readonly pre: readonly string[];
	readonly post: readonly string[];
}

/**
 * One clause a type declares, with its text carried opaquely.
 *
 * The text is not parsed. `agent-ix/quire-contract-ir#52` owns clause
 * semantics, and the IR carries the text without parsing it.
 */
export interface ClauseDescriptor {
	readonly identity: string;
	readonly language: string;
	readonly clauseId: string;
	readonly text: string;
	readonly sourceSpan: {
		readonly path: string;
		readonly startLine: number;
		readonly startColumn: number;
	} | null;
}

/** One enum or union member, including its semantic identity. */
export interface VariantDescriptor {
	readonly identity: string;
	readonly name: string;
	readonly payloadType: string;
}

/** One constraint's semantic identity and operands. */
export interface ConstraintDescriptor {
	readonly identity: string;
	readonly keyword: string;
	readonly appliesTo: string;
	readonly diagnosticCode: string;
	readonly operands: unknown;
}

/**
 * One field's declared default.
 *
 * The kind is carried for every field. The value is carried wherever the kind
 * is not `none`, including for a `representation` or a `migration` default that
 * the generated validator deliberately does not apply.
 */
export interface DefaultDescriptor {
	readonly kind: string;
	readonly value: unknown;
}

/** One observed value the document carries. */
export interface OccurrenceDescriptor {
	readonly identity: string;
	readonly definition: string;
	/** Copied verbatim from the document; not a clock this backend read. */
	readonly observedAt: string;
	readonly value: unknown;
}

/** Every type name this package exports. */
export type ExportedTypeName =
	| "ClauseLanguage"
	| "ClauseRef"
	| "ConstraintDecl"
	| "ConstraintKeyword"
	| "DecimalPolicy"
	| "DecimalPolicyPrecision"
	| "DecimalPolicyScale"
	| "DefaultDecl"
	| "DefaultDeclValue"
	| "DefaultKind"
	| "EdgeCategory"
	| "EnumValue"
	| "EnumValueDoc"
	| "EnumValuesConstraint"
	| "EnumValuesConstraintKeyword"
	| "EnumValuesConstraintValues"
	| "ExclusiveMaxConstraint"
	| "ExclusiveMaxConstraintKeyword"
	| "ExclusiveMaxConstraintValue"
	| "ExclusiveMinConstraint"
	| "ExclusiveMinConstraintKeyword"
	| "ExclusiveMinConstraintValue"
	| "FieldDecl"
	| "FieldDeclDoc"
	| "FieldDeclIdentity"
	| "FieldDeclNullable"
	| "FormatConstraint"
	| "FormatConstraintKeyword"
	| "FormatConstraintName"
	| "Identifier"
	| "KernelScalar"
	| "MaxConstraint"
	| "MaxConstraintKeyword"
	| "MaxConstraintValue"
	| "MaxLengthConstraint"
	| "MaxLengthConstraintKeyword"
	| "MaxLengthConstraintValue"
	| "MinConstraint"
	| "MinConstraintKeyword"
	| "MinConstraintValue"
	| "MinLengthConstraint"
	| "MinLengthConstraintKeyword"
	| "MinLengthConstraintValue"
	| "Multiplicity"
	| "MultiplicityLower"
	| "MultiplicityOrdered"
	| "MultiplicityUnique"
	| "MultiplicityUpper"
	| "NonEmptyConstraint"
	| "NonEmptyConstraintKeyword"
	| "OperationDecl"
	| "PatternConstraint"
	| "PatternConstraintDialect"
	| "PatternConstraintKeyword"
	| "PatternConstraintRegex"
	| "RelationDecl"
	| "RelationDeclComposite"
	| "SemanticId"
	| "SourceLocus"
	| "SourceLocusEndColumn"
	| "SourceLocusEndLine"
	| "SourceLocusPath"
	| "SourceLocusStartColumn"
	| "SourceLocusStartLine"
	| "TypeRef"
	| "TypeRefTarget"
	| "UniqueConstraint"
	| "UniqueConstraintKeyword"
	| "UnitSymbol";

/** Every `<Type>.<field>` key this package exports a field identity for. */
export type ExportedFieldKey =
	| "ClauseRef.clauseId"
	| "ClauseRef.language"
	| "ClauseRef.sourceSpan"
	| "DecimalPolicy.precision"
	| "DecimalPolicy.scale"
	| "DefaultDecl.kind"
	| "DefaultDecl.value"
	| "EnumValue.doc"
	| "EnumValue.value"
	| "EnumValuesConstraint.keyword"
	| "EnumValuesConstraint.values"
	| "ExclusiveMaxConstraint.keyword"
	| "ExclusiveMaxConstraint.value"
	| "ExclusiveMinConstraint.keyword"
	| "ExclusiveMinConstraint.value"
	| "FieldDecl.constraints"
	| "FieldDecl.default"
	| "FieldDecl.doc"
	| "FieldDecl.identity"
	| "FieldDecl.name"
	| "FieldDecl.nullable"
	| "FieldDecl.type"
	| "FormatConstraint.keyword"
	| "FormatConstraint.name"
	| "MaxConstraint.keyword"
	| "MaxConstraint.value"
	| "MaxLengthConstraint.keyword"
	| "MaxLengthConstraint.value"
	| "MinConstraint.keyword"
	| "MinConstraint.value"
	| "MinLengthConstraint.keyword"
	| "MinLengthConstraint.value"
	| "Multiplicity.lower"
	| "Multiplicity.ordered"
	| "Multiplicity.unique"
	| "Multiplicity.upper"
	| "NonEmptyConstraint.keyword"
	| "OperationDecl.name"
	| "OperationDecl.params"
	| "OperationDecl.post"
	| "OperationDecl.pre"
	| "OperationDecl.returns"
	| "PatternConstraint.dialect"
	| "PatternConstraint.keyword"
	| "PatternConstraint.regex"
	| "RelationDecl.category"
	| "RelationDecl.composite"
	| "RelationDecl.multiplicity"
	| "RelationDecl.target"
	| "RelationDecl.verb"
	| "SourceLocus.endColumn"
	| "SourceLocus.endLine"
	| "SourceLocus.path"
	| "SourceLocus.sourceIdentity"
	| "SourceLocus.startColumn"
	| "SourceLocus.startLine"
	| "TypeRef.decimal"
	| "TypeRef.multiplicity"
	| "TypeRef.target"
	| "TypeRef.unit"
	| "UniqueConstraint.keyword";

/** The semantic identity of each exported type. */
export const TYPE_IDENTITY = {
	ClauseLanguage: "ix://agent-ix/semantic-core/type/ClauseLanguage",
	ClauseRef: "ix://agent-ix/semantic-core/type/ClauseRef",
	ConstraintDecl: "ix://agent-ix/semantic-core/type/ConstraintDecl",
	ConstraintKeyword: "ix://agent-ix/semantic-core/type/ConstraintKeyword",
	DecimalPolicy: "ix://agent-ix/semantic-core/type/DecimalPolicy",
	DecimalPolicyPrecision:
		"ix://agent-ix/semantic-core/type/DecimalPolicyPrecision",
	DecimalPolicyScale: "ix://agent-ix/semantic-core/type/DecimalPolicyScale",
	DefaultDecl: "ix://agent-ix/semantic-core/type/DefaultDecl",
	DefaultDeclValue: "ix://agent-ix/semantic-core/type/DefaultDeclValue",
	DefaultKind: "ix://agent-ix/semantic-core/type/DefaultKind",
	EdgeCategory: "ix://agent-ix/semantic-core/type/EdgeCategory",
	EnumValue: "ix://agent-ix/semantic-core/type/EnumValue",
	EnumValueDoc: "ix://agent-ix/semantic-core/type/EnumValueDoc",
	EnumValuesConstraint: "ix://agent-ix/semantic-core/type/EnumValuesConstraint",
	EnumValuesConstraintKeyword:
		"ix://agent-ix/semantic-core/type/EnumValuesConstraintKeyword",
	EnumValuesConstraintValues:
		"ix://agent-ix/semantic-core/type/EnumValuesConstraintValues",
	ExclusiveMaxConstraint:
		"ix://agent-ix/semantic-core/type/ExclusiveMaxConstraint",
	ExclusiveMaxConstraintKeyword:
		"ix://agent-ix/semantic-core/type/ExclusiveMaxConstraintKeyword",
	ExclusiveMaxConstraintValue:
		"ix://agent-ix/semantic-core/type/ExclusiveMaxConstraintValue",
	ExclusiveMinConstraint:
		"ix://agent-ix/semantic-core/type/ExclusiveMinConstraint",
	ExclusiveMinConstraintKeyword:
		"ix://agent-ix/semantic-core/type/ExclusiveMinConstraintKeyword",
	ExclusiveMinConstraintValue:
		"ix://agent-ix/semantic-core/type/ExclusiveMinConstraintValue",
	FieldDecl: "ix://agent-ix/semantic-core/type/FieldDecl",
	FieldDeclDoc: "ix://agent-ix/semantic-core/type/FieldDeclDoc",
	FieldDeclIdentity: "ix://agent-ix/semantic-core/type/FieldDeclIdentity",
	FieldDeclNullable: "ix://agent-ix/semantic-core/type/FieldDeclNullable",
	FormatConstraint: "ix://agent-ix/semantic-core/type/FormatConstraint",
	FormatConstraintKeyword:
		"ix://agent-ix/semantic-core/type/FormatConstraintKeyword",
	FormatConstraintName: "ix://agent-ix/semantic-core/type/FormatConstraintName",
	Identifier: "ix://agent-ix/semantic-core/type/Identifier",
	KernelScalar: "ix://agent-ix/semantic-core/type/KernelScalar",
	MaxConstraint: "ix://agent-ix/semantic-core/type/MaxConstraint",
	MaxConstraintKeyword: "ix://agent-ix/semantic-core/type/MaxConstraintKeyword",
	MaxConstraintValue: "ix://agent-ix/semantic-core/type/MaxConstraintValue",
	MaxLengthConstraint: "ix://agent-ix/semantic-core/type/MaxLengthConstraint",
	MaxLengthConstraintKeyword:
		"ix://agent-ix/semantic-core/type/MaxLengthConstraintKeyword",
	MaxLengthConstraintValue:
		"ix://agent-ix/semantic-core/type/MaxLengthConstraintValue",
	MinConstraint: "ix://agent-ix/semantic-core/type/MinConstraint",
	MinConstraintKeyword: "ix://agent-ix/semantic-core/type/MinConstraintKeyword",
	MinConstraintValue: "ix://agent-ix/semantic-core/type/MinConstraintValue",
	MinLengthConstraint: "ix://agent-ix/semantic-core/type/MinLengthConstraint",
	MinLengthConstraintKeyword:
		"ix://agent-ix/semantic-core/type/MinLengthConstraintKeyword",
	MinLengthConstraintValue:
		"ix://agent-ix/semantic-core/type/MinLengthConstraintValue",
	Multiplicity: "ix://agent-ix/semantic-core/type/Multiplicity",
	MultiplicityLower: "ix://agent-ix/semantic-core/type/MultiplicityLower",
	MultiplicityOrdered: "ix://agent-ix/semantic-core/type/MultiplicityOrdered",
	MultiplicityUnique: "ix://agent-ix/semantic-core/type/MultiplicityUnique",
	MultiplicityUpper: "ix://agent-ix/semantic-core/type/MultiplicityUpper",
	NonEmptyConstraint: "ix://agent-ix/semantic-core/type/NonEmptyConstraint",
	NonEmptyConstraintKeyword:
		"ix://agent-ix/semantic-core/type/NonEmptyConstraintKeyword",
	OperationDecl: "ix://agent-ix/semantic-core/type/OperationDecl",
	PatternConstraint: "ix://agent-ix/semantic-core/type/PatternConstraint",
	PatternConstraintDialect:
		"ix://agent-ix/semantic-core/type/PatternConstraintDialect",
	PatternConstraintKeyword:
		"ix://agent-ix/semantic-core/type/PatternConstraintKeyword",
	PatternConstraintRegex:
		"ix://agent-ix/semantic-core/type/PatternConstraintRegex",
	RelationDecl: "ix://agent-ix/semantic-core/type/RelationDecl",
	RelationDeclComposite:
		"ix://agent-ix/semantic-core/type/RelationDeclComposite",
	SemanticId: "ix://agent-ix/semantic-core/type/SemanticId",
	SourceLocus: "ix://agent-ix/semantic-core/type/SourceLocus",
	SourceLocusEndColumn: "ix://agent-ix/semantic-core/type/SourceLocusEndColumn",
	SourceLocusEndLine: "ix://agent-ix/semantic-core/type/SourceLocusEndLine",
	SourceLocusPath: "ix://agent-ix/semantic-core/type/SourceLocusPath",
	SourceLocusStartColumn:
		"ix://agent-ix/semantic-core/type/SourceLocusStartColumn",
	SourceLocusStartLine: "ix://agent-ix/semantic-core/type/SourceLocusStartLine",
	TypeRef: "ix://agent-ix/semantic-core/type/TypeRef",
	TypeRefTarget: "ix://agent-ix/semantic-core/type/TypeRefTarget",
	UniqueConstraint: "ix://agent-ix/semantic-core/type/UniqueConstraint",
	UniqueConstraintKeyword:
		"ix://agent-ix/semantic-core/type/UniqueConstraintKeyword",
	UnitSymbol: "ix://agent-ix/semantic-core/type/UnitSymbol",
} as const satisfies Record<ExportedTypeName, string>;

/** The structural kind each exported type was lowered from. */
export const TYPE_KIND = {
	ClauseLanguage: "scalar",
	ClauseRef: "record",
	ConstraintDecl: "union",
	ConstraintKeyword: "enum",
	DecimalPolicy: "record",
	DecimalPolicyPrecision: "scalar",
	DecimalPolicyScale: "scalar",
	DefaultDecl: "record",
	DefaultDeclValue: "record",
	DefaultKind: "enum",
	EdgeCategory: "enum",
	EnumValue: "record",
	EnumValueDoc: "scalar",
	EnumValuesConstraint: "record",
	EnumValuesConstraintKeyword: "enum",
	EnumValuesConstraintValues: "union",
	ExclusiveMaxConstraint: "record",
	ExclusiveMaxConstraintKeyword: "enum",
	ExclusiveMaxConstraintValue: "union",
	ExclusiveMinConstraint: "record",
	ExclusiveMinConstraintKeyword: "enum",
	ExclusiveMinConstraintValue: "union",
	FieldDecl: "record",
	FieldDeclDoc: "scalar",
	FieldDeclIdentity: "scalar",
	FieldDeclNullable: "scalar",
	FormatConstraint: "record",
	FormatConstraintKeyword: "enum",
	FormatConstraintName: "scalar",
	Identifier: "scalar",
	KernelScalar: "enum",
	MaxConstraint: "record",
	MaxConstraintKeyword: "enum",
	MaxConstraintValue: "union",
	MaxLengthConstraint: "record",
	MaxLengthConstraintKeyword: "enum",
	MaxLengthConstraintValue: "scalar",
	MinConstraint: "record",
	MinConstraintKeyword: "enum",
	MinConstraintValue: "union",
	MinLengthConstraint: "record",
	MinLengthConstraintKeyword: "enum",
	MinLengthConstraintValue: "scalar",
	Multiplicity: "record",
	MultiplicityLower: "scalar",
	MultiplicityOrdered: "scalar",
	MultiplicityUnique: "scalar",
	MultiplicityUpper: "scalar",
	NonEmptyConstraint: "record",
	NonEmptyConstraintKeyword: "enum",
	OperationDecl: "record",
	PatternConstraint: "record",
	PatternConstraintDialect: "enum",
	PatternConstraintKeyword: "enum",
	PatternConstraintRegex: "scalar",
	RelationDecl: "record",
	RelationDeclComposite: "scalar",
	SemanticId: "scalar",
	SourceLocus: "record",
	SourceLocusEndColumn: "scalar",
	SourceLocusEndLine: "scalar",
	SourceLocusPath: "scalar",
	SourceLocusStartColumn: "scalar",
	SourceLocusStartLine: "scalar",
	TypeRef: "record",
	TypeRefTarget: "union",
	UniqueConstraint: "record",
	UniqueConstraintKeyword: "enum",
	UnitSymbol: "scalar",
} as const satisfies Record<ExportedTypeName, string>;

/** The namespaced roles each exported type declares, in document order. */
export const TYPE_ROLES = {
	ClauseLanguage: [],
	ClauseRef: [],
	ConstraintDecl: [],
	ConstraintKeyword: [],
	DecimalPolicy: [],
	DecimalPolicyPrecision: [],
	DecimalPolicyScale: [],
	DefaultDecl: [],
	DefaultDeclValue: [],
	DefaultKind: [],
	EdgeCategory: [],
	EnumValue: [],
	EnumValueDoc: [],
	EnumValuesConstraint: [],
	EnumValuesConstraintKeyword: [],
	EnumValuesConstraintValues: [],
	ExclusiveMaxConstraint: [],
	ExclusiveMaxConstraintKeyword: [],
	ExclusiveMaxConstraintValue: [],
	ExclusiveMinConstraint: [],
	ExclusiveMinConstraintKeyword: [],
	ExclusiveMinConstraintValue: [],
	FieldDecl: [],
	FieldDeclDoc: [],
	FieldDeclIdentity: [],
	FieldDeclNullable: [],
	FormatConstraint: [],
	FormatConstraintKeyword: [],
	FormatConstraintName: [],
	Identifier: [],
	KernelScalar: [],
	MaxConstraint: [],
	MaxConstraintKeyword: [],
	MaxConstraintValue: [],
	MaxLengthConstraint: [],
	MaxLengthConstraintKeyword: [],
	MaxLengthConstraintValue: [],
	MinConstraint: [],
	MinConstraintKeyword: [],
	MinConstraintValue: [],
	MinLengthConstraint: [],
	MinLengthConstraintKeyword: [],
	MinLengthConstraintValue: [],
	Multiplicity: [],
	MultiplicityLower: [],
	MultiplicityOrdered: [],
	MultiplicityUnique: [],
	MultiplicityUpper: [],
	NonEmptyConstraint: [],
	NonEmptyConstraintKeyword: [],
	OperationDecl: [],
	PatternConstraint: [],
	PatternConstraintDialect: [],
	PatternConstraintKeyword: [],
	PatternConstraintRegex: [],
	RelationDecl: [],
	RelationDeclComposite: [],
	SemanticId: [],
	SourceLocus: [],
	SourceLocusEndColumn: [],
	SourceLocusEndLine: [],
	SourceLocusPath: [],
	SourceLocusStartColumn: [],
	SourceLocusStartLine: [],
	TypeRef: [],
	TypeRefTarget: [],
	UniqueConstraint: [],
	UniqueConstraintKeyword: [],
	UnitSymbol: [],
} as const satisfies Record<ExportedTypeName, readonly string[]>;

/**
 * The unknown-member policy each exported type declares.
 *
 * It is carried for all eight kinds, including the seven on which it has no
 * validation effect, because it is contract data the document states and this
 * package declares nothing dropped.
 */
export const TYPE_UNKNOWN_POLICY = {
	ClauseLanguage: "reject",
	ClauseRef: "reject",
	ConstraintDecl: "reject",
	ConstraintKeyword: "reject",
	DecimalPolicy: "reject",
	DecimalPolicyPrecision: "reject",
	DecimalPolicyScale: "reject",
	DefaultDecl: "reject",
	DefaultDeclValue: "preserve",
	DefaultKind: "reject",
	EdgeCategory: "reject",
	EnumValue: "reject",
	EnumValueDoc: "reject",
	EnumValuesConstraint: "reject",
	EnumValuesConstraintKeyword: "reject",
	EnumValuesConstraintValues: "reject",
	ExclusiveMaxConstraint: "reject",
	ExclusiveMaxConstraintKeyword: "reject",
	ExclusiveMaxConstraintValue: "reject",
	ExclusiveMinConstraint: "reject",
	ExclusiveMinConstraintKeyword: "reject",
	ExclusiveMinConstraintValue: "reject",
	FieldDecl: "reject",
	FieldDeclDoc: "reject",
	FieldDeclIdentity: "reject",
	FieldDeclNullable: "reject",
	FormatConstraint: "reject",
	FormatConstraintKeyword: "reject",
	FormatConstraintName: "reject",
	Identifier: "reject",
	KernelScalar: "reject",
	MaxConstraint: "reject",
	MaxConstraintKeyword: "reject",
	MaxConstraintValue: "reject",
	MaxLengthConstraint: "reject",
	MaxLengthConstraintKeyword: "reject",
	MaxLengthConstraintValue: "reject",
	MinConstraint: "reject",
	MinConstraintKeyword: "reject",
	MinConstraintValue: "reject",
	MinLengthConstraint: "reject",
	MinLengthConstraintKeyword: "reject",
	MinLengthConstraintValue: "reject",
	Multiplicity: "reject",
	MultiplicityLower: "reject",
	MultiplicityOrdered: "reject",
	MultiplicityUnique: "reject",
	MultiplicityUpper: "reject",
	NonEmptyConstraint: "reject",
	NonEmptyConstraintKeyword: "reject",
	OperationDecl: "reject",
	PatternConstraint: "reject",
	PatternConstraintDialect: "reject",
	PatternConstraintKeyword: "reject",
	PatternConstraintRegex: "reject",
	RelationDecl: "reject",
	RelationDeclComposite: "reject",
	SemanticId: "reject",
	SourceLocus: "reject",
	SourceLocusEndColumn: "reject",
	SourceLocusEndLine: "reject",
	SourceLocusPath: "reject",
	SourceLocusStartColumn: "reject",
	SourceLocusStartLine: "reject",
	TypeRef: "reject",
	TypeRefTarget: "reject",
	UniqueConstraint: "reject",
	UniqueConstraintKeyword: "reject",
	UnitSymbol: "reject",
} as const satisfies Record<ExportedTypeName, string>;

/** The extensions each exported type declares. */
export const TYPE_EXTENSIONS = {
	ClauseLanguage: [],
	ClauseRef: [],
	ConstraintDecl: [],
	ConstraintKeyword: [],
	DecimalPolicy: [],
	DecimalPolicyPrecision: [],
	DecimalPolicyScale: [],
	DefaultDecl: [],
	DefaultDeclValue: [],
	DefaultKind: [],
	EdgeCategory: [],
	EnumValue: [],
	EnumValueDoc: [],
	EnumValuesConstraint: [],
	EnumValuesConstraintKeyword: [],
	EnumValuesConstraintValues: [],
	ExclusiveMaxConstraint: [],
	ExclusiveMaxConstraintKeyword: [],
	ExclusiveMaxConstraintValue: [],
	ExclusiveMinConstraint: [],
	ExclusiveMinConstraintKeyword: [],
	ExclusiveMinConstraintValue: [],
	FieldDecl: [],
	FieldDeclDoc: [],
	FieldDeclIdentity: [],
	FieldDeclNullable: [],
	FormatConstraint: [],
	FormatConstraintKeyword: [],
	FormatConstraintName: [],
	Identifier: [],
	KernelScalar: [],
	MaxConstraint: [],
	MaxConstraintKeyword: [],
	MaxConstraintValue: [],
	MaxLengthConstraint: [],
	MaxLengthConstraintKeyword: [],
	MaxLengthConstraintValue: [],
	MinConstraint: [],
	MinConstraintKeyword: [],
	MinConstraintValue: [],
	MinLengthConstraint: [],
	MinLengthConstraintKeyword: [],
	MinLengthConstraintValue: [],
	Multiplicity: [],
	MultiplicityLower: [],
	MultiplicityOrdered: [],
	MultiplicityUnique: [],
	MultiplicityUpper: [],
	NonEmptyConstraint: [],
	NonEmptyConstraintKeyword: [],
	OperationDecl: [],
	PatternConstraint: [],
	PatternConstraintDialect: [],
	PatternConstraintKeyword: [],
	PatternConstraintRegex: [],
	RelationDecl: [],
	RelationDeclComposite: [],
	SemanticId: [],
	SourceLocus: [],
	SourceLocusEndColumn: [],
	SourceLocusEndLine: [],
	SourceLocusPath: [],
	SourceLocusStartColumn: [],
	SourceLocusStartLine: [],
	TypeRef: [],
	TypeRefTarget: [],
	UniqueConstraint: [],
	UniqueConstraintKeyword: [],
	UnitSymbol: [],
} as const satisfies Record<ExportedTypeName, readonly ExtensionDescriptor[]>;

/** The relationships each exported type declares; empty where it declares none. */
export const TYPE_RELATIONSHIPS = {
	ClauseLanguage: [],
	ClauseRef: [],
	ConstraintDecl: [],
	ConstraintKeyword: [],
	DecimalPolicy: [],
	DecimalPolicyPrecision: [],
	DecimalPolicyScale: [],
	DefaultDecl: [],
	DefaultDeclValue: [],
	DefaultKind: [],
	EdgeCategory: [],
	EnumValue: [],
	EnumValueDoc: [],
	EnumValuesConstraint: [],
	EnumValuesConstraintKeyword: [],
	EnumValuesConstraintValues: [],
	ExclusiveMaxConstraint: [],
	ExclusiveMaxConstraintKeyword: [],
	ExclusiveMaxConstraintValue: [],
	ExclusiveMinConstraint: [],
	ExclusiveMinConstraintKeyword: [],
	ExclusiveMinConstraintValue: [],
	FieldDecl: [],
	FieldDeclDoc: [],
	FieldDeclIdentity: [],
	FieldDeclNullable: [],
	FormatConstraint: [],
	FormatConstraintKeyword: [],
	FormatConstraintName: [],
	Identifier: [],
	KernelScalar: [],
	MaxConstraint: [],
	MaxConstraintKeyword: [],
	MaxConstraintValue: [],
	MaxLengthConstraint: [],
	MaxLengthConstraintKeyword: [],
	MaxLengthConstraintValue: [],
	MinConstraint: [],
	MinConstraintKeyword: [],
	MinConstraintValue: [],
	MinLengthConstraint: [],
	MinLengthConstraintKeyword: [],
	MinLengthConstraintValue: [],
	Multiplicity: [],
	MultiplicityLower: [],
	MultiplicityOrdered: [],
	MultiplicityUnique: [],
	MultiplicityUpper: [],
	NonEmptyConstraint: [],
	NonEmptyConstraintKeyword: [],
	OperationDecl: [],
	PatternConstraint: [],
	PatternConstraintDialect: [],
	PatternConstraintKeyword: [],
	PatternConstraintRegex: [],
	RelationDecl: [],
	RelationDeclComposite: [],
	SemanticId: [],
	SourceLocus: [],
	SourceLocusEndColumn: [],
	SourceLocusEndLine: [],
	SourceLocusPath: [],
	SourceLocusStartColumn: [],
	SourceLocusStartLine: [],
	TypeRef: [],
	TypeRefTarget: [],
	UniqueConstraint: [],
	UniqueConstraintKeyword: [],
	UnitSymbol: [],
} as const satisfies Record<
	ExportedTypeName,
	readonly RelationshipDescriptor[]
>;

/** The semantic identity of each exported field. */
export const FIELD_IDENTITY = {
	"ClauseRef.clauseId":
		"ix://agent-ix/semantic-core/type/ClauseRef/field/clauseId",
	"ClauseRef.language":
		"ix://agent-ix/semantic-core/type/ClauseRef/field/language",
	"ClauseRef.sourceSpan":
		"ix://agent-ix/semantic-core/type/ClauseRef/field/sourceSpan",
	"DecimalPolicy.precision":
		"ix://agent-ix/semantic-core/type/DecimalPolicy/field/precision",
	"DecimalPolicy.scale":
		"ix://agent-ix/semantic-core/type/DecimalPolicy/field/scale",
	"DefaultDecl.kind": "ix://agent-ix/semantic-core/type/DefaultDecl/field/kind",
	"DefaultDecl.value":
		"ix://agent-ix/semantic-core/type/DefaultDecl/field/value",
	"EnumValue.doc": "ix://agent-ix/semantic-core/type/EnumValue/field/doc",
	"EnumValue.value": "ix://agent-ix/semantic-core/type/EnumValue/field/value",
	"EnumValuesConstraint.keyword":
		"ix://agent-ix/semantic-core/type/EnumValuesConstraint/field/keyword",
	"EnumValuesConstraint.values":
		"ix://agent-ix/semantic-core/type/EnumValuesConstraint/field/values",
	"ExclusiveMaxConstraint.keyword":
		"ix://agent-ix/semantic-core/type/ExclusiveMaxConstraint/field/keyword",
	"ExclusiveMaxConstraint.value":
		"ix://agent-ix/semantic-core/type/ExclusiveMaxConstraint/field/value",
	"ExclusiveMinConstraint.keyword":
		"ix://agent-ix/semantic-core/type/ExclusiveMinConstraint/field/keyword",
	"ExclusiveMinConstraint.value":
		"ix://agent-ix/semantic-core/type/ExclusiveMinConstraint/field/value",
	"FieldDecl.constraints":
		"ix://agent-ix/semantic-core/type/FieldDecl/field/constraints",
	"FieldDecl.default":
		"ix://agent-ix/semantic-core/type/FieldDecl/field/default",
	"FieldDecl.doc": "ix://agent-ix/semantic-core/type/FieldDecl/field/doc",
	"FieldDecl.identity":
		"ix://agent-ix/semantic-core/type/FieldDecl/field/identity",
	"FieldDecl.name": "ix://agent-ix/semantic-core/type/FieldDecl/field/name",
	"FieldDecl.nullable":
		"ix://agent-ix/semantic-core/type/FieldDecl/field/nullable",
	"FieldDecl.type": "ix://agent-ix/semantic-core/type/FieldDecl/field/type",
	"FormatConstraint.keyword":
		"ix://agent-ix/semantic-core/type/FormatConstraint/field/keyword",
	"FormatConstraint.name":
		"ix://agent-ix/semantic-core/type/FormatConstraint/field/name",
	"MaxConstraint.keyword":
		"ix://agent-ix/semantic-core/type/MaxConstraint/field/keyword",
	"MaxConstraint.value":
		"ix://agent-ix/semantic-core/type/MaxConstraint/field/value",
	"MaxLengthConstraint.keyword":
		"ix://agent-ix/semantic-core/type/MaxLengthConstraint/field/keyword",
	"MaxLengthConstraint.value":
		"ix://agent-ix/semantic-core/type/MaxLengthConstraint/field/value",
	"MinConstraint.keyword":
		"ix://agent-ix/semantic-core/type/MinConstraint/field/keyword",
	"MinConstraint.value":
		"ix://agent-ix/semantic-core/type/MinConstraint/field/value",
	"MinLengthConstraint.keyword":
		"ix://agent-ix/semantic-core/type/MinLengthConstraint/field/keyword",
	"MinLengthConstraint.value":
		"ix://agent-ix/semantic-core/type/MinLengthConstraint/field/value",
	"Multiplicity.lower":
		"ix://agent-ix/semantic-core/type/Multiplicity/field/lower",
	"Multiplicity.ordered":
		"ix://agent-ix/semantic-core/type/Multiplicity/field/ordered",
	"Multiplicity.unique":
		"ix://agent-ix/semantic-core/type/Multiplicity/field/unique",
	"Multiplicity.upper":
		"ix://agent-ix/semantic-core/type/Multiplicity/field/upper",
	"NonEmptyConstraint.keyword":
		"ix://agent-ix/semantic-core/type/NonEmptyConstraint/field/keyword",
	"OperationDecl.name":
		"ix://agent-ix/semantic-core/type/OperationDecl/field/name",
	"OperationDecl.params":
		"ix://agent-ix/semantic-core/type/OperationDecl/field/params",
	"OperationDecl.post":
		"ix://agent-ix/semantic-core/type/OperationDecl/field/post",
	"OperationDecl.pre":
		"ix://agent-ix/semantic-core/type/OperationDecl/field/pre",
	"OperationDecl.returns":
		"ix://agent-ix/semantic-core/type/OperationDecl/field/returns",
	"PatternConstraint.dialect":
		"ix://agent-ix/semantic-core/type/PatternConstraint/field/dialect",
	"PatternConstraint.keyword":
		"ix://agent-ix/semantic-core/type/PatternConstraint/field/keyword",
	"PatternConstraint.regex":
		"ix://agent-ix/semantic-core/type/PatternConstraint/field/regex",
	"RelationDecl.category":
		"ix://agent-ix/semantic-core/type/RelationDecl/field/category",
	"RelationDecl.composite":
		"ix://agent-ix/semantic-core/type/RelationDecl/field/composite",
	"RelationDecl.multiplicity":
		"ix://agent-ix/semantic-core/type/RelationDecl/field/multiplicity",
	"RelationDecl.target":
		"ix://agent-ix/semantic-core/type/RelationDecl/field/target",
	"RelationDecl.verb":
		"ix://agent-ix/semantic-core/type/RelationDecl/field/verb",
	"SourceLocus.endColumn":
		"ix://agent-ix/semantic-core/type/SourceLocus/field/endColumn",
	"SourceLocus.endLine":
		"ix://agent-ix/semantic-core/type/SourceLocus/field/endLine",
	"SourceLocus.path": "ix://agent-ix/semantic-core/type/SourceLocus/field/path",
	"SourceLocus.sourceIdentity":
		"ix://agent-ix/semantic-core/type/SourceLocus/field/sourceIdentity",
	"SourceLocus.startColumn":
		"ix://agent-ix/semantic-core/type/SourceLocus/field/startColumn",
	"SourceLocus.startLine":
		"ix://agent-ix/semantic-core/type/SourceLocus/field/startLine",
	"TypeRef.decimal": "ix://agent-ix/semantic-core/type/TypeRef/field/decimal",
	"TypeRef.multiplicity":
		"ix://agent-ix/semantic-core/type/TypeRef/field/multiplicity",
	"TypeRef.target": "ix://agent-ix/semantic-core/type/TypeRef/field/target",
	"TypeRef.unit": "ix://agent-ix/semantic-core/type/TypeRef/field/unit",
	"UniqueConstraint.keyword":
		"ix://agent-ix/semantic-core/type/UniqueConstraint/field/keyword",
} as const satisfies Record<ExportedFieldKey, string>;

/** The extensions each exported field declares. */
export const FIELD_EXTENSIONS = {
	"ClauseRef.clauseId": [],
	"ClauseRef.language": [],
	"ClauseRef.sourceSpan": [],
	"DecimalPolicy.precision": [],
	"DecimalPolicy.scale": [],
	"DefaultDecl.kind": [],
	"DefaultDecl.value": [],
	"EnumValue.doc": [],
	"EnumValue.value": [],
	"EnumValuesConstraint.keyword": [],
	"EnumValuesConstraint.values": [],
	"ExclusiveMaxConstraint.keyword": [],
	"ExclusiveMaxConstraint.value": [],
	"ExclusiveMinConstraint.keyword": [],
	"ExclusiveMinConstraint.value": [],
	"FieldDecl.constraints": [],
	"FieldDecl.default": [],
	"FieldDecl.doc": [],
	"FieldDecl.identity": [],
	"FieldDecl.name": [],
	"FieldDecl.nullable": [],
	"FieldDecl.type": [],
	"FormatConstraint.keyword": [],
	"FormatConstraint.name": [],
	"MaxConstraint.keyword": [],
	"MaxConstraint.value": [],
	"MaxLengthConstraint.keyword": [],
	"MaxLengthConstraint.value": [],
	"MinConstraint.keyword": [],
	"MinConstraint.value": [],
	"MinLengthConstraint.keyword": [],
	"MinLengthConstraint.value": [],
	"Multiplicity.lower": [],
	"Multiplicity.ordered": [],
	"Multiplicity.unique": [],
	"Multiplicity.upper": [],
	"NonEmptyConstraint.keyword": [],
	"OperationDecl.name": [],
	"OperationDecl.params": [],
	"OperationDecl.post": [],
	"OperationDecl.pre": [],
	"OperationDecl.returns": [],
	"PatternConstraint.dialect": [],
	"PatternConstraint.keyword": [],
	"PatternConstraint.regex": [],
	"RelationDecl.category": [],
	"RelationDecl.composite": [],
	"RelationDecl.multiplicity": [],
	"RelationDecl.target": [],
	"RelationDecl.verb": [],
	"SourceLocus.endColumn": [],
	"SourceLocus.endLine": [],
	"SourceLocus.path": [],
	"SourceLocus.sourceIdentity": [],
	"SourceLocus.startColumn": [],
	"SourceLocus.startLine": [],
	"TypeRef.decimal": [],
	"TypeRef.multiplicity": [],
	"TypeRef.target": [],
	"TypeRef.unit": [],
	"UniqueConstraint.keyword": [],
} as const satisfies Record<ExportedFieldKey, readonly ExtensionDescriptor[]>;

/** The unit each declaring field carries. A field declaring none has no entry. */
export const FIELD_UNIT = {} as const satisfies Partial<
	Record<ExportedFieldKey, string>
>;

/** The extensions the document declares at its top level. */
export const DOCUMENT_EXTENSIONS =
	[] as const satisfies readonly ExtensionDescriptor[];

/** The occurrences the document carries; empty where it carries none. */
export const OCCURRENCES =
	[] as const satisfies readonly OccurrenceDescriptor[];

/**
 * The operations each type declares, as data.
 *
 * No executable function is generated for an operation. The generated surface
 * is data, and rendering an operation as a readonly descriptor is not the
 * degradation `contracts-v1.md` prohibits — that is a fall back to `any`, a
 * generic map, or an empty model, and this is none of those.
 */
export const TYPE_OPERATIONS = {
	ClauseLanguage: [],
	ClauseRef: [],
	ConstraintDecl: [],
	ConstraintKeyword: [],
	DecimalPolicy: [],
	DecimalPolicyPrecision: [],
	DecimalPolicyScale: [],
	DefaultDecl: [],
	DefaultDeclValue: [],
	DefaultKind: [],
	EdgeCategory: [],
	EnumValue: [],
	EnumValueDoc: [],
	EnumValuesConstraint: [],
	EnumValuesConstraintKeyword: [],
	EnumValuesConstraintValues: [],
	ExclusiveMaxConstraint: [],
	ExclusiveMaxConstraintKeyword: [],
	ExclusiveMaxConstraintValue: [],
	ExclusiveMinConstraint: [],
	ExclusiveMinConstraintKeyword: [],
	ExclusiveMinConstraintValue: [],
	FieldDecl: [],
	FieldDeclDoc: [],
	FieldDeclIdentity: [],
	FieldDeclNullable: [],
	FormatConstraint: [],
	FormatConstraintKeyword: [],
	FormatConstraintName: [],
	Identifier: [],
	KernelScalar: [],
	MaxConstraint: [],
	MaxConstraintKeyword: [],
	MaxConstraintValue: [],
	MaxLengthConstraint: [],
	MaxLengthConstraintKeyword: [],
	MaxLengthConstraintValue: [],
	MinConstraint: [],
	MinConstraintKeyword: [],
	MinConstraintValue: [],
	MinLengthConstraint: [],
	MinLengthConstraintKeyword: [],
	MinLengthConstraintValue: [],
	Multiplicity: [],
	MultiplicityLower: [],
	MultiplicityOrdered: [],
	MultiplicityUnique: [],
	MultiplicityUpper: [],
	NonEmptyConstraint: [],
	NonEmptyConstraintKeyword: [],
	OperationDecl: [],
	PatternConstraint: [],
	PatternConstraintDialect: [],
	PatternConstraintKeyword: [],
	PatternConstraintRegex: [],
	RelationDecl: [],
	RelationDeclComposite: [],
	SemanticId: [],
	SourceLocus: [],
	SourceLocusEndColumn: [],
	SourceLocusEndLine: [],
	SourceLocusPath: [],
	SourceLocusStartColumn: [],
	SourceLocusStartLine: [],
	TypeRef: [],
	TypeRefTarget: [],
	UniqueConstraint: [],
	UniqueConstraintKeyword: [],
	UnitSymbol: [],
} as const satisfies Record<ExportedTypeName, readonly OperationDescriptor[]>;

/**
 * The clauses each type declares, with their text carried opaquely.
 *
 * The text is never parsed here: `agent-ix/quire-contract-ir#52` owns clause
 * semantics and the IR itself carries the text without parsing it.
 */
export const TYPE_CLAUSES = {
	ClauseLanguage: [],
	ClauseRef: [],
	ConstraintDecl: [],
	ConstraintKeyword: [],
	DecimalPolicy: [],
	DecimalPolicyPrecision: [],
	DecimalPolicyScale: [],
	DefaultDecl: [],
	DefaultDeclValue: [],
	DefaultKind: [],
	EdgeCategory: [],
	EnumValue: [],
	EnumValueDoc: [],
	EnumValuesConstraint: [],
	EnumValuesConstraintKeyword: [],
	EnumValuesConstraintValues: [],
	ExclusiveMaxConstraint: [],
	ExclusiveMaxConstraintKeyword: [],
	ExclusiveMaxConstraintValue: [],
	ExclusiveMinConstraint: [],
	ExclusiveMinConstraintKeyword: [],
	ExclusiveMinConstraintValue: [],
	FieldDecl: [],
	FieldDeclDoc: [],
	FieldDeclIdentity: [],
	FieldDeclNullable: [],
	FormatConstraint: [],
	FormatConstraintKeyword: [],
	FormatConstraintName: [],
	Identifier: [],
	KernelScalar: [],
	MaxConstraint: [],
	MaxConstraintKeyword: [],
	MaxConstraintValue: [],
	MaxLengthConstraint: [],
	MaxLengthConstraintKeyword: [],
	MaxLengthConstraintValue: [],
	MinConstraint: [],
	MinConstraintKeyword: [],
	MinConstraintValue: [],
	MinLengthConstraint: [],
	MinLengthConstraintKeyword: [],
	MinLengthConstraintValue: [],
	Multiplicity: [],
	MultiplicityLower: [],
	MultiplicityOrdered: [],
	MultiplicityUnique: [],
	MultiplicityUpper: [],
	NonEmptyConstraint: [],
	NonEmptyConstraintKeyword: [],
	OperationDecl: [],
	PatternConstraint: [],
	PatternConstraintDialect: [],
	PatternConstraintKeyword: [],
	PatternConstraintRegex: [],
	RelationDecl: [],
	RelationDeclComposite: [],
	SemanticId: [],
	SourceLocus: [],
	SourceLocusEndColumn: [],
	SourceLocusEndLine: [],
	SourceLocusPath: [],
	SourceLocusStartColumn: [],
	SourceLocusStartLine: [],
	TypeRef: [],
	TypeRefTarget: [],
	UniqueConstraint: [],
	UniqueConstraintKeyword: [],
	UnitSymbol: [],
} as const satisfies Record<ExportedTypeName, readonly ClauseDescriptor[]>;

/** The enum and union members, including their semantic identities. */
export const TYPE_VARIANTS = {
	ClauseLanguage: [],
	ClauseRef: [],
	ConstraintDecl: [
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintDecl/variant/EnumValuesConstraint",
			name: "EnumValuesConstraint",
			payloadType: "ix://agent-ix/semantic-core/type/EnumValuesConstraint",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintDecl/variant/ExclusiveMaxConstraint",
			name: "ExclusiveMaxConstraint",
			payloadType: "ix://agent-ix/semantic-core/type/ExclusiveMaxConstraint",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintDecl/variant/ExclusiveMinConstraint",
			name: "ExclusiveMinConstraint",
			payloadType: "ix://agent-ix/semantic-core/type/ExclusiveMinConstraint",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintDecl/variant/FormatConstraint",
			name: "FormatConstraint",
			payloadType: "ix://agent-ix/semantic-core/type/FormatConstraint",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintDecl/variant/MaxConstraint",
			name: "MaxConstraint",
			payloadType: "ix://agent-ix/semantic-core/type/MaxConstraint",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintDecl/variant/MaxLengthConstraint",
			name: "MaxLengthConstraint",
			payloadType: "ix://agent-ix/semantic-core/type/MaxLengthConstraint",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintDecl/variant/MinConstraint",
			name: "MinConstraint",
			payloadType: "ix://agent-ix/semantic-core/type/MinConstraint",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintDecl/variant/MinLengthConstraint",
			name: "MinLengthConstraint",
			payloadType: "ix://agent-ix/semantic-core/type/MinLengthConstraint",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintDecl/variant/NonEmptyConstraint",
			name: "NonEmptyConstraint",
			payloadType: "ix://agent-ix/semantic-core/type/NonEmptyConstraint",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintDecl/variant/PatternConstraint",
			name: "PatternConstraint",
			payloadType: "ix://agent-ix/semantic-core/type/PatternConstraint",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintDecl/variant/UniqueConstraint",
			name: "UniqueConstraint",
			payloadType: "ix://agent-ix/semantic-core/type/UniqueConstraint",
		},
	],
	ConstraintKeyword: [
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintKeyword/variant/enumValues",
			name: "enumValues",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintKeyword/variant/exclusiveMax",
			name: "exclusiveMax",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintKeyword/variant/exclusiveMin",
			name: "exclusiveMin",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintKeyword/variant/format",
			name: "format",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintKeyword/variant/max",
			name: "max",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintKeyword/variant/maxLength",
			name: "maxLength",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintKeyword/variant/min",
			name: "min",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintKeyword/variant/minLength",
			name: "minLength",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintKeyword/variant/nonEmpty",
			name: "nonEmpty",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintKeyword/variant/pattern",
			name: "pattern",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ConstraintKeyword/variant/unique",
			name: "unique",
			payloadType: "",
		},
	],
	DecimalPolicy: [],
	DecimalPolicyPrecision: [],
	DecimalPolicyScale: [],
	DefaultDecl: [],
	DefaultDeclValue: [],
	DefaultKind: [
		{
			identity: "ix://agent-ix/semantic-core/type/DefaultKind/variant/migration",
			name: "migration",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/DefaultKind/variant/representation",
			name: "representation",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/DefaultKind/variant/semantic",
			name: "semantic",
			payloadType: "",
		},
	],
	EdgeCategory: [
		{
			identity: "ix://agent-ix/semantic-core/type/EdgeCategory/variant/behavioral",
			name: "behavioral",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/EdgeCategory/variant/dataflow",
			name: "dataflow",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/EdgeCategory/variant/dependency",
			name: "dependency",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/EdgeCategory/variant/governance",
			name: "governance",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/EdgeCategory/variant/realization",
			name: "realization",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/EdgeCategory/variant/structural",
			name: "structural",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/EdgeCategory/variant/traceability",
			name: "traceability",
			payloadType: "",
		},
	],
	EnumValue: [],
	EnumValueDoc: [],
	EnumValuesConstraint: [],
	EnumValuesConstraintKeyword: [
		{
			identity: "ix://agent-ix/semantic-core/type/EnumValuesConstraintKeyword/variant/enumValues",
			name: "enumValues",
			payloadType: "",
		},
	],
	EnumValuesConstraintValues: [
		{
			identity: "ix://agent-ix/semantic-core/type/EnumValuesConstraintValues/variant/boolean",
			name: "boolean",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/EnumValuesConstraintValues/variant/number",
			name: "number",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/EnumValuesConstraintValues/variant/string",
			name: "string",
			payloadType: "",
		},
	],
	ExclusiveMaxConstraint: [],
	ExclusiveMaxConstraintKeyword: [
		{
			identity: "ix://agent-ix/semantic-core/type/ExclusiveMaxConstraintKeyword/variant/exclusiveMax",
			name: "exclusiveMax",
			payloadType: "",
		},
	],
	ExclusiveMaxConstraintValue: [
		{
			identity: "ix://agent-ix/semantic-core/type/ExclusiveMaxConstraintValue/variant/number",
			name: "number",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ExclusiveMaxConstraintValue/variant/string",
			name: "string",
			payloadType: "",
		},
	],
	ExclusiveMinConstraint: [],
	ExclusiveMinConstraintKeyword: [
		{
			identity: "ix://agent-ix/semantic-core/type/ExclusiveMinConstraintKeyword/variant/exclusiveMin",
			name: "exclusiveMin",
			payloadType: "",
		},
	],
	ExclusiveMinConstraintValue: [
		{
			identity: "ix://agent-ix/semantic-core/type/ExclusiveMinConstraintValue/variant/number",
			name: "number",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/ExclusiveMinConstraintValue/variant/string",
			name: "string",
			payloadType: "",
		},
	],
	FieldDecl: [],
	FieldDeclDoc: [],
	FieldDeclIdentity: [],
	FieldDeclNullable: [],
	FormatConstraint: [],
	FormatConstraintKeyword: [
		{
			identity: "ix://agent-ix/semantic-core/type/FormatConstraintKeyword/variant/format",
			name: "format",
			payloadType: "",
		},
	],
	FormatConstraintName: [],
	Identifier: [],
	KernelScalar: [
		{
			identity: "ix://agent-ix/semantic-core/type/KernelScalar/variant/Boolean",
			name: "Boolean",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/KernelScalar/variant/Bytes",
			name: "Bytes",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/KernelScalar/variant/Decimal",
			name: "Decimal",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/KernelScalar/variant/Duration",
			name: "Duration",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/KernelScalar/variant/Integer",
			name: "Integer",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/KernelScalar/variant/JsonObject",
			name: "JsonObject",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/KernelScalar/variant/String",
			name: "String",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/KernelScalar/variant/Timestamp",
			name: "Timestamp",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/KernelScalar/variant/UUID",
			name: "UUID",
			payloadType: "",
		},
	],
	MaxConstraint: [],
	MaxConstraintKeyword: [
		{
			identity: "ix://agent-ix/semantic-core/type/MaxConstraintKeyword/variant/max",
			name: "max",
			payloadType: "",
		},
	],
	MaxConstraintValue: [
		{
			identity: "ix://agent-ix/semantic-core/type/MaxConstraintValue/variant/number",
			name: "number",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/MaxConstraintValue/variant/string",
			name: "string",
			payloadType: "",
		},
	],
	MaxLengthConstraint: [],
	MaxLengthConstraintKeyword: [
		{
			identity: "ix://agent-ix/semantic-core/type/MaxLengthConstraintKeyword/variant/maxLength",
			name: "maxLength",
			payloadType: "",
		},
	],
	MaxLengthConstraintValue: [],
	MinConstraint: [],
	MinConstraintKeyword: [
		{
			identity: "ix://agent-ix/semantic-core/type/MinConstraintKeyword/variant/min",
			name: "min",
			payloadType: "",
		},
	],
	MinConstraintValue: [
		{
			identity: "ix://agent-ix/semantic-core/type/MinConstraintValue/variant/number",
			name: "number",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/MinConstraintValue/variant/string",
			name: "string",
			payloadType: "",
		},
	],
	MinLengthConstraint: [],
	MinLengthConstraintKeyword: [
		{
			identity: "ix://agent-ix/semantic-core/type/MinLengthConstraintKeyword/variant/minLength",
			name: "minLength",
			payloadType: "",
		},
	],
	MinLengthConstraintValue: [],
	Multiplicity: [],
	MultiplicityLower: [],
	MultiplicityOrdered: [],
	MultiplicityUnique: [],
	MultiplicityUpper: [],
	NonEmptyConstraint: [],
	NonEmptyConstraintKeyword: [
		{
			identity: "ix://agent-ix/semantic-core/type/NonEmptyConstraintKeyword/variant/nonEmpty",
			name: "nonEmpty",
			payloadType: "",
		},
	],
	OperationDecl: [],
	PatternConstraint: [],
	PatternConstraintDialect: [
		{
			identity: "ix://agent-ix/semantic-core/type/PatternConstraintDialect/variant/ecma-262",
			name: "ecma-262",
			payloadType: "",
		},
	],
	PatternConstraintKeyword: [
		{
			identity: "ix://agent-ix/semantic-core/type/PatternConstraintKeyword/variant/pattern",
			name: "pattern",
			payloadType: "",
		},
	],
	PatternConstraintRegex: [],
	RelationDecl: [],
	RelationDeclComposite: [],
	SemanticId: [],
	SourceLocus: [],
	SourceLocusEndColumn: [],
	SourceLocusEndLine: [],
	SourceLocusPath: [],
	SourceLocusStartColumn: [],
	SourceLocusStartLine: [],
	TypeRef: [],
	TypeRefTarget: [
		{
			identity: "ix://agent-ix/semantic-core/type/TypeRefTarget/variant/KernelScalar",
			name: "KernelScalar",
			payloadType: "ix://agent-ix/semantic-core/type/KernelScalar",
		},
		{
			identity: "ix://agent-ix/semantic-core/type/TypeRefTarget/variant/SemanticId",
			name: "SemanticId",
			payloadType: "ix://agent-ix/semantic-core/type/SemanticId",
		},
	],
	UniqueConstraint: [],
	UniqueConstraintKeyword: [
		{
			identity: "ix://agent-ix/semantic-core/type/UniqueConstraintKeyword/variant/unique",
			name: "unique",
			payloadType: "",
		},
	],
	UnitSymbol: [],
} as const satisfies Record<ExportedTypeName, readonly VariantDescriptor[]>;

/** The constraints each type carries, including their semantic identities. */
export const TYPE_CONSTRAINTS = {
	ClauseLanguage: [],
	ClauseRef: [],
	ConstraintDecl: [],
	ConstraintKeyword: [],
	DecimalPolicy: [],
	DecimalPolicyPrecision: [
		{
			identity: "ix://agent-ix/semantic-core/type/DecimalPolicyPrecision/constraint/max",
			keyword: "max",
			appliesTo: "ix://agent-ix/semantic-core/type/DecimalPolicyPrecision",
			diagnosticCode: "agent-ix.semantic-core.MAX",
			operands: {
				value: 2147483647,
			},
		},
		{
			identity: "ix://agent-ix/semantic-core/type/DecimalPolicyPrecision/constraint/min",
			keyword: "min",
			appliesTo: "ix://agent-ix/semantic-core/type/DecimalPolicyPrecision",
			diagnosticCode: "agent-ix.semantic-core.MIN",
			operands: {
				value: 1,
			},
		},
	],
	DecimalPolicyScale: [
		{
			identity: "ix://agent-ix/semantic-core/type/DecimalPolicyScale/constraint/max",
			keyword: "max",
			appliesTo: "ix://agent-ix/semantic-core/type/DecimalPolicyScale",
			diagnosticCode: "agent-ix.semantic-core.MAX",
			operands: {
				value: 2147483647,
			},
		},
		{
			identity: "ix://agent-ix/semantic-core/type/DecimalPolicyScale/constraint/min",
			keyword: "min",
			appliesTo: "ix://agent-ix/semantic-core/type/DecimalPolicyScale",
			diagnosticCode: "agent-ix.semantic-core.MIN",
			operands: {
				value: 0,
			},
		},
	],
	DefaultDecl: [],
	DefaultDeclValue: [],
	DefaultKind: [],
	EdgeCategory: [],
	EnumValue: [],
	EnumValueDoc: [],
	EnumValuesConstraint: [],
	EnumValuesConstraintKeyword: [],
	EnumValuesConstraintValues: [],
	ExclusiveMaxConstraint: [],
	ExclusiveMaxConstraintKeyword: [],
	ExclusiveMaxConstraintValue: [],
	ExclusiveMinConstraint: [],
	ExclusiveMinConstraintKeyword: [],
	ExclusiveMinConstraintValue: [],
	FieldDecl: [],
	FieldDeclDoc: [],
	FieldDeclIdentity: [],
	FieldDeclNullable: [],
	FormatConstraint: [],
	FormatConstraintKeyword: [],
	FormatConstraintName: [],
	Identifier: [],
	KernelScalar: [],
	MaxConstraint: [],
	MaxConstraintKeyword: [],
	MaxConstraintValue: [],
	MaxLengthConstraint: [],
	MaxLengthConstraintKeyword: [],
	MaxLengthConstraintValue: [
		{
			identity: "ix://agent-ix/semantic-core/type/MaxLengthConstraintValue/constraint/max",
			keyword: "max",
			appliesTo: "ix://agent-ix/semantic-core/type/MaxLengthConstraintValue",
			diagnosticCode: "agent-ix.semantic-core.MAX",
			operands: {
				value: 2147483647,
			},
		},
		{
			identity: "ix://agent-ix/semantic-core/type/MaxLengthConstraintValue/constraint/min",
			keyword: "min",
			appliesTo: "ix://agent-ix/semantic-core/type/MaxLengthConstraintValue",
			diagnosticCode: "agent-ix.semantic-core.MIN",
			operands: {
				value: 0,
			},
		},
	],
	MinConstraint: [],
	MinConstraintKeyword: [],
	MinConstraintValue: [],
	MinLengthConstraint: [],
	MinLengthConstraintKeyword: [],
	MinLengthConstraintValue: [
		{
			identity: "ix://agent-ix/semantic-core/type/MinLengthConstraintValue/constraint/max",
			keyword: "max",
			appliesTo: "ix://agent-ix/semantic-core/type/MinLengthConstraintValue",
			diagnosticCode: "agent-ix.semantic-core.MAX",
			operands: {
				value: 2147483647,
			},
		},
		{
			identity: "ix://agent-ix/semantic-core/type/MinLengthConstraintValue/constraint/min",
			keyword: "min",
			appliesTo: "ix://agent-ix/semantic-core/type/MinLengthConstraintValue",
			diagnosticCode: "agent-ix.semantic-core.MIN",
			operands: {
				value: 0,
			},
		},
	],
	Multiplicity: [],
	MultiplicityLower: [
		{
			identity: "ix://agent-ix/semantic-core/type/MultiplicityLower/constraint/max",
			keyword: "max",
			appliesTo: "ix://agent-ix/semantic-core/type/MultiplicityLower",
			diagnosticCode: "agent-ix.semantic-core.MAX",
			operands: {
				value: 2147483647,
			},
		},
		{
			identity: "ix://agent-ix/semantic-core/type/MultiplicityLower/constraint/min",
			keyword: "min",
			appliesTo: "ix://agent-ix/semantic-core/type/MultiplicityLower",
			diagnosticCode: "agent-ix.semantic-core.MIN",
			operands: {
				value: 0,
			},
		},
	],
	MultiplicityOrdered: [],
	MultiplicityUnique: [],
	MultiplicityUpper: [
		{
			identity: "ix://agent-ix/semantic-core/type/MultiplicityUpper/constraint/max",
			keyword: "max",
			appliesTo: "ix://agent-ix/semantic-core/type/MultiplicityUpper",
			diagnosticCode: "agent-ix.semantic-core.MAX",
			operands: {
				value: 2147483647,
			},
		},
		{
			identity: "ix://agent-ix/semantic-core/type/MultiplicityUpper/constraint/min",
			keyword: "min",
			appliesTo: "ix://agent-ix/semantic-core/type/MultiplicityUpper",
			diagnosticCode: "agent-ix.semantic-core.MIN",
			operands: {
				value: 0,
			},
		},
	],
	NonEmptyConstraint: [],
	NonEmptyConstraintKeyword: [],
	OperationDecl: [],
	PatternConstraint: [],
	PatternConstraintDialect: [],
	PatternConstraintKeyword: [],
	PatternConstraintRegex: [],
	RelationDecl: [],
	RelationDeclComposite: [],
	SemanticId: [],
	SourceLocus: [],
	SourceLocusEndColumn: [
		{
			identity: "ix://agent-ix/semantic-core/type/SourceLocusEndColumn/constraint/max",
			keyword: "max",
			appliesTo: "ix://agent-ix/semantic-core/type/SourceLocusEndColumn",
			diagnosticCode: "agent-ix.semantic-core.MAX",
			operands: {
				value: 2147483647,
			},
		},
		{
			identity: "ix://agent-ix/semantic-core/type/SourceLocusEndColumn/constraint/min",
			keyword: "min",
			appliesTo: "ix://agent-ix/semantic-core/type/SourceLocusEndColumn",
			diagnosticCode: "agent-ix.semantic-core.MIN",
			operands: {
				value: 1,
			},
		},
	],
	SourceLocusEndLine: [
		{
			identity: "ix://agent-ix/semantic-core/type/SourceLocusEndLine/constraint/max",
			keyword: "max",
			appliesTo: "ix://agent-ix/semantic-core/type/SourceLocusEndLine",
			diagnosticCode: "agent-ix.semantic-core.MAX",
			operands: {
				value: 2147483647,
			},
		},
		{
			identity: "ix://agent-ix/semantic-core/type/SourceLocusEndLine/constraint/min",
			keyword: "min",
			appliesTo: "ix://agent-ix/semantic-core/type/SourceLocusEndLine",
			diagnosticCode: "agent-ix.semantic-core.MIN",
			operands: {
				value: 1,
			},
		},
	],
	SourceLocusPath: [],
	SourceLocusStartColumn: [
		{
			identity: "ix://agent-ix/semantic-core/type/SourceLocusStartColumn/constraint/max",
			keyword: "max",
			appliesTo: "ix://agent-ix/semantic-core/type/SourceLocusStartColumn",
			diagnosticCode: "agent-ix.semantic-core.MAX",
			operands: {
				value: 2147483647,
			},
		},
		{
			identity: "ix://agent-ix/semantic-core/type/SourceLocusStartColumn/constraint/min",
			keyword: "min",
			appliesTo: "ix://agent-ix/semantic-core/type/SourceLocusStartColumn",
			diagnosticCode: "agent-ix.semantic-core.MIN",
			operands: {
				value: 1,
			},
		},
	],
	SourceLocusStartLine: [
		{
			identity: "ix://agent-ix/semantic-core/type/SourceLocusStartLine/constraint/max",
			keyword: "max",
			appliesTo: "ix://agent-ix/semantic-core/type/SourceLocusStartLine",
			diagnosticCode: "agent-ix.semantic-core.MAX",
			operands: {
				value: 2147483647,
			},
		},
		{
			identity: "ix://agent-ix/semantic-core/type/SourceLocusStartLine/constraint/min",
			keyword: "min",
			appliesTo: "ix://agent-ix/semantic-core/type/SourceLocusStartLine",
			diagnosticCode: "agent-ix.semantic-core.MIN",
			operands: {
				value: 1,
			},
		},
	],
	TypeRef: [],
	TypeRefTarget: [],
	UniqueConstraint: [],
	UniqueConstraintKeyword: [],
	UnitSymbol: [],
} as const satisfies Record<ExportedTypeName, readonly ConstraintDescriptor[]>;

/**
 * The declared default of each exported field.
 *
 * A `representation` or `migration` default appears here even though the
 * generated validator applies only a `semantic` one, so a consumer can see a
 * default the semantic contract declines to substitute.
 */
export const FIELD_DEFAULT = {
	"ClauseRef.clauseId": { kind: "none", value: null },
	"ClauseRef.language": { kind: "none", value: null },
	"ClauseRef.sourceSpan": { kind: "none", value: null },
	"DecimalPolicy.precision": { kind: "none", value: null },
	"DecimalPolicy.scale": { kind: "none", value: null },
	"DefaultDecl.kind": { kind: "none", value: null },
	"DefaultDecl.value": { kind: "none", value: null },
	"EnumValue.doc": { kind: "none", value: null },
	"EnumValue.value": { kind: "none", value: null },
	"EnumValuesConstraint.keyword": { kind: "none", value: null },
	"EnumValuesConstraint.values": { kind: "none", value: null },
	"ExclusiveMaxConstraint.keyword": { kind: "none", value: null },
	"ExclusiveMaxConstraint.value": { kind: "none", value: null },
	"ExclusiveMinConstraint.keyword": { kind: "none", value: null },
	"ExclusiveMinConstraint.value": { kind: "none", value: null },
	"FieldDecl.constraints": { kind: "none", value: null },
	"FieldDecl.default": { kind: "none", value: null },
	"FieldDecl.doc": { kind: "none", value: null },
	"FieldDecl.identity": { kind: "none", value: null },
	"FieldDecl.name": { kind: "none", value: null },
	"FieldDecl.nullable": { kind: "none", value: null },
	"FieldDecl.type": { kind: "none", value: null },
	"FormatConstraint.keyword": { kind: "none", value: null },
	"FormatConstraint.name": { kind: "none", value: null },
	"MaxConstraint.keyword": { kind: "none", value: null },
	"MaxConstraint.value": { kind: "none", value: null },
	"MaxLengthConstraint.keyword": { kind: "none", value: null },
	"MaxLengthConstraint.value": { kind: "none", value: null },
	"MinConstraint.keyword": { kind: "none", value: null },
	"MinConstraint.value": { kind: "none", value: null },
	"MinLengthConstraint.keyword": { kind: "none", value: null },
	"MinLengthConstraint.value": { kind: "none", value: null },
	"Multiplicity.lower": { kind: "none", value: null },
	"Multiplicity.ordered": { kind: "none", value: null },
	"Multiplicity.unique": { kind: "none", value: null },
	"Multiplicity.upper": { kind: "none", value: null },
	"NonEmptyConstraint.keyword": { kind: "none", value: null },
	"OperationDecl.name": { kind: "none", value: null },
	"OperationDecl.params": { kind: "none", value: null },
	"OperationDecl.post": { kind: "none", value: null },
	"OperationDecl.pre": { kind: "none", value: null },
	"OperationDecl.returns": { kind: "none", value: null },
	"PatternConstraint.dialect": { kind: "none", value: null },
	"PatternConstraint.keyword": { kind: "none", value: null },
	"PatternConstraint.regex": { kind: "none", value: null },
	"RelationDecl.category": { kind: "none", value: null },
	"RelationDecl.composite": { kind: "none", value: null },
	"RelationDecl.multiplicity": { kind: "none", value: null },
	"RelationDecl.target": { kind: "none", value: null },
	"RelationDecl.verb": { kind: "none", value: null },
	"SourceLocus.endColumn": { kind: "none", value: null },
	"SourceLocus.endLine": { kind: "none", value: null },
	"SourceLocus.path": { kind: "none", value: null },
	"SourceLocus.sourceIdentity": { kind: "none", value: null },
	"SourceLocus.startColumn": { kind: "none", value: null },
	"SourceLocus.startLine": { kind: "none", value: null },
	"TypeRef.decimal": { kind: "none", value: null },
	"TypeRef.multiplicity": { kind: "none", value: null },
	"TypeRef.target": { kind: "none", value: null },
	"TypeRef.unit": { kind: "none", value: null },
	"UniqueConstraint.keyword": { kind: "none", value: null },
} as const satisfies Record<ExportedFieldKey, DefaultDescriptor>;

