/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Generated by the Agent IX TypeScript semantic backend. Do not edit.
 * backend: ix://agent-ix/filament-core-data/backend/typescript@0.1.0
 * contract: 1.1.0
 * package: agent-ix/semantic-kernel@0.2.0
 * fingerprint: sha256:386f7c78f388d37f59c651a66bd231b2efcc152b5e9f08a80c2b873ca404ac73
 */

/**
 * The provenance of the semantic document this package was generated from.
 *
 * Every value here is copied from the document or computed from it. There is no
 * generation timestamp, no build date, no hostname, no machine identifier, no
 * user name, no user id, no home directory, no working directory, no absolute
 * path, no tool path, no interpreter path and no environment variable value:
 * each of those is a determinism leak, and generating this package twice at
 * different times produces identical bytes because none of them is read.
 *
 * An occurrence's `observedAt` is the one timestamp a generated package
 * carries, and it is contract data the document's author wrote. It is declared
 * in `identity.ts`, not here.
 */

/** The document's provenance and the fingerprint of its normalized form. */
export const PROVENANCE = {
	contractVersion: "1.1.0",
	sourceIdentity: "ix://agent-ix/semantic-core",
	sourceVersion: "0.2.0",
	sourceDialect: "spec-bundle",
	sourceDigest:
		"sha256:0000000000000000000000000000000000000000000000000000000000000000",
	packageIdentity: "agent-ix/semantic-kernel",
	packageVersion: "0.2.0",
	packageManifestDigest:
		"sha256:0000000000000000000000000000000000000000000000000000000000000000",
	packageMappingVersions: [],
	packageProfileVersions: [],
	packageLockDigest:
		"sha256:0000000000000000000000000000000000000000000000000000000000000000",
	fingerprint:
		"sha256:386f7c78f388d37f59c651a66bd231b2efcc152b5e9f08a80c2b873ca404ac73",
	backendIdentity: "ix://agent-ix/filament-core-data/backend/typescript",
	backendVersion: "0.1.0",
} as const;
