/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Generated by the Agent IX TypeScript semantic backend. Do not edit.
 * backend: ix://agent-ix/filament-core-data/backend/typescript@0.1.0
 * contract: 2.0.0
 * package: agent-ix/semantic-kernel@0.2.0
 * fingerprint: sha256:8939ef5559a1ff9d7265a65fd3e958a0ca52f47b91555f9865e819627e040c91
 */

/**
 * The property that discriminates every generated union.
 * Exported as one constant so that a `switch` over it narrows the default arm to `never`, and so that a ruling on agent-ix/filament-core-data#58 — which records that the published contract states no JSON wire form for a discriminated union — moves one declaration rather than every union.
 */
export const UNION_DISCRIMINANT = "kind";

export type ClauseLanguage = string;

export interface ClauseRef {
	readonly clauseId: Identifier;
	readonly language: ClauseLanguage;
	readonly sourceSpan?: SourceLocus;
}

export type ConstraintDecl = EnumValuesConstraint | ExclusiveMaxConstraint | ExclusiveMinConstraint | FormatConstraint | MaxConstraint | MaxLengthConstraint | MinConstraint | MinLengthConstraint | NonEmptyConstraint | PatternConstraint | UniqueConstraint;

export type ConstraintKeyword = "enumValues" | "exclusiveMax" | "exclusiveMin" | "format" | "max" | "maxLength" | "min" | "minLength" | "nonEmpty" | "pattern" | "unique";

export interface DecimalPolicy {
	readonly precision: DecimalPolicyPrecision;
	readonly scale: DecimalPolicyScale;
}

export type DecimalPolicyPrecision = number;

export type DecimalPolicyScale = number;

export interface DefaultDecl {
	readonly kind: DefaultKind;
	readonly value?: DefaultDeclValue;
}

export interface DefaultDeclValue {
	/**
	 * Unknown members are admitted: this record declares `unknownPolicy: "preserve"`.
	 */
	readonly __unknownPolicy?: "preserve";
	readonly [key: string]: unknown;
}

export type DefaultKind = "migration" | "representation" | "semantic";

export type EdgeCategory = "behavioral" | "dataflow" | "dependency" | "governance" | "realization" | "structural" | "traceability";

export interface EnumValue {
	readonly doc?: EnumValueDoc;
	readonly value: Identifier;
}

export type EnumValueDoc = string;

export interface EnumValuesConstraint {
	readonly keyword: EnumValuesConstraintKeyword;
	readonly values: readonly EnumValuesConstraintValues[];
}

export type EnumValuesConstraintKeyword = "enumValues";

export type EnumValuesConstraintValues = EnumValuesConstraintValuesBoolean | EnumValuesConstraintValuesNumber | EnumValuesConstraintValuesString;

export type EnumValuesConstraintValuesBoolean = boolean;

export type EnumValuesConstraintValuesNumber = number;

export type EnumValuesConstraintValuesString = string;

export interface ExclusiveMaxConstraint {
	readonly keyword: ExclusiveMaxConstraintKeyword;
	readonly value: ExclusiveMaxConstraintValue;
}

export type ExclusiveMaxConstraintKeyword = "exclusiveMax";

export type ExclusiveMaxConstraintValue = ExclusiveMaxConstraintValueNumber | ExclusiveMaxConstraintValueString;

export type ExclusiveMaxConstraintValueNumber = number;

export type ExclusiveMaxConstraintValueString = string;

export interface ExclusiveMinConstraint {
	readonly keyword: ExclusiveMinConstraintKeyword;
	readonly value: ExclusiveMinConstraintValue;
}

export type ExclusiveMinConstraintKeyword = "exclusiveMin";

export type ExclusiveMinConstraintValue = ExclusiveMinConstraintValueNumber | ExclusiveMinConstraintValueString;

export type ExclusiveMinConstraintValueNumber = number;

export type ExclusiveMinConstraintValueString = string;

export interface FieldDecl {
	readonly constraints?: readonly ConstraintDecl[];
	readonly default?: DefaultDecl;
	readonly doc?: FieldDeclDoc;
	readonly identity?: FieldDeclIdentity;
	readonly name: Identifier;
	readonly nullable?: FieldDeclNullable;
	readonly type: TypeRef;
}

export type FieldDeclDoc = string;

export type FieldDeclIdentity = boolean;

export type FieldDeclNullable = boolean;

export interface FormatConstraint {
	readonly keyword: FormatConstraintKeyword;
	readonly name: FormatConstraintName;
}

export type FormatConstraintKeyword = "format";

export type FormatConstraintName = string;

export type Identifier = string;

export type KernelScalar = "Boolean" | "Bytes" | "Decimal" | "Duration" | "Integer" | "JsonObject" | "String" | "Timestamp" | "UUID";

export interface MaxConstraint {
	readonly keyword: MaxConstraintKeyword;
	readonly value: MaxConstraintValue;
}

export type MaxConstraintKeyword = "max";

export type MaxConstraintValue = MaxConstraintValueNumber | MaxConstraintValueString;

export type MaxConstraintValueNumber = number;

export type MaxConstraintValueString = string;

export interface MaxLengthConstraint {
	readonly keyword: MaxLengthConstraintKeyword;
	readonly value: MaxLengthConstraintValue;
}

export type MaxLengthConstraintKeyword = "maxLength";

export type MaxLengthConstraintValue = number;

export interface MinConstraint {
	readonly keyword: MinConstraintKeyword;
	readonly value: MinConstraintValue;
}

export type MinConstraintKeyword = "min";

export type MinConstraintValue = MinConstraintValueNumber | MinConstraintValueString;

export type MinConstraintValueNumber = number;

export type MinConstraintValueString = string;

export interface MinLengthConstraint {
	readonly keyword: MinLengthConstraintKeyword;
	readonly value: MinLengthConstraintValue;
}

export type MinLengthConstraintKeyword = "minLength";

export type MinLengthConstraintValue = number;

export interface Multiplicity {
	readonly lower: MultiplicityLower;
	readonly ordered?: MultiplicityOrdered;
	readonly unique?: MultiplicityUnique;
	readonly upper?: MultiplicityUpper;
}

export type MultiplicityLower = number;

export type MultiplicityOrdered = boolean;

export type MultiplicityUnique = boolean;

export type MultiplicityUpper = number;

export interface NonEmptyConstraint {
	readonly keyword: NonEmptyConstraintKeyword;
}

export type NonEmptyConstraintKeyword = "nonEmpty";

export interface OperationDecl {
	readonly name: Identifier;
	readonly params?: readonly FieldDecl[];
	readonly post?: readonly ClauseRef[];
	readonly pre?: readonly ClauseRef[];
	readonly returns?: TypeRef;
}

export interface PatternConstraint {
	readonly dialect: PatternConstraintDialect;
	readonly keyword: PatternConstraintKeyword;
	readonly regex: PatternConstraintRegex;
}

export type PatternConstraintDialect = "ecma-262";

export type PatternConstraintKeyword = "pattern";

export type PatternConstraintRegex = string;

export interface RelationDecl {
	readonly category: EdgeCategory;
	readonly composite?: RelationDeclComposite;
	readonly multiplicity?: Multiplicity;
	readonly target: SemanticId;
	readonly verb: Identifier;
}

export type RelationDeclComposite = boolean;

export type SemanticId = string;

export interface SourceLocus {
	readonly endColumn?: SourceLocusEndColumn;
	readonly endLine?: SourceLocusEndLine;
	readonly path: SourceLocusPath;
	readonly sourceIdentity: SemanticId;
	readonly startColumn: SourceLocusStartColumn;
	readonly startLine: SourceLocusStartLine;
}

export type SourceLocusEndColumn = number;

export type SourceLocusEndLine = number;

export type SourceLocusPath = string;

export type SourceLocusStartColumn = number;

export type SourceLocusStartLine = number;

export interface TypeRef {
	readonly decimal?: DecimalPolicy;
	readonly multiplicity?: Multiplicity;
	readonly target: TypeRefTarget;
	readonly unit?: UnitSymbol;
}

export type TypeRefTarget = KernelScalar | SemanticId;

export interface UniqueConstraint {
	readonly keyword: UniqueConstraintKeyword;
}

export type UniqueConstraintKeyword = "unique";

export type UnitSymbol = string;
