# generated by datamodel-codegen:
#   filename:  ClauseRef.json

from __future__ import annotations

from msgspec import UNSET, Struct, UnsetType

from .ClauseLanguage import ClauseLanguage
from .Identifier import Identifier
from .SourceLocus import SourceLocus


class ClauseRef(Struct):
    clauseId: Identifier
    language: ClauseLanguage
    sourceSpan: SourceLocus | UnsetType = UNSET
