# generated by datamodel-codegen:
#   filename:  ConstraintKeyword.json

from __future__ import annotations

from enum import StrEnum


class ConstraintKeyword(StrEnum):
    min = 'min'
    max = 'max'
    exclusiveMin = 'exclusiveMin'
    exclusiveMax = 'exclusiveMax'
    pattern = 'pattern'
    minLength = 'minLength'
    maxLength = 'maxLength'
    enumValues = 'enumValues'
    nonEmpty = 'nonEmpty'
    unique = 'unique'
    format = 'format'
