# generated by datamodel-codegen:
#   filename:  DecimalPolicy.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class DecimalPolicy(Struct):
    precision: Annotated[int, Meta(ge=1, le=2147483647)]
    scale: Annotated[int, Meta(ge=0, le=2147483647)]
