# generated by datamodel-codegen:
#   filename:  DefaultDecl.json

from __future__ import annotations

from typing import Any

from msgspec import UNSET, Struct, UnsetType

from .DefaultKind import DefaultKind


class DefaultDecl(Struct):
    kind: DefaultKind
    value: Any | UnsetType = UNSET
