# generated by datamodel-codegen:
#   filename:  EnumValue.json

from __future__ import annotations

from msgspec import UNSET, Struct, UnsetType

from .Identifier import Identifier


class EnumValue(Struct):
    value: Identifier
    doc: str | UnsetType = UNSET
