# generated by datamodel-codegen:
#   filename:  EnumValuesConstraint.json

from __future__ import annotations

from typing import Annotated, Literal

from msgspec import Meta, Struct


class EnumValuesConstraint(Struct):
    keyword: Literal['enumValues']
    values: Annotated[list[str | float | bool], Meta(min_length=1)]
