# generated by datamodel-codegen:
#   filename:  ExclusiveMaxConstraint.json

from __future__ import annotations

from typing import Literal

from msgspec import Struct


class ExclusiveMaxConstraint(Struct):
    keyword: Literal['exclusiveMax']
    value: float | str
