# generated by datamodel-codegen:
#   filename:  ExclusiveMinConstraint.json

from __future__ import annotations

from typing import Literal

from msgspec import Struct


class ExclusiveMinConstraint(Struct):
    keyword: Literal['exclusiveMin']
    value: float | str
