# generated by datamodel-codegen:
#   filename:  FieldDecl.json

from __future__ import annotations

from msgspec import UNSET, Struct, UnsetType

from .ConstraintDecl import ConstraintDecl
from .DefaultDecl import DefaultDecl
from .Identifier import Identifier
from .TypeRef import TypeRef


class FieldDecl(Struct):
    name: Identifier
    type: TypeRef
    constraints: list[ConstraintDecl] | UnsetType = UNSET
    default: DefaultDecl | UnsetType = UNSET
    doc: str | UnsetType = UNSET
    identity: bool | UnsetType = UNSET
    nullable: bool | UnsetType = UNSET
