# generated by datamodel-codegen:
#   filename:  FormatConstraint.json

from __future__ import annotations

from typing import Annotated, Literal

from msgspec import Meta, Struct


class FormatConstraint(Struct):
    keyword: Literal['format']
    name: Annotated[
        str, Meta(pattern='^[a-z0-9][a-z0-9.-]*:[A-Za-z0-9][A-Za-z0-9._-]*$')
    ]
