# generated by datamodel-codegen:
#   filename:  Identifier.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta

type Identifier = Annotated[
    str,
    Meta(
        description='A declaration name: letters, digits, underscore; no leading digit.',
        pattern='^[A-Za-z_][A-Za-z0-9_]*$',
        title='Identifier',
    ),
]
