# generated by datamodel-codegen:
#   filename:  MaxConstraint.json

from __future__ import annotations

from typing import Literal

from msgspec import Struct


class MaxConstraint(Struct):
    keyword: Literal['max']
    value: float | str
