# generated by datamodel-codegen:
#   filename:  MaxLengthConstraint.json

from __future__ import annotations

from typing import Annotated, Literal

from msgspec import Meta, Struct


class MaxLengthConstraint(Struct):
    keyword: Literal['maxLength']
    value: Annotated[int, Meta(ge=0, le=2147483647)]
