# generated by datamodel-codegen:
#   filename:  MinConstraint.json

from __future__ import annotations

from typing import Literal

from msgspec import Struct


class MinConstraint(Struct):
    keyword: Literal['min']
    value: float | str
