# generated by datamodel-codegen:
#   filename:  MinLengthConstraint.json

from __future__ import annotations

from typing import Annotated, Literal

from msgspec import Meta, Struct


class MinLengthConstraint(Struct):
    keyword: Literal['minLength']
    value: Annotated[int, Meta(ge=0, le=2147483647)]
