# generated by datamodel-codegen:
#   filename:  Multiplicity.json

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType


class Multiplicity(Struct):
    lower: Annotated[int, Meta(ge=0, le=2147483647)]
    ordered: bool | UnsetType = UNSET
    unique: bool | UnsetType = UNSET
    upper: Annotated[int, Meta(ge=0, le=2147483647)] | UnsetType = UNSET
