# generated by datamodel-codegen:
#   filename:  NonEmptyConstraint.json

from __future__ import annotations

from typing import Literal

from msgspec import Struct


class NonEmptyConstraint(Struct):
    keyword: Literal['nonEmpty']
