# generated by datamodel-codegen:
#   filename:  OperationDecl.json

from __future__ import annotations

from msgspec import UNSET, Struct, UnsetType

from .ClauseRef import ClauseRef
from .FieldDecl import FieldDecl
from .Identifier import Identifier
from .TypeRef import TypeRef


class OperationDecl(Struct):
    name: Identifier
    params: list[FieldDecl]
    post: list[ClauseRef] | UnsetType = UNSET
    pre: list[ClauseRef] | UnsetType = UNSET
    returns: TypeRef | UnsetType = UNSET
