# generated by datamodel-codegen:
#   filename:  PatternConstraint.json

from __future__ import annotations

from typing import Annotated, Literal

from msgspec import Meta, Struct


class PatternConstraint(Struct):
    dialect: Literal['ecma-262']
    keyword: Literal['pattern']
    regex: Annotated[str, Meta(min_length=1)]
