# generated by datamodel-codegen:
#   filename:  RelationDecl.json

from __future__ import annotations

from msgspec import UNSET, Struct, UnsetType

from .EdgeCategory import EdgeCategory
from .Identifier import Identifier
from .Multiplicity import Multiplicity
from .SemanticId import SemanticId


class RelationDecl(Struct):
    category: EdgeCategory
    target: SemanticId
    verb: Identifier
    composite: bool | UnsetType = UNSET
    multiplicity: Multiplicity | UnsetType = UNSET
