# generated by datamodel-codegen:
#   filename:  SourceLocus.json

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType

from .SemanticId import SemanticId


class SourceLocus(Struct):
    path: Annotated[str, Meta(min_length=1)]
    sourceIdentity: SemanticId
    startColumn: Annotated[int, Meta(ge=1, le=2147483647)]
    startLine: Annotated[int, Meta(ge=1, le=2147483647)]
    endColumn: Annotated[int, Meta(ge=1, le=2147483647)] | UnsetType = UNSET
    endLine: Annotated[int, Meta(ge=1, le=2147483647)] | UnsetType = UNSET
