# generated by datamodel-codegen:
#   filename:  UniqueConstraint.json

from __future__ import annotations

from typing import Literal

from msgspec import Struct


class UniqueConstraint(Struct):
    keyword: Literal['unique']
