# generated by datamodel-codegen:
#   filename:  ClauseRef.json

from __future__ import annotations

from pydantic import ConfigDict
from pydantic.dataclasses import dataclass

from .ClauseLanguage import ClauseLanguage
from .Identifier import Identifier
from .SourceLocus import SourceLocus


@dataclass(config=ConfigDict(extra='forbid'))
class ClauseRef:
    clauseId: Identifier
    language: ClauseLanguage
    sourceSpan: SourceLocus | None = None
