# generated by datamodel-codegen:
#   filename:  ClauseLanguage.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field

type ClauseLanguage = Annotated[
    str,
    Field(
        description='`ocl`, `sysml`, `fretish`, or a namespaced `<ns>:<name>` language (FR-028).',
        pattern='^(ocl|sysml|fretish|[a-z0-9][a-z0-9.-]*:[A-Za-z0-9][A-Za-z0-9._-]*)$',
        title='ClauseLanguage',
    ),
]
