# generated by datamodel-codegen:
#   filename:  ConstraintDecl.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from .EnumValuesConstraint import EnumValuesConstraint
from .ExclusiveMaxConstraint import ExclusiveMaxConstraint
from .ExclusiveMinConstraint import ExclusiveMinConstraint
from .FormatConstraint import FormatConstraint
from .MaxConstraint import MaxConstraint
from .MaxLengthConstraint import MaxLengthConstraint
from .MinConstraint import MinConstraint
from .MinLengthConstraint import MinLengthConstraint
from .NonEmptyConstraint import NonEmptyConstraint
from .PatternConstraint import PatternConstraint
from .UniqueConstraint import UniqueConstraint

type ConstraintDecl = Annotated[
    MinConstraint | MaxConstraint | ExclusiveMinConstraint | ExclusiveMaxConstraint | PatternConstraint | MinLengthConstraint | MaxLengthConstraint | EnumValuesConstraint | NonEmptyConstraint | UniqueConstraint | FormatConstraint,
    Field(
        description='FR-029 constraint declaration, discriminated on `keyword`.',
        title='ConstraintDecl',
    ),
]
