# generated by datamodel-codegen:
#   filename:  DefaultKind.json

from __future__ import annotations

from enum import StrEnum


class DefaultKind(StrEnum):
    semantic = 'semantic'
    representation = 'representation'
    migration = 'migration'
