# generated by datamodel-codegen:
#   filename:  DefaultDecl.json

from __future__ import annotations

from typing import Any

from pydantic import ConfigDict
from pydantic.dataclasses import dataclass

from .DefaultKind import DefaultKind


@dataclass(config=ConfigDict(extra='forbid'))
class DefaultDecl:
    kind: DefaultKind
    value: Any | None = None
