# generated by datamodel-codegen:
#   filename:  EnumValuesConstraint.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from pydantic.dataclasses import dataclass


@dataclass(config=ConfigDict(extra='forbid'))
class EnumValuesConstraint:
    keyword: Literal['enumValues']
    values: Annotated[list[str | float | bool], Field(min_length=1)]
