# generated by datamodel-codegen:
#   filename:  EnumValue.json

from __future__ import annotations

from pydantic import ConfigDict
from pydantic.dataclasses import dataclass

from .Identifier import Identifier


@dataclass(config=ConfigDict(extra='forbid'))
class EnumValue:
    value: Identifier
    doc: str | None = None
