# generated by datamodel-codegen:
#   filename:  FieldDecl.json

from __future__ import annotations

from pydantic import ConfigDict
from pydantic.dataclasses import dataclass

from .ConstraintDecl import ConstraintDecl
from .DefaultDecl import DefaultDecl
from .Identifier import Identifier
from .TypeRef import TypeRef


@dataclass(config=ConfigDict(extra='forbid'))
class FieldDecl:
    name: Identifier
    type: TypeRef
    constraints: list[ConstraintDecl] | None = None
    default: DefaultDecl | None = None
    doc: str | None = None
    identity: bool | None = None
    nullable: bool | None = None
