# generated by datamodel-codegen:
#   filename:  FormatConstraint.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from pydantic.dataclasses import dataclass


@dataclass(config=ConfigDict(extra='forbid'))
class FormatConstraint:
    keyword: Literal['format']
    name: Annotated[
        str, Field(pattern='^[a-z0-9][a-z0-9.-]*:[A-Za-z0-9][A-Za-z0-9._-]*$')
    ]
