# generated by datamodel-codegen:
#   filename:  MaxConstraint.json

from __future__ import annotations

from typing import Literal

from pydantic import ConfigDict
from pydantic.dataclasses import dataclass


@dataclass(config=ConfigDict(extra='forbid'))
class MaxConstraint:
    keyword: Literal['max']
    value: float | str
