# generated by datamodel-codegen:
#   filename:  MaxLengthConstraint.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from pydantic.dataclasses import dataclass


@dataclass(config=ConfigDict(extra='forbid'))
class MaxLengthConstraint:
    keyword: Literal['maxLength']
    value: Annotated[int, Field(ge=0, le=2147483647)]
