# generated by datamodel-codegen:
#   filename:  MinConstraint.json

from __future__ import annotations

from typing import Literal

from pydantic import ConfigDict
from pydantic.dataclasses import dataclass


@dataclass(config=ConfigDict(extra='forbid'))
class MinConstraint:
    keyword: Literal['min']
    value: float | str
