# generated by datamodel-codegen:
#   filename:  Multiplicity.json

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field
from pydantic.dataclasses import dataclass


@dataclass(config=ConfigDict(extra='forbid'))
class Multiplicity:
    lower: Annotated[int, Field(ge=0, le=2147483647)]
    ordered: bool | None = None
    unique: bool | None = None
    upper: Annotated[int | None, Field(ge=0, le=2147483647)] = None
