# generated by datamodel-codegen:
#   filename:  NonEmptyConstraint.json

from __future__ import annotations

from typing import Literal

from pydantic import ConfigDict
from pydantic.dataclasses import dataclass


@dataclass(config=ConfigDict(extra='forbid'))
class NonEmptyConstraint:
    keyword: Literal['nonEmpty']
