# generated by datamodel-codegen:
#   filename:  OperationDecl.json

from __future__ import annotations

from pydantic import ConfigDict
from pydantic.dataclasses import dataclass

from .ClauseRef import ClauseRef
from .FieldDecl import FieldDecl
from .Identifier import Identifier
from .TypeRef import TypeRef


@dataclass(config=ConfigDict(extra='forbid'))
class OperationDecl:
    name: Identifier
    params: list[FieldDecl]
    post: list[ClauseRef] | None = None
    pre: list[ClauseRef] | None = None
    returns: TypeRef | None = None
