# generated by datamodel-codegen:
#   filename:  PatternConstraint.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from pydantic.dataclasses import dataclass


@dataclass(config=ConfigDict(extra='forbid'))
class PatternConstraint:
    dialect: Literal['ecma-262']
    keyword: Literal['pattern']
    regex: Annotated[str, Field(min_length=1)]
