# generated by datamodel-codegen:
#   filename:  RelationDecl.json

from __future__ import annotations

from pydantic import ConfigDict
from pydantic.dataclasses import dataclass

from .EdgeCategory import EdgeCategory
from .Identifier import Identifier
from .Multiplicity import Multiplicity
from .SemanticId import SemanticId


@dataclass(config=ConfigDict(extra='forbid'))
class RelationDecl:
    category: EdgeCategory
    target: SemanticId
    verb: Identifier
    composite: bool | None = None
    multiplicity: Multiplicity | None = None
