# generated by datamodel-codegen:
#   filename:  SemanticId.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field

type SemanticId = Annotated[
    str,
    Field(
        description='A stable semantic identity, same pattern as the IR `semanticIdentity`.',
        pattern='^ix://[a-z0-9][a-z0-9._-]*/[A-Za-z0-9][A-Za-z0-9._~:/-]*$',
        title='SemanticId',
    ),
]
