# generated by datamodel-codegen:
#   filename:  SourceLocus.json

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field
from pydantic.dataclasses import dataclass

from .SemanticId import SemanticId


@dataclass(config=ConfigDict(extra='forbid'))
class SourceLocus:
    path: Annotated[str, Field(min_length=1)]
    sourceIdentity: SemanticId
    startColumn: Annotated[int, Field(ge=1, le=2147483647)]
    startLine: Annotated[int, Field(ge=1, le=2147483647)]
    endColumn: Annotated[int | None, Field(ge=1, le=2147483647)] = None
    endLine: Annotated[int | None, Field(ge=1, le=2147483647)] = None
