# generated by datamodel-codegen:
#   filename:  TypeRef.json

from __future__ import annotations

from pydantic import ConfigDict
from pydantic.dataclasses import dataclass

from .DecimalPolicy import DecimalPolicy
from .KernelScalar import KernelScalar
from .Multiplicity import Multiplicity
from .SemanticId import SemanticId
from .UnitSymbol import UnitSymbol


@dataclass(config=ConfigDict(extra='forbid'))
class TypeRef:
    target: SemanticId | KernelScalar
    decimal: DecimalPolicy | None = None
    multiplicity: Multiplicity | None = None
    unit: UnitSymbol | None = None
