# generated by datamodel-codegen:
#   filename:  UniqueConstraint.json

from __future__ import annotations

from typing import Literal

from pydantic import ConfigDict
from pydantic.dataclasses import dataclass


@dataclass(config=ConfigDict(extra='forbid'))
class UniqueConstraint:
    keyword: Literal['unique']
