/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Generated by the Agent IX TypeScript semantic backend. Do not edit.
 * backend: ix://agent-ix/filament-core-data/backend/typescript@0.1.0
 * contract: 1.1.0
 * package: agent-ix/conformance@1.0.0
 * fingerprint: sha256:e2f0f9228011b4d10fac90ac6835f823bc07ba556c2ad532ba5e1a0327d7380a
 */

/**
 * The semantic identity of everything this package renders, and the contract
 * data a TypeScript type cannot carry: roles, unknown policies, units,
 * relationship descriptors, and extensions at type and field level.
 *
 * Identities are copied from the semantic document verbatim. They are never
 * minted, shortened or re-cased here: an identity that moves when a display
 * name changes is exactly the defect `conformance/defects.json` records as
 * DEF-PROTO-008, and the generated identifier moving while the identity does not
 * is what makes such a rename visible.
 *
 * This module imports nothing, so a consumer reading identity data reaches no
 * validator.
 */

/** One extension the document declares, at any of its three levels. */
export interface ExtensionDescriptor {
	readonly identity: string;
	readonly version: string;
	readonly required: boolean;
	readonly capability?: string;
	readonly payload: unknown;
}

/** One relationship a record declares. Rendered here and nowhere else. */
export interface RelationshipDescriptor {
	readonly identity: string;
	readonly verb: string;
	readonly category: string;
	readonly composite: boolean;
	readonly target: string;
	readonly lower: number;
	/** `null` where the document declares no upper bound. */
	readonly upper: number | null;
}

/** One operation parameter, or an operation's return. */
export interface FieldDescriptor {
	readonly identity: string;
	readonly name: string;
	readonly typeRef: string;
	readonly optional: boolean;
	readonly nullable: boolean;
	readonly collection: boolean;
	readonly lower: number;
	readonly upper: number | null;
}

/**
 * One operation a record declares, as data.
 *
 * No executable function is generated for it: the generated surface is data,
 * and an operation is contract data a consumer may dispatch on.
 */
export interface OperationDescriptor {
	readonly identity: string;
	readonly name: string;
	readonly params: readonly FieldDescriptor[];
	readonly returns: {
		readonly typeRef: string;
		readonly nullable: boolean;
		readonly lower: number;
		readonly upper: number | null;
	} | null;
	readonly pre: readonly string[];
	readonly post: readonly string[];
}

/**
 * One clause a type declares, with its text carried opaquely.
 *
 * The text is not parsed. `agent-ix/quire-contract-ir#52` owns clause
 * semantics, and the IR carries the text without parsing it.
 */
export interface ClauseDescriptor {
	readonly identity: string;
	readonly language: string;
	readonly clauseId: string;
	readonly text: string;
	readonly sourceSpan: {
		readonly path: string;
		readonly startLine: number;
		readonly startColumn: number;
	} | null;
}

/** One enum or union member, including its semantic identity. */
export interface VariantDescriptor {
	readonly identity: string;
	readonly name: string;
	readonly payloadType: string;
}

/** One constraint's semantic identity and operands. */
export interface ConstraintDescriptor {
	readonly identity: string;
	readonly keyword: string;
	readonly appliesTo: string;
	readonly diagnosticCode: string;
	readonly operands: unknown;
}

/**
 * One field's declared default.
 *
 * The kind is carried for every field. The value is carried wherever the kind
 * is not `none`, including for a `representation` or a `migration` default that
 * the generated validator deliberately does not apply.
 */
export interface DefaultDescriptor {
	readonly kind: string;
	readonly value: unknown;
}

/** One observed value the document carries. */
export interface OccurrenceDescriptor {
	readonly identity: string;
	readonly definition: string;
	/** Copied verbatim from the document; not a clock this backend read. */
	readonly observedAt: string;
	readonly value: unknown;
}

/** Every type name this package exports. */
export type ExportedTypeName =
	| "Count"
	| "Millis"
	| "Node"
	| "NodeRef"
	| "Payload"
	| "Root"
	| "Status"
	| "Text"
	| "TextList"
	| "TextMap";

/** Every `<Type>.<field>` key this package exports a field identity for. */
export type ExportedFieldKey =
	| "Node.attrs"
	| "Node.children"
	| "Node.elapsed"
	| "Node.id"
	| "Node.label"
	| "Node.payload"
	| "Node.status"
	| "Node.tags"
	| "Root.name"
	| "Root.node";

/** The semantic identity of each exported type. */
export const TYPE_IDENTITY = {
	Count: "ix://agent-ix/conformance/type/Count",
	Millis: "ix://agent-ix/conformance/type/Millis",
	Node: "ix://agent-ix/conformance/type/Node",
	NodeRef: "ix://agent-ix/conformance/type/NodeRef",
	Payload: "ix://agent-ix/conformance/type/Payload",
	Root: "ix://agent-ix/conformance/type/Root",
	Status: "ix://agent-ix/conformance/type/Status",
	Text: "ix://agent-ix/conformance/type/Text",
	TextList: "ix://agent-ix/conformance/type/TextList",
	TextMap: "ix://agent-ix/conformance/type/TextMap",
} as const satisfies Record<ExportedTypeName, string>;

/** The structural kind each exported type was lowered from. */
export const TYPE_KIND = {
	Count: "scalar",
	Millis: "alias",
	Node: "record",
	NodeRef: "reference",
	Payload: "union",
	Root: "record",
	Status: "enum",
	Text: "scalar",
	TextList: "sequence",
	TextMap: "map",
} as const satisfies Record<ExportedTypeName, string>;

/** The namespaced roles each exported type declares, in document order. */
export const TYPE_ROLES = {
	Count: [],
	Millis: [],
	Node: ["agent-ix:entity"],
	NodeRef: [],
	Payload: [],
	Root: ["agent-ix:entity", "agent-ix:aggregate"],
	Status: ["agent-ix:state"],
	Text: ["agent-ix:value"],
	TextList: [],
	TextMap: [],
} as const satisfies Record<ExportedTypeName, readonly string[]>;

/**
 * The unknown-member policy each exported type declares.
 *
 * It is carried for all eight kinds, including the seven on which it has no
 * validation effect, because it is contract data the document states and this
 * package declares nothing dropped.
 */
export const TYPE_UNKNOWN_POLICY = {
	Count: "reject",
	Millis: "reject",
	Node: "reject",
	NodeRef: "reject",
	Payload: "surface",
	Root: "reject",
	Status: "reject",
	Text: "reject",
	TextList: "reject",
	TextMap: "preserve",
} as const satisfies Record<ExportedTypeName, string>;

/**
 * The names of the fields that tell an entity's instances apart, in declared
 * order. A type that is not an entity has no entry.
 */
export const TYPE_IDENTITY_FIELDS = {} as const satisfies Partial<
	Record<ExportedTypeName, readonly string[]>
>;

/** The extensions each exported type declares. */
export const TYPE_EXTENSIONS = {
	Count: [],
	Millis: [],
	Node: [],
	NodeRef: [],
	Payload: [],
	Root: [],
	Status: [],
	Text: [],
	TextList: [],
	TextMap: [],
} as const satisfies Record<ExportedTypeName, readonly ExtensionDescriptor[]>;

/** The relationships each exported type declares; empty where it declares none. */
export const TYPE_RELATIONSHIPS = {
	Count: [],
	Millis: [],
	Node: [
		{
			identity: "ix://agent-ix/conformance/relationship/node-references-node",
			verb: "references",
			category: "dependency",
			composite: false,
			target: "ix://agent-ix/conformance/type/Node",
			lower: 0,
			upper: null,
		},
	],
	NodeRef: [],
	Payload: [],
	Root: [
		{
			identity: "ix://agent-ix/conformance/relationship/root-contains-node",
			verb: "contains",
			category: "structural",
			composite: true,
			target: "ix://agent-ix/conformance/type/Node",
			lower: 1,
			upper: null,
		},
	],
	Status: [],
	Text: [],
	TextList: [],
	TextMap: [],
} as const satisfies Record<
	ExportedTypeName,
	readonly RelationshipDescriptor[]
>;

/** The semantic identity of each exported field. */
export const FIELD_IDENTITY = {
	"Node.attrs": "ix://agent-ix/conformance/field/node-attrs",
	"Node.children": "ix://agent-ix/conformance/field/node-children",
	"Node.elapsed": "ix://agent-ix/conformance/field/node-elapsed",
	"Node.id": "ix://agent-ix/conformance/field/node-id",
	"Node.label": "ix://agent-ix/conformance/field/node-label",
	"Node.payload": "ix://agent-ix/conformance/field/node-payload",
	"Node.status": "ix://agent-ix/conformance/field/node-status",
	"Node.tags": "ix://agent-ix/conformance/field/node-tags",
	"Root.name": "ix://agent-ix/conformance/field/root-name",
	"Root.node": "ix://agent-ix/conformance/field/root-node",
} as const satisfies Record<ExportedFieldKey, string>;

/** The extensions each exported field declares. */
export const FIELD_EXTENSIONS = {
	"Node.attrs": [],
	"Node.children": [],
	"Node.elapsed": [],
	"Node.id": [],
	"Node.label": [],
	"Node.payload": [],
	"Node.status": [],
	"Node.tags": [],
	"Root.name": [],
	"Root.node": [],
} as const satisfies Record<ExportedFieldKey, readonly ExtensionDescriptor[]>;

/** The unit each declaring field carries. A field declaring none has no entry. */
export const FIELD_UNIT = {
	"Node.elapsed": "ms",
} as const satisfies Partial<Record<ExportedFieldKey, string>>;

/** The extensions the document declares at its top level. */
export const DOCUMENT_EXTENSIONS = [
	{
		identity: "ix://agent-ix/conformance/ext/doc",
		version: "1.0.0",
		required: false,
		capability: "documentation",
		payload: {
			text: "conformance base",
		},
	},
] as const satisfies readonly ExtensionDescriptor[];

/** The occurrences the document carries; empty where it carries none. */
export const OCCURRENCES = [
	{
		identity: "ix://agent-ix/conformance/occurrence/root-1",
		definition: "ix://agent-ix/conformance/type/Root",
		observedAt: "2026-01-01T00:00:00Z",
		value: {
			name: "root",
			node: "ix://agent-ix/conformance/type/Node",
		},
	},
] as const satisfies readonly OccurrenceDescriptor[];

/**
 * The operations each type declares, as data.
 *
 * No executable function is generated for an operation. The generated surface
 * is data, and rendering an operation as a readonly descriptor is not the
 * degradation `contracts-v1.md` prohibits — that is a fall back to `any`, a
 * generic map, or an empty model, and this is none of those.
 */
export const TYPE_OPERATIONS = {
	Count: [],
	Millis: [],
	Node: [],
	NodeRef: [],
	Payload: [],
	Root: [
		{
			identity: "ix://agent-ix/conformance/operation/root-resize",
			name: "resize",
			params: [
				{
					identity: "ix://agent-ix/conformance/field/root-resize-size",
					name: "size",
					typeRef: "ix://agent-ix/conformance/type/Count",
					optional: false,
					nullable: false,
					collection: false,
					lower: 1,
					upper: 1,
				},
			],
			returns: {
				typeRef: "ix://agent-ix/conformance/type/Node",
				nullable: false,
				lower: 1,
				upper: 1,
			},
			pre: ["size-non-negative"],
			post: ["node-returned"],
		},
	],
	Status: [],
	Text: [],
	TextList: [],
	TextMap: [],
} as const satisfies Record<ExportedTypeName, readonly OperationDescriptor[]>;

/**
 * The clauses each type declares, with their text carried opaquely.
 *
 * The text is never parsed here: `agent-ix/quire-contract-ir#52` owns clause
 * semantics and the IR itself carries the text without parsing it.
 */
export const TYPE_CLAUSES = {
	Count: [],
	Millis: [],
	Node: [],
	NodeRef: [],
	Payload: [],
	Root: [
		{
			identity: "ix://agent-ix/conformance/clause/root-size-non-negative",
			language: "ocl",
			clauseId: "size-non-negative",
			text: "size >= 0",
			sourceSpan: {
				path: "model/root.tsp",
				startLine: 9,
				startColumn: 3,
			},
		},
		{
			identity: "ix://agent-ix/conformance/clause/root-node-returned",
			language: "ocl",
			clauseId: "node-returned",
			text: "result.oclIsKindOf(Node)",
			sourceSpan: {
				path: "model/root.tsp",
				startLine: 10,
				startColumn: 3,
			},
		},
	],
	Status: [],
	Text: [],
	TextList: [],
	TextMap: [],
} as const satisfies Record<ExportedTypeName, readonly ClauseDescriptor[]>;

/** The enum and union members, including their semantic identities. */
export const TYPE_VARIANTS = {
	Count: [],
	Millis: [],
	Node: [],
	NodeRef: [],
	Payload: [
		{
			identity: "ix://agent-ix/conformance/variant/payload-count",
			name: "count",
			payloadType: "ix://agent-ix/conformance/type/Count",
		},
		{
			identity: "ix://agent-ix/conformance/variant/payload-text",
			name: "text",
			payloadType: "ix://agent-ix/conformance/type/Text",
		},
	],
	Root: [],
	Status: [
		{
			identity: "ix://agent-ix/conformance/variant/status-draft",
			name: "draft",
			payloadType: "",
		},
		{
			identity: "ix://agent-ix/conformance/variant/status-final",
			name: "final",
			payloadType: "",
		},
	],
	Text: [],
	TextList: [],
	TextMap: [],
} as const satisfies Record<ExportedTypeName, readonly VariantDescriptor[]>;

/** The constraints each type carries, including their semantic identities. */
export const TYPE_CONSTRAINTS = {
	Count: [
		{
			identity: "ix://agent-ix/conformance/constraint/count-min",
			keyword: "min",
			appliesTo: "ix://agent-ix/conformance/type/Count",
			diagnosticCode: "agent-ix.conformance.COUNT_MIN",
			operands: {
				value: 0,
			},
		},
	],
	Millis: [],
	Node: [],
	NodeRef: [],
	Payload: [],
	Root: [],
	Status: [],
	Text: [
		{
			identity: "ix://agent-ix/conformance/constraint/text-min-length",
			keyword: "minLength",
			appliesTo: "ix://agent-ix/conformance/type/Text",
			diagnosticCode: "agent-ix.conformance.TEXT_MIN_LENGTH",
			operands: {
				value: 1,
			},
		},
	],
	TextList: [],
	TextMap: [],
} as const satisfies Record<ExportedTypeName, readonly ConstraintDescriptor[]>;

/**
 * The declared default of each exported field.
 *
 * A `representation` or `migration` default appears here even though the
 * generated validator applies only a `semantic` one, so a consumer can see a
 * default the semantic contract declines to substitute.
 */
export const FIELD_DEFAULT = {
	"Node.attrs": { kind: "none", value: null },
	"Node.children": { kind: "none", value: null },
	"Node.elapsed": { kind: "none", value: null },
	"Node.id": { kind: "none", value: null },
	"Node.label": { kind: "none", value: null },
	"Node.payload": { kind: "none", value: null },
	"Node.status": { kind: "semantic", value: "draft" },
	"Node.tags": { kind: "none", value: null },
	"Root.name": { kind: "none", value: null },
	"Root.node": { kind: "none", value: null },
} as const satisfies Record<ExportedFieldKey, DefaultDescriptor>;
