/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Generated by the Agent IX TypeScript semantic backend. Do not edit.
 * backend: ix://agent-ix/filament-core-data/backend/typescript@0.1.0
 * contract: 2.0.0
 * package: agent-ix/conformance@1.0.0
 * fingerprint: sha256:cf2742a429baf7170b0a9deec5d7d2825def47e9b117c3b7ca42c39338f6b888
 */

export type {
	Count,
	Millis,
	Node,
	NodeRef,
	Payload,
	Root,
	Status,
	Text,
	TextList,
	TextMap,
} from "./types.js";

export {
	NodeRefOf,
	UNION_DISCRIMINANT,
} from "./types.js";

export {
	validateCount,
	validateMillis,
	validateNode,
	validateNodeRef,
	validatePayload,
	validateRoot,
	validateStatus,
	validateText,
	validateTextList,
	validateTextMap,
} from "./validators.js";

export type {
	StructuralCode,
	ValidationError,
	ValidationResult,
} from "./errors.js";

export {
	MAX_VALIDATION_DEPTH,
	PRESERVED_MEMBER,
	VALIDATION_CODES,
} from "./errors.js";

export type {
	ClauseDescriptor,
	ConstraintDescriptor,
	DefaultDescriptor,
	ExportedFieldKey,
	ExportedTypeName,
	ExtensionDescriptor,
	FieldDescriptor,
	OccurrenceDescriptor,
	OperationDescriptor,
	RelationshipDescriptor,
	VariantDescriptor,
} from "./identity.js";

export {
	DOCUMENT_EXTENSIONS,
	FIELD_DEFAULT,
	FIELD_EXTENSIONS,
	FIELD_IDENTITY,
	FIELD_UNIT,
	OCCURRENCES,
	TYPE_CLAUSES,
	TYPE_CONSTRAINTS,
	TYPE_EXTENSIONS,
	TYPE_IDENTITY,
	TYPE_IDENTITY_FIELDS,
	TYPE_KIND,
	TYPE_OPERATIONS,
	TYPE_RELATIONSHIPS,
	TYPE_ROLES,
	TYPE_UNKNOWN_POLICY,
	TYPE_VARIANTS,
} from "./identity.js";

export { PROVENANCE } from "./provenance.js";
