/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Generated by the Agent IX TypeScript semantic backend. Do not edit.
 * backend: ix://agent-ix/filament-core-data/backend/typescript@0.1.0
 * contract: 2.0.0
 * package: agent-ix/conformance@1.0.0
 * fingerprint: sha256:cf2742a429baf7170b0a9deec5d7d2825def47e9b117c3b7ca42c39338f6b888
 */

/**
 * The provenance of the semantic document this package was generated from.
 *
 * Every value here is copied from the document or computed from it. There is no
 * generation timestamp, no build date, no hostname, no machine identifier, no
 * user name, no user id, no home directory, no working directory, no absolute
 * path, no tool path, no interpreter path and no environment variable value:
 * each of those is a determinism leak, and generating this package twice at
 * different times produces identical bytes because none of them is read.
 *
 * An occurrence's `observedAt` is the one timestamp a generated package
 * carries, and it is contract data the document's author wrote. It is declared
 * in `identity.ts`, not here.
 */

/** The document's provenance and the fingerprint of its normalized form. */
export const PROVENANCE = {
	contractVersion: "2.0.0",
	sourceIdentity: "ix://agent-ix/filament-core-data/source/typespec",
	sourceVersion: "1.0.0",
	sourceDialect: "typespec",
	sourceDigest:
		"sha256:0000000000000000000000000000000000000000000000000000000000000000",
	packageIdentity: "agent-ix/conformance",
	packageVersion: "1.0.0",
	packageManifestDigest:
		"sha256:1111111111111111111111111111111111111111111111111111111111111111",
	packageMappingVersions: ["1.0.0"],
	packageProfileVersions: ["1.0.0"],
	packageLockDigest:
		"sha256:2222222222222222222222222222222222222222222222222222222222222222",
	fingerprint:
		"sha256:cf2742a429baf7170b0a9deec5d7d2825def47e9b117c3b7ca42c39338f6b888",
	backendIdentity: "ix://agent-ix/filament-core-data/backend/typescript",
	backendVersion: "0.1.0",
} as const;
