/**
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Generated by the Agent IX TypeScript semantic backend. Do not edit.
 * backend: ix://agent-ix/filament-core-data/backend/typescript@0.1.0
 * contract: 2.0.0
 * package: agent-ix/conformance@1.0.0
 * fingerprint: sha256:cf2742a429baf7170b0a9deec5d7d2825def47e9b117c3b7ca42c39338f6b888
 */

/**
 * The property that discriminates every generated union.
 * Exported as one constant so that a `switch` over it narrows the default arm to `never`, and so that a ruling on agent-ix/filament-core-data#58 — which records that the published contract states no JSON wire form for a discriminated union — moves one declaration rather than every union.
 */
export const UNION_DISCRIMINANT = "kind";

export type Count = number;

export type Millis = Count;

export interface Node {
	readonly attrs?: TextMap;
	readonly children?: readonly NodeRef[];
	/**
	 * Unit: ms.
	 */
	readonly elapsed: Millis;
	readonly id: Text;
	readonly label?: Text | null;
	readonly payload?: Payload;
	/**
	 * Default (semantic): "draft".
	 */
	readonly status: Status;
	readonly tags?: TextList;
}

/**
 * An opaque reference to `ix://agent-ix/conformance/type/Node`. Construct one with `NodeRefOf`; a plain string is not assignable.
 */
declare const NodeRefBrand: unique symbol;
export type NodeRef = string & { readonly [NodeRefBrand]: never };
function NodeRefIs(value: string): value is NodeRef {
	return typeof value === "string";
}
export function NodeRefOf(value: string): NodeRef {
	if (NodeRefIs(value)) return value;
	throw new Error("unreachable: every string brands as NodeRef");
}

export type Payload =
	| { readonly kind: "count"; readonly value: Count }
	| { readonly kind: "text"; readonly value: Text };

export interface Root {
	readonly name: Text;
	readonly node: NodeRef;
}

export type Status = "draft" | "final";

export type Text = string;

export type TextList = readonly Text[];

export type TextMap = {
	readonly [key: string]: Text;
};
