/**
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * Generated by the Agent IX TypeScript semantic backend. Do not edit.
 * backend: ix://agent-ix/filament-core-data/backend/typescript@0.1.0
 * contract: 1.1.0
 * package: agent-ix/conformance@1.0.0
 * fingerprint: sha256:e2f0f9228011b4d10fac90ac6835f823bc07ba556c2ad532ba5e1a0327d7380a
 */

/**
 * Runtime validators, one per exported type.
 *
 * Each validator is a pure function of its argument. It reads no clock, no
 * environment variable, no file and no socket; it imports nothing outside this
 * package; it never throws, whatever it is handed; and it reports every failure
 * it finds rather than stopping at the first.
 *
 * The narrowing from `unknown` to a generated type happens in exactly one
 * construct — a user-defined type predicate — because this package contains no
 * type assertion. A `prepare` pass builds the value the caller receives, with
 * semantic defaults applied and undeclared members separated; the predicate
 * then decides that value and narrows it.
 */

import {
	VALIDATION_CODES as CODES,
	MAX_VALIDATION_DEPTH,
	codePointLength,
	copyAccessor,
	fail,
	isPlainObject,
	isUniqueCollection,
	join,
	ownKeys,
	ownMember,
	sortErrors,
} from "./errors.js";
import type { ValidationError, ValidationResult } from "./errors.js";
import type {
	Count,
	Millis,
	Node,
	NodeRef,
	Payload,
	Root,
	Status,
	Text,
	TextList,
	TextMap,
} from "./types.js";

function prepareCount(value: unknown, depth: number): unknown {
	if (depth > MAX_VALIDATION_DEPTH) return value;
	return value;
}

function checkCount(
	candidate: unknown,
	pointer: string,
	errors: ValidationError[],
	_surfaced: ValidationError[],
	depth: number,
): candidate is Count {
	const before = errors.length;
	if (depth > MAX_VALIDATION_DEPTH) {
		fail(
			errors,
			pointer,
			CODES.DEPTH_LIMIT_EXCEEDED,
			"the value nests past the declared bound",
		);
		return false;
	}
	if (!(typeof candidate === "number")) {
		fail(errors, pointer, CODES.NOT_A_NUMBER, "the value is of the wrong type");
		return false;
	}
	if (Number.isNaN(candidate)) {
		fail(errors, pointer, CODES.NOT_A_NUMBER_VALUE, "the value is NaN");
		return false;
	}
	if (!Number.isFinite(candidate)) {
		fail(errors, pointer, CODES.NOT_FINITE, "the value is not finite");
		return false;
	}
	if (!Number.isInteger(candidate)) {
		fail(errors, pointer, CODES.NOT_AN_INTEGER, "the value is not an integer");
		return false;
	}
	if (!Number.isSafeInteger(candidate)) {
		fail(
			errors,
			pointer,
			CODES.INTEGER_OUT_OF_SAFE_RANGE,
			"the magnitude exceeds Number.MAX_SAFE_INTEGER",
		);
		return false;
	}
	if (!(candidate >= 0)) {
		fail(
			errors,
			pointer,
			"agent-ix.conformance.COUNT_MIN",
			"the min constraint ix://agent-ix/conformance/constraint/count-min is not satisfied",
		);
	}
	return errors.length === before;
}

/** Decide an untrusted value against `ix://agent-ix/conformance/type/Count`. */
export function validateCount(input: unknown): ValidationResult<Count> {
	const errors: ValidationError[] = [];
	const surfaced: ValidationError[] = [];
	const value = prepareCount(input, 0);
	if (checkCount(value, "", errors, surfaced, 0)) {
		return { ok: true, value, surfaced: sortErrors(surfaced) };
	}
	return { ok: false, errors: sortErrors(errors) };
}

function prepareMillis(value: unknown, depth: number): unknown {
	if (depth > MAX_VALIDATION_DEPTH) return value;
	return prepareCount(value, depth + 1);
}

function checkMillis(
	candidate: unknown,
	pointer: string,
	errors: ValidationError[],
	surfaced: ValidationError[],
	depth: number,
): candidate is Millis {
	const before = errors.length;
	if (depth > MAX_VALIDATION_DEPTH) {
		fail(
			errors,
			pointer,
			CODES.DEPTH_LIMIT_EXCEEDED,
			"the value nests past the declared bound",
		);
		return false;
	}
	if (checkCount(candidate, pointer, errors, surfaced, depth + 1)) {
		// The target declares every constraint.
	}
	return errors.length === before;
}

/** Decide an untrusted value against `ix://agent-ix/conformance/type/Millis`. */
export function validateMillis(input: unknown): ValidationResult<Millis> {
	const errors: ValidationError[] = [];
	const surfaced: ValidationError[] = [];
	const value = prepareMillis(input, 0);
	if (checkMillis(value, "", errors, surfaced, 0)) {
		return { ok: true, value, surfaced: sortErrors(surfaced) };
	}
	return { ok: false, errors: sortErrors(errors) };
}

function prepareNode(value: unknown, depth: number): unknown {
	if (depth > MAX_VALIDATION_DEPTH) return value;
	if (!isPlainObject(value)) return value;
	const out: Record<string, unknown> = Object.create(null);
	let accessor = false;
	{
		const member = ownMember(value, "attrs");
		if (member.state === "value") {
			out["attrs"] =
				member.value === null
					? member.value
					: prepareTextMap(member.value, depth + 1);
		} else if (member.state === "accessor") {
			copyAccessor(out, value, "attrs");
			accessor = true;
		}
	}
	{
		const member = ownMember(value, "children");
		if (member.state === "value") {
			out["children"] = Array.isArray(member.value)
				? member.value.map((item) => prepareNodeRef(item, depth + 1))
				: member.value;
		} else if (member.state === "accessor") {
			copyAccessor(out, value, "children");
			accessor = true;
		}
	}
	{
		const member = ownMember(value, "elapsed");
		if (member.state === "value") {
			out["elapsed"] =
				member.value === null
					? member.value
					: prepareMillis(member.value, depth + 1);
		} else if (member.state === "accessor") {
			copyAccessor(out, value, "elapsed");
			accessor = true;
		}
	}
	{
		const member = ownMember(value, "id");
		if (member.state === "value") {
			out["id"] =
				member.value === null
					? member.value
					: prepareText(member.value, depth + 1);
		} else if (member.state === "accessor") {
			copyAccessor(out, value, "id");
			accessor = true;
		}
	}
	{
		const member = ownMember(value, "label");
		if (member.state === "value") {
			out["label"] =
				member.value === null
					? member.value
					: prepareText(member.value, depth + 1);
		} else if (member.state === "accessor") {
			copyAccessor(out, value, "label");
			accessor = true;
		}
	}
	{
		const member = ownMember(value, "payload");
		if (member.state === "value") {
			out["payload"] =
				member.value === null
					? member.value
					: preparePayload(member.value, depth + 1);
		} else if (member.state === "accessor") {
			copyAccessor(out, value, "payload");
			accessor = true;
		}
	}
	{
		const member = ownMember(value, "status");
		if (member.state === "value") {
			out["status"] =
				member.value === null
					? member.value
					: prepareStatus(member.value, depth + 1);
		} else if (member.state === "absent") {
			out["status"] = "draft";
		} else if (member.state === "accessor") {
			copyAccessor(out, value, "status");
			accessor = true;
		}
	}
	{
		const member = ownMember(value, "tags");
		if (member.state === "value") {
			out["tags"] =
				member.value === null
					? member.value
					: prepareTextList(member.value, depth + 1);
		} else if (member.state === "accessor") {
			copyAccessor(out, value, "tags");
			accessor = true;
		}
	}
	const declared: readonly string[] = [
		"attrs",
		"children",
		"elapsed",
		"id",
		"label",
		"payload",
		"status",
		"tags",
	];
	for (const key of ownKeys(value)) {
		if (declared.includes(key)) continue;
		const member = ownMember(value, key);
		if (member.state !== "value") continue;
		out[key] = member.value;
	}
	return accessor ? out : { ...out };
}

function checkNode(
	candidate: unknown,
	pointer: string,
	errors: ValidationError[],
	surfaced: ValidationError[],
	depth: number,
): candidate is Node {
	const before = errors.length;
	if (depth > MAX_VALIDATION_DEPTH) {
		fail(
			errors,
			pointer,
			CODES.DEPTH_LIMIT_EXCEEDED,
			"the value nests past the declared bound",
		);
		return false;
	}
	if (!isPlainObject(candidate)) {
		fail(errors, pointer, CODES.NOT_AN_OBJECT, "the value is not an object");
		return false;
	}
	{
		const member = ownMember(candidate, "attrs");
		const at = join(pointer, "attrs");
		if (member.state === "accessor") {
			fail(
				errors,
				at,
				CODES.ACCESSOR_MEMBER,
				"the member is an accessor and is not read",
			);
		} else if (member.state === "absent") {
			// An absent optional property is accepted.
		} else if (member.value === undefined) {
			fail(
				errors,
				at,
				CODES.EXPLICIT_UNDEFINED,
				"the property is present with the value undefined",
			);
		} else if (member.value === null) {
			fail(
				errors,
				at,
				CODES.NULL_NOT_PERMITTED,
				"the property is null and the field is not nullable",
			);
		} else {
			checkTextMap(member.value, at, errors, surfaced, depth + 1);
		}
	}
	{
		const member = ownMember(candidate, "children");
		const at = join(pointer, "children");
		if (member.state === "accessor") {
			fail(
				errors,
				at,
				CODES.ACCESSOR_MEMBER,
				"the member is an accessor and is not read",
			);
		} else if (member.state === "absent") {
			// An absent optional property is accepted.
		} else if (member.value === undefined) {
			fail(
				errors,
				at,
				CODES.EXPLICIT_UNDEFINED,
				"the property is present with the value undefined",
			);
		} else if (member.value === null) {
			fail(
				errors,
				at,
				CODES.NULL_NOT_PERMITTED,
				"the property is null and the field is not nullable",
			);
		} else {
			if (!Array.isArray(member.value)) {
				fail(errors, at, CODES.NOT_AN_ARRAY, "the value is not an array");
			} else {
				if (!isUniqueCollection(member.value)) {
					fail(
						errors,
						at,
						CODES.COLLECTION_NOT_UNIQUE,
						"two members share a canonical form",
					);
				}
				for (let index = 0; index < member.value.length; index += 1) {
					checkNodeRef(
						member.value[index],
						join(at, String(index)),
						errors,
						surfaced,
						depth + 1,
					);
				}
			}
		}
	}
	{
		const member = ownMember(candidate, "elapsed");
		const at = join(pointer, "elapsed");
		if (member.state === "accessor") {
			fail(
				errors,
				at,
				CODES.ACCESSOR_MEMBER,
				"the member is an accessor and is not read",
			);
		} else if (member.state === "absent") {
			fail(errors, at, CODES.MISSING_REQUIRED, "the property is absent");
		} else if (member.value === undefined) {
			fail(
				errors,
				at,
				CODES.EXPLICIT_UNDEFINED,
				"the property is present with the value undefined",
			);
		} else if (member.value === null) {
			fail(
				errors,
				at,
				CODES.NULL_NOT_PERMITTED,
				"the property is null and the field is not nullable",
			);
		} else {
			checkMillis(member.value, at, errors, surfaced, depth + 1);
		}
	}
	{
		const member = ownMember(candidate, "id");
		const at = join(pointer, "id");
		if (member.state === "accessor") {
			fail(
				errors,
				at,
				CODES.ACCESSOR_MEMBER,
				"the member is an accessor and is not read",
			);
		} else if (member.state === "absent") {
			fail(errors, at, CODES.MISSING_REQUIRED, "the property is absent");
		} else if (member.value === undefined) {
			fail(
				errors,
				at,
				CODES.EXPLICIT_UNDEFINED,
				"the property is present with the value undefined",
			);
		} else if (member.value === null) {
			fail(
				errors,
				at,
				CODES.NULL_NOT_PERMITTED,
				"the property is null and the field is not nullable",
			);
		} else {
			checkText(member.value, at, errors, surfaced, depth + 1);
		}
	}
	{
		const member = ownMember(candidate, "label");
		const at = join(pointer, "label");
		if (member.state === "accessor") {
			fail(
				errors,
				at,
				CODES.ACCESSOR_MEMBER,
				"the member is an accessor and is not read",
			);
		} else if (member.state === "absent") {
			// An absent optional property is accepted.
		} else if (member.value === undefined) {
			fail(
				errors,
				at,
				CODES.EXPLICIT_UNDEFINED,
				"the property is present with the value undefined",
			);
		} else if (member.value === null) {
			// A null value is accepted: the field is nullable.
		} else {
			checkText(member.value, at, errors, surfaced, depth + 1);
		}
	}
	{
		const member = ownMember(candidate, "payload");
		const at = join(pointer, "payload");
		if (member.state === "accessor") {
			fail(
				errors,
				at,
				CODES.ACCESSOR_MEMBER,
				"the member is an accessor and is not read",
			);
		} else if (member.state === "absent") {
			// An absent optional property is accepted.
		} else if (member.value === undefined) {
			fail(
				errors,
				at,
				CODES.EXPLICIT_UNDEFINED,
				"the property is present with the value undefined",
			);
		} else if (member.value === null) {
			fail(
				errors,
				at,
				CODES.NULL_NOT_PERMITTED,
				"the property is null and the field is not nullable",
			);
		} else {
			checkPayload(member.value, at, errors, surfaced, depth + 1);
		}
	}
	{
		const member = ownMember(candidate, "status");
		const at = join(pointer, "status");
		if (member.state === "accessor") {
			fail(
				errors,
				at,
				CODES.ACCESSOR_MEMBER,
				"the member is an accessor and is not read",
			);
		} else if (member.state === "absent") {
			fail(errors, at, CODES.MISSING_REQUIRED, "the property is absent");
		} else if (member.value === undefined) {
			fail(
				errors,
				at,
				CODES.EXPLICIT_UNDEFINED,
				"the property is present with the value undefined",
			);
		} else if (member.value === null) {
			fail(
				errors,
				at,
				CODES.NULL_NOT_PERMITTED,
				"the property is null and the field is not nullable",
			);
		} else {
			checkStatus(member.value, at, errors, surfaced, depth + 1);
		}
	}
	{
		const member = ownMember(candidate, "tags");
		const at = join(pointer, "tags");
		if (member.state === "accessor") {
			fail(
				errors,
				at,
				CODES.ACCESSOR_MEMBER,
				"the member is an accessor and is not read",
			);
		} else if (member.state === "absent") {
			// An absent optional property is accepted.
		} else if (member.value === undefined) {
			fail(
				errors,
				at,
				CODES.EXPLICIT_UNDEFINED,
				"the property is present with the value undefined",
			);
		} else if (member.value === null) {
			fail(
				errors,
				at,
				CODES.NULL_NOT_PERMITTED,
				"the property is null and the field is not nullable",
			);
		} else {
			checkTextList(member.value, at, errors, surfaced, depth + 1);
		}
	}
	const declared: readonly string[] = [
		"attrs",
		"children",
		"elapsed",
		"id",
		"label",
		"payload",
		"status",
		"tags",
	];
	for (const key of ownKeys(candidate)) {
		if (declared.includes(key)) continue;
		fail(
			errors,
			join(pointer, key),
			CODES.UNKNOWN_MEMBER,
			"the member is not declared and this record rejects unknown members",
		);
	}
	return errors.length === before;
}

/** Decide an untrusted value against `ix://agent-ix/conformance/type/Node`. */
export function validateNode(input: unknown): ValidationResult<Node> {
	const errors: ValidationError[] = [];
	const surfaced: ValidationError[] = [];
	const value = prepareNode(input, 0);
	if (checkNode(value, "", errors, surfaced, 0)) {
		return { ok: true, value, surfaced: sortErrors(surfaced) };
	}
	return { ok: false, errors: sortErrors(errors) };
}

function prepareNodeRef(value: unknown, depth: number): unknown {
	if (depth > MAX_VALIDATION_DEPTH) return value;
	return value;
}

function checkNodeRef(
	candidate: unknown,
	pointer: string,
	errors: ValidationError[],
	_surfaced: ValidationError[],
	depth: number,
): candidate is NodeRef {
	const before = errors.length;
	if (depth > MAX_VALIDATION_DEPTH) {
		fail(
			errors,
			pointer,
			CODES.DEPTH_LIMIT_EXCEEDED,
			"the value nests past the declared bound",
		);
		return false;
	}
	if (typeof candidate !== "string") {
		fail(
			errors,
			pointer,
			CODES.NOT_A_STRING,
			"a reference is carried as a string",
		);
		return false;
	}
	return errors.length === before;
}

/** Decide an untrusted value against `ix://agent-ix/conformance/type/NodeRef`. */
export function validateNodeRef(input: unknown): ValidationResult<NodeRef> {
	const errors: ValidationError[] = [];
	const surfaced: ValidationError[] = [];
	const value = prepareNodeRef(input, 0);
	if (checkNodeRef(value, "", errors, surfaced, 0)) {
		return { ok: true, value, surfaced: sortErrors(surfaced) };
	}
	return { ok: false, errors: sortErrors(errors) };
}

function preparePayload(value: unknown, depth: number): unknown {
	if (depth > MAX_VALIDATION_DEPTH) return value;
	if (!isPlainObject(value)) return value;
	const tag = ownMember(value, "kind");
	const payload = ownMember(value, "value");
	if (tag.state !== "value" || payload.state !== "value") return value;
	switch (tag.value) {
		case "count":
			return { ...value, value: prepareCount(payload.value, depth + 1) };
		case "text":
			return { ...value, value: prepareText(payload.value, depth + 1) };
		default:
			return value;
	}
}

function checkPayload(
	candidate: unknown,
	pointer: string,
	errors: ValidationError[],
	surfaced: ValidationError[],
	depth: number,
): candidate is Payload {
	const before = errors.length;
	if (depth > MAX_VALIDATION_DEPTH) {
		fail(
			errors,
			pointer,
			CODES.DEPTH_LIMIT_EXCEEDED,
			"the value nests past the declared bound",
		);
		return false;
	}
	if (!isPlainObject(candidate)) {
		fail(errors, pointer, CODES.NOT_AN_OBJECT, "the value is not an object");
		return false;
	}
	const tag = ownMember(candidate, "kind");
	if (tag.state !== "value" || typeof tag.value !== "string") {
		fail(
			errors,
			pointer,
			CODES.MISSING_DISCRIMINANT,
			"the discriminant is absent or is not a string",
		);
		return false;
	}
	switch (tag.value) {
		case "count": {
			const payload = ownMember(candidate, "value");
			if (payload.state !== "value") {
				fail(
					errors,
					join(pointer, "value"),
					CODES.MISSING_REQUIRED,
					"the variant payload is absent",
				);
				break;
			}
			checkCount(
				payload.value,
				join(pointer, "value"),
				errors,
				surfaced,
				depth + 1,
			);
			break;
		}
		case "text": {
			const payload = ownMember(candidate, "value");
			if (payload.state !== "value") {
				fail(
					errors,
					join(pointer, "value"),
					CODES.MISSING_REQUIRED,
					"the variant payload is absent",
				);
				break;
			}
			checkText(
				payload.value,
				join(pointer, "value"),
				errors,
				surfaced,
				depth + 1,
			);
			break;
		}
		default: {
			fail(
				errors,
				pointer,
				CODES.NOT_A_DECLARED_VARIANT,
				"the discriminant names no declared variant",
			);
			break;
		}
	}
	return errors.length === before;
}

/** Decide an untrusted value against `ix://agent-ix/conformance/type/Payload`. */
export function validatePayload(input: unknown): ValidationResult<Payload> {
	const errors: ValidationError[] = [];
	const surfaced: ValidationError[] = [];
	const value = preparePayload(input, 0);
	if (checkPayload(value, "", errors, surfaced, 0)) {
		return { ok: true, value, surfaced: sortErrors(surfaced) };
	}
	return { ok: false, errors: sortErrors(errors) };
}

function prepareRoot(value: unknown, depth: number): unknown {
	if (depth > MAX_VALIDATION_DEPTH) return value;
	if (!isPlainObject(value)) return value;
	const out: Record<string, unknown> = Object.create(null);
	let accessor = false;
	{
		const member = ownMember(value, "name");
		if (member.state === "value") {
			out["name"] =
				member.value === null
					? member.value
					: prepareText(member.value, depth + 1);
		} else if (member.state === "accessor") {
			copyAccessor(out, value, "name");
			accessor = true;
		}
	}
	{
		const member = ownMember(value, "node");
		if (member.state === "value") {
			out["node"] =
				member.value === null
					? member.value
					: prepareNodeRef(member.value, depth + 1);
		} else if (member.state === "accessor") {
			copyAccessor(out, value, "node");
			accessor = true;
		}
	}
	const declared: readonly string[] = ["name", "node"];
	for (const key of ownKeys(value)) {
		if (declared.includes(key)) continue;
		const member = ownMember(value, key);
		if (member.state !== "value") continue;
		out[key] = member.value;
	}
	return accessor ? out : { ...out };
}

function checkRoot(
	candidate: unknown,
	pointer: string,
	errors: ValidationError[],
	surfaced: ValidationError[],
	depth: number,
): candidate is Root {
	const before = errors.length;
	if (depth > MAX_VALIDATION_DEPTH) {
		fail(
			errors,
			pointer,
			CODES.DEPTH_LIMIT_EXCEEDED,
			"the value nests past the declared bound",
		);
		return false;
	}
	if (!isPlainObject(candidate)) {
		fail(errors, pointer, CODES.NOT_AN_OBJECT, "the value is not an object");
		return false;
	}
	{
		const member = ownMember(candidate, "name");
		const at = join(pointer, "name");
		if (member.state === "accessor") {
			fail(
				errors,
				at,
				CODES.ACCESSOR_MEMBER,
				"the member is an accessor and is not read",
			);
		} else if (member.state === "absent") {
			fail(errors, at, CODES.MISSING_REQUIRED, "the property is absent");
		} else if (member.value === undefined) {
			fail(
				errors,
				at,
				CODES.EXPLICIT_UNDEFINED,
				"the property is present with the value undefined",
			);
		} else if (member.value === null) {
			fail(
				errors,
				at,
				CODES.NULL_NOT_PERMITTED,
				"the property is null and the field is not nullable",
			);
		} else {
			checkText(member.value, at, errors, surfaced, depth + 1);
		}
	}
	{
		const member = ownMember(candidate, "node");
		const at = join(pointer, "node");
		if (member.state === "accessor") {
			fail(
				errors,
				at,
				CODES.ACCESSOR_MEMBER,
				"the member is an accessor and is not read",
			);
		} else if (member.state === "absent") {
			fail(errors, at, CODES.MISSING_REQUIRED, "the property is absent");
		} else if (member.value === undefined) {
			fail(
				errors,
				at,
				CODES.EXPLICIT_UNDEFINED,
				"the property is present with the value undefined",
			);
		} else if (member.value === null) {
			fail(
				errors,
				at,
				CODES.NULL_NOT_PERMITTED,
				"the property is null and the field is not nullable",
			);
		} else {
			checkNodeRef(member.value, at, errors, surfaced, depth + 1);
		}
	}
	const declared: readonly string[] = ["name", "node"];
	for (const key of ownKeys(candidate)) {
		if (declared.includes(key)) continue;
		fail(
			errors,
			join(pointer, key),
			CODES.UNKNOWN_MEMBER,
			"the member is not declared and this record rejects unknown members",
		);
	}
	return errors.length === before;
}

/** Decide an untrusted value against `ix://agent-ix/conformance/type/Root`. */
export function validateRoot(input: unknown): ValidationResult<Root> {
	const errors: ValidationError[] = [];
	const surfaced: ValidationError[] = [];
	const value = prepareRoot(input, 0);
	if (checkRoot(value, "", errors, surfaced, 0)) {
		return { ok: true, value, surfaced: sortErrors(surfaced) };
	}
	return { ok: false, errors: sortErrors(errors) };
}

function prepareStatus(value: unknown, depth: number): unknown {
	if (depth > MAX_VALIDATION_DEPTH) return value;
	return value;
}

function checkStatus(
	candidate: unknown,
	pointer: string,
	errors: ValidationError[],
	_surfaced: ValidationError[],
	depth: number,
): candidate is Status {
	const before = errors.length;
	if (depth > MAX_VALIDATION_DEPTH) {
		fail(
			errors,
			pointer,
			CODES.DEPTH_LIMIT_EXCEEDED,
			"the value nests past the declared bound",
		);
		return false;
	}
	if (typeof candidate !== "string") {
		fail(errors, pointer, CODES.NOT_A_STRING, "the value is of the wrong type");
		return false;
	}
	const variants: readonly string[] = ["draft", "final"];
	if (!variants.includes(candidate)) {
		fail(
			errors,
			pointer,
			CODES.NOT_A_DECLARED_VARIANT,
			"the value names no declared variant",
		);
		return false;
	}
	return errors.length === before;
}

/** Decide an untrusted value against `ix://agent-ix/conformance/type/Status`. */
export function validateStatus(input: unknown): ValidationResult<Status> {
	const errors: ValidationError[] = [];
	const surfaced: ValidationError[] = [];
	const value = prepareStatus(input, 0);
	if (checkStatus(value, "", errors, surfaced, 0)) {
		return { ok: true, value, surfaced: sortErrors(surfaced) };
	}
	return { ok: false, errors: sortErrors(errors) };
}

function prepareText(value: unknown, depth: number): unknown {
	if (depth > MAX_VALIDATION_DEPTH) return value;
	return value;
}

function checkText(
	candidate: unknown,
	pointer: string,
	errors: ValidationError[],
	_surfaced: ValidationError[],
	depth: number,
): candidate is Text {
	const before = errors.length;
	if (depth > MAX_VALIDATION_DEPTH) {
		fail(
			errors,
			pointer,
			CODES.DEPTH_LIMIT_EXCEEDED,
			"the value nests past the declared bound",
		);
		return false;
	}
	if (!(typeof candidate === "string")) {
		fail(errors, pointer, CODES.NOT_A_STRING, "the value is of the wrong type");
		return false;
	}
	if (!(codePointLength(candidate) >= 1)) {
		fail(
			errors,
			pointer,
			"agent-ix.conformance.TEXT_MIN_LENGTH",
			"the minLength constraint ix://agent-ix/conformance/constraint/text-min-length is not satisfied",
		);
	}
	return errors.length === before;
}

/** Decide an untrusted value against `ix://agent-ix/conformance/type/Text`. */
export function validateText(input: unknown): ValidationResult<Text> {
	const errors: ValidationError[] = [];
	const surfaced: ValidationError[] = [];
	const value = prepareText(input, 0);
	if (checkText(value, "", errors, surfaced, 0)) {
		return { ok: true, value, surfaced: sortErrors(surfaced) };
	}
	return { ok: false, errors: sortErrors(errors) };
}

function prepareTextList(value: unknown, depth: number): unknown {
	if (depth > MAX_VALIDATION_DEPTH) return value;
	if (!Array.isArray(value)) return value;
	return value.map((member) => prepareText(member, depth + 1));
}

function checkTextList(
	candidate: unknown,
	pointer: string,
	errors: ValidationError[],
	surfaced: ValidationError[],
	depth: number,
): candidate is TextList {
	const before = errors.length;
	if (depth > MAX_VALIDATION_DEPTH) {
		fail(
			errors,
			pointer,
			CODES.DEPTH_LIMIT_EXCEEDED,
			"the value nests past the declared bound",
		);
		return false;
	}
	if (!Array.isArray(candidate)) {
		fail(errors, pointer, CODES.NOT_AN_ARRAY, "the value is not an array");
		return false;
	}
	for (let index = 0; index < candidate.length; index += 1) {
		checkText(
			candidate[index],
			join(pointer, String(index)),
			errors,
			surfaced,
			depth + 1,
		);
	}
	return errors.length === before;
}

/** Decide an untrusted value against `ix://agent-ix/conformance/type/TextList`. */
export function validateTextList(input: unknown): ValidationResult<TextList> {
	const errors: ValidationError[] = [];
	const surfaced: ValidationError[] = [];
	const value = prepareTextList(input, 0);
	if (checkTextList(value, "", errors, surfaced, 0)) {
		return { ok: true, value, surfaced: sortErrors(surfaced) };
	}
	return { ok: false, errors: sortErrors(errors) };
}

function prepareTextMap(value: unknown, depth: number): unknown {
	if (depth > MAX_VALIDATION_DEPTH) return value;
	if (!isPlainObject(value)) return value;
	const out: Record<string, unknown> = Object.create(null);
	let accessor = false;
	for (const key of ownKeys(value)) {
		const member = ownMember(value, key);
		if (member.state === "accessor") {
			copyAccessor(out, value, key);
			accessor = true;
			continue;
		}
		if (member.state !== "value") continue;
		out[key] = prepareText(member.value, depth + 1);
	}
	return accessor ? out : { ...out };
}

function checkTextMap(
	candidate: unknown,
	pointer: string,
	errors: ValidationError[],
	surfaced: ValidationError[],
	depth: number,
): candidate is TextMap {
	const before = errors.length;
	if (depth > MAX_VALIDATION_DEPTH) {
		fail(
			errors,
			pointer,
			CODES.DEPTH_LIMIT_EXCEEDED,
			"the value nests past the declared bound",
		);
		return false;
	}
	if (!isPlainObject(candidate)) {
		fail(errors, pointer, CODES.NOT_AN_OBJECT, "the value is not an object");
		return false;
	}
	for (const key of ownKeys(candidate)) {
		const member = ownMember(candidate, key);
		if (member.state === "accessor") {
			fail(
				errors,
				join(pointer, key),
				CODES.ACCESSOR_MEMBER,
				"the member is an accessor and is not read",
			);
			continue;
		}
		checkText(member.value, join(pointer, key), errors, surfaced, depth + 1);
	}
	return errors.length === before;
}

/** Decide an untrusted value against `ix://agent-ix/conformance/type/TextMap`. */
export function validateTextMap(input: unknown): ValidationResult<TextMap> {
	const errors: ValidationError[] = [];
	const surfaced: ValidationError[] = [];
	const value = prepareTextMap(input, 0);
	if (checkTextMap(value, "", errors, surfaced, 0)) {
		return { ok: true, value, surfaced: sortErrors(surfaced) };
	}
	return { ok: false, errors: sortErrors(errors) };
}
