"""The generated package layout (FR-079).

One package per demonstrated profile, with provenance, a content fingerprint,
a README that says what the family does not carry, and an `__init__.py` whose
`__all__` is sorted and complete — so an added type is a visible diff rather
than a re-ordering.

Nothing here is published. The issue #23 safety gate forbids PyPI publication
and backend consumer migration, and no path under this tree reaches a
distribution manifest.
"""

from __future__ import annotations

import argparse
import ast
import json
import shutil
import sys
from typing import Any

from python_backend import ROOT
from python_backend.adapter.jcs import digest, digest_bytes
from python_backend.adapter.prepare import prepare_input_set
from python_backend.adapter.profiles import profile_by_id
from python_backend.adapter.render import render
from python_backend.runner.generate import generate
from python_backend.runner.inspect_source import inspect_generated
from python_backend.runner.qualify import NOT_QUALIFIED, REPORT
from python_backend.runner.toolchain import toolchain

GENERATED = ROOT / "generated"
EXAMPLES = ROOT / "examples"
PUBLISHED = ROOT.parent / "schema" / "semantic" / "v1"

UPSTREAM_ATTRIBUTION = (
    "Generated by datamodel-code-generator (MIT). Copyright (c) 2019 Koudai "
    "Takahashi. The generator is an attributed, pinned third-party dependency; "
    "its licence is preserved and its source is neither vendored nor forked."
)


class LayoutError(RuntimeError):
    """Two documents declare the same type name, or a package cannot be written."""


def _public_symbols(source: str) -> list[str]:
    tree = ast.parse(source)
    names: list[str] = []
    for statement in tree.body:
        if isinstance(statement, ast.ClassDef) and not statement.name.startswith("_"):
            names.append(statement.name)
        elif isinstance(statement, ast.TypeAlias) and isinstance(
            statement.name, ast.Name
        ):
            if not statement.name.id.startswith("_"):
                names.append(statement.name.id)
        elif isinstance(statement, ast.AnnAssign) and isinstance(
            statement.target, ast.Name
        ):
            if not statement.target.id.startswith("_"):
                names.append(statement.target.id)
    return names


def _module_exports(files: dict[str, str]) -> dict[str, list[str]]:
    exports: dict[str, list[str]] = {}
    for name, source in sorted(files.items()):
        if not name.endswith(".py") or name == "__init__.py":
            continue
        exports[name[:-3]] = _public_symbols(source)
    return exports


def collisions(exports: dict[str, list[str]]) -> dict[str, list[str]]:
    """Names more than one module declares.

    Measured, not hypothetical: the pinned generator mints a class from an
    inline enum's *property* name, so two documents that each declare a
    `preservation` enum both emit a `Preservation`, and they are different
    types. A flat namespace cannot hold both, and re-exporting one would hide
    the other silently — which is the failure this package exists to avoid. The
    colliding names stay reachable as `package.<module>.<Name>`, are excluded
    from `__all__`, and are recorded in `PROVENANCE.json` and the README.
    """

    owners: dict[str, list[str]] = {}
    for module, names in exports.items():
        for name in names:
            owners.setdefault(name, []).append(module)
    return {
        name: sorted(modules) for name, modules in owners.items() if len(modules) > 1
    }


def _init_module(exports: dict[str, list[str]]) -> str:
    for module, names in exports.items():
        duplicates = {name for name in names if names.count(name) > 1}
        if duplicates:
            msg = (
                f"module {module!r} declares {sorted(duplicates)} more than once; "
                "one would shadow the other"
            )
            raise LayoutError(msg)

    shared = collisions(exports)
    lines = [
        '"""Generated package. Do not edit: regenerate with',
        "`poetry run python -m python_backend.runner.emit`.",
        "",
        "`__all__` carries every type name exactly one module declares. Names",
        "several modules declare are different types that happen to share a",
        "local name; they are reachable as `<module>.<Name>` and are listed in",
        '`PROVENANCE.json` under `nameCollisions`."""',
        "",
    ]
    for module in sorted(exports):
        names = sorted(name for name in set(exports[module]) if name not in shared)
        if names:
            lines.append(f"from .{module} import {', '.join(names)}")
    lines.append("")
    lines.append("__all__ = [")
    everything = sorted(
        {name for names in exports.values() for name in names} - set(shared)
    )
    lines.extend(f'    "{name}",' for name in everything)
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def _readme(
    profile: dict[str, Any], verdict: dict[str, Any], shared: dict[str, list[str]]
) -> str:
    lost = verdict["lost"] or ["nothing measured as lost"]
    conditions = verdict["conditions"]
    lines = [
        f"# Generated Python package: `{profile['id']}`",
        "",
        f"Output family: `{profile['outputModelType']}`.",
        f"Runtime validation: {profile['runtimeValidation']}.",
        f"Qualification verdict: **{verdict['verdict']}**.",
        "",
        "Generated by the pinned `datamodel-code-generator` through",
        "`python_backend/runner/emit.py`. Do not edit by hand: the tree is",
        "regenerated and byte-compared.",
        "",
        "## What this package does not carry",
        "",
    ]
    lines.extend(f"- `{name}`" for name in lost)
    lines.extend(
        [
            "",
            "Each is recorded in `python_backend/qualification/gaps.json` with a",
            "severity and a disposition. A construct measured as lost and absent",
            "from that register fails the qualification gate.",
            "",
        ]
    )
    if shared:
        lines.append("## Names this package does not re-export at the top level")
        lines.append("")
        lines.append(
            "These names are declared by more than one module and are different"
        )
        lines.append(
            "types. They are reachable as `<module>.<Name>` and are excluded from"
        )
        lines.append("`__all__` rather than silently shadowed.")
        lines.append("")
        lines.extend(
            f"- `{name}` — {', '.join(modules)}"
            for name, modules in sorted(shared.items())
        )
        lines.append("")
    if conditions:
        lines.append("## Conditions this verdict depends on")
        lines.append("")
        lines.extend(f"- {row['condition']} ({row['grounding']})" for row in conditions)
        lines.append("")
    lines.extend(
        [
            "## Licence",
            "",
            "The generated source is AGPL-3.0-only, like the rest of this",
            "repository. The generator is MIT and is attributed in",
            "`PROVENANCE.json`.",
            "",
            "This package is not published. The issue #23 safety gate forbids",
            "PyPI publication and backend consumer migration.",
            "",
        ]
    )
    return "\n".join(lines)


def _content_fingerprint(files: dict[str, str]) -> str:
    return digest(
        {name: files[name] for name in sorted(files) if name != "PROVENANCE.json"}
    )


def build(profile_id: str) -> dict[str, str]:
    profile = profile_by_id(profile_id)
    report = json.loads(REPORT.read_text(encoding="utf-8"))
    verdict = next(row for row in report["verdicts"] if row["profileId"] == profile_id)

    prepared = prepare_input_set(sorted(PUBLISHED.glob("*.schema.json")))
    result = generate(
        prepared,
        profile_id,
        inspect=lambda files, documents: inspect_generated(files, documents, "enforce"),
    )

    files = dict(result.files)
    exports = _module_exports(files)
    shared = collisions(exports)
    files["__init__.py"] = _init_module(exports)
    files["README.md"] = _readme(profile, verdict, shared)

    provenance = {
        "$comment": "Issue #23, FR-079. Regenerated, never hand-edited.",
        "source": {
            "documents": sorted(prepared.documents),
            "inputDigest": result.input_digest,
            "preparation": result.preparation,
        },
        "profile": {"id": profile_id, "digest": result.profile_digest},
        "toolchainFingerprint": result.toolchain_fingerprint,
        "generator": {
            "distribution": toolchain()["generator"]["distribution"],
            "version": toolchain()["generator"]["version"],
            "license": "MIT",
            "attribution": UPSTREAM_ATTRIBUTION,
        },
        "generatedSourceLicense": "AGPL-3.0-only",
        "nameCollisions": collisions(exports),
        "published": False,
        "contentFingerprint": _content_fingerprint(files),
    }
    files["PROVENANCE.json"] = render(provenance)
    return files


def demonstrated() -> list[str]:
    report = json.loads(REPORT.read_text(encoding="utf-8"))
    return [
        row["profileId"]
        for row in report["verdicts"]
        if row["verdict"] != NOT_QUALIFIED
    ]


def _not_qualified_note() -> str:
    report = json.loads(REPORT.read_text(encoding="utf-8"))
    rows = [row for row in report["verdicts"] if row["verdict"] == NOT_QUALIFIED]
    lines = [
        "# Families with no emitted package",
        "",
        "These families were declared, measured, and judged. The absence of a",
        "package is a recorded decision, not an omission.",
        "",
    ]
    for row in rows:
        lines.append(f"## `{row['profileId']}` — {row['verdict']}")
        lines.append("")
        lines.append(f"Output family: `{row['outputModelType']}`.")
        lines.append("")
        lines.append("Constructs it loses:")
        lines.append("")
        lines.extend(f"- `{name}`" for name in row["lost"])
        lines.append("")
    return "\n".join(lines)


def write_all() -> dict[str, str]:
    fingerprints: dict[str, str] = {}
    if GENERATED.exists():
        shutil.rmtree(GENERATED)
    GENERATED.mkdir(parents=True)
    for profile_id in demonstrated():
        files = build(profile_id)
        target = GENERATED / profile_id
        target.mkdir(parents=True)
        for name, text in files.items():
            destination = target / name
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(text, encoding="utf-8")
        fingerprints[profile_id] = _content_fingerprint(files)
    (GENERATED / "NOT-QUALIFIED.md").write_text(_not_qualified_note(), encoding="utf-8")
    (GENERATED / "__init__.py").write_text(
        '"""Generated Python packages, one per demonstrated profile (FR-079).\n\n'
        "Regenerate with `poetry run python -m python_backend.runner.emit`. Not\n"
        'published: the issue #23 safety gate forbids it."""\n',
        encoding="utf-8",
    )
    return fingerprints


def check() -> int:
    failures: list[str] = []
    for profile_id in demonstrated():
        files = build(profile_id)
        target = GENERATED / profile_id
        for name, text in files.items():
            path = target / name
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                failures.append(str(path))
        committed = {
            str(path.relative_to(target)): path.read_text(encoding="utf-8")
            for path in sorted(target.rglob("*"))
            if path.is_file() and "__pycache__" not in path.parts
        }
        for name in committed:
            if name not in files:
                failures.append(f"{target / name} is not regenerated")
    note = GENERATED / "NOT-QUALIFIED.md"
    if not note.exists() or note.read_text(encoding="utf-8") != _not_qualified_note():
        failures.append(str(note))
    if not (GENERATED / "__init__.py").exists():
        failures.append(str(GENERATED / "__init__.py"))
    for failure in failures:
        print(f"{failure} differs from a fresh generation", file=sys.stderr)
    return 1 if failures else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Emit the generated Python packages.")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    if args.check:
        return check()
    fingerprints = write_all()
    for profile_id, fingerprint in fingerprints.items():
        print(f"{profile_id} {fingerprint}")
    _ = digest_bytes
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
