"""The qualification (FR-077).

What each output family retains and what it loses, measured one construct at a
time and then over the whole published set, and recorded as a verdict a later
reader can check against the artefact that produced it.

Every measurement goes through the inspection's *reporting* mode. The enforcing
mode refuses a package that degrades a constraint, and a family that loses
object closure must be measurable rather than suppressed by the very check that
would refuse it.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

from python_backend import ROOT
from python_backend.adapter.prepare import (
    Prepared,
    prepare_documents,
    prepare_input_set,
)
from python_backend.adapter.profiles import load_profiles, profile_digest
from python_backend.adapter.render import render
from python_backend.runner.generate import generate, toolchain_fingerprint
from python_backend.runner.inspect_source import inspect_generated

PROBES = ROOT / "qualification" / "probes"
REPORT = ROOT / "qualification" / "report.json"
GAPS = ROOT / "qualification" / "gaps.json"

# The three verdicts, and no others. A static gate asserts that no other verdict
# word appears in any artefact of this change; the criterion is named in
# `spec/tests.md` rather than here, because a bare requirement id in a comment
# binds to the NEXT symbol and would mint a trace on a constant.
QUALIFIED = "qualified"
CONDITIONAL = "qualified-with-conditions"
NOT_QUALIFIED = "not-qualified"


def probes() -> list[dict[str, Any]]:
    return [
        json.loads(path.read_text(encoding="utf-8"))
        for path in sorted(PROBES.glob("*.json"))
    ]


def _documents(probe: dict[str, Any]) -> dict[str, dict[str, Any]]:
    if "schemas" in probe:
        return dict(probe["schemas"])
    return {"probe.schema.json": probe["schema"]}


def _prepared(probe: dict[str, Any]) -> Prepared:
    return prepare_documents(_documents(probe))


def _detect(detector: dict[str, Any], sources: str) -> bool:
    if detector["kind"] == "regex":
        return re.search(detector["pattern"], sources) is not None
    msg = f"unknown detector kind {detector['kind']!r}"
    raise ValueError(msg)


def measure() -> dict[str, Any]:
    """Measure every probe against every declared profile."""

    families = load_profiles()
    results: dict[str, dict[str, bool]] = {}
    for probe in probes():
        row: dict[str, bool] = {}
        prepared = _prepared(probe)
        for profile in families:
            generated = generate(prepared, profile["id"])
            joined = "\n".join(
                text
                for name, text in sorted(generated.files.items())
                if name.endswith(".py")
            )
            row[profile["id"]] = _detect(probe["detector"], joined)
        results[probe["id"]] = row
    return results


def mismatches(
    measured: dict[str, dict[str, bool]], catalogue: list[dict[str, Any]]
) -> list[tuple[str, str, bool, bool]]:
    """Where a measurement disagrees with a probe's declared expectation.

    The gate reads this, and so does its falsification, so the falsification
    exercises the comparison rather than restating the negation it just built.
    """

    out: list[tuple[str, str, bool, bool]] = []
    for probe in catalogue:
        for profile_id, expected in probe["expected"].items():
            actual = measured[probe["id"]][profile_id]
            if actual != expected:
                out.append((probe["id"], profile_id, expected, actual))
    return out


def _published_set() -> Prepared:
    return prepare_input_set(
        sorted((ROOT.parent / "schema" / "semantic" / "v1").glob("*.schema.json"))
    )


def build() -> tuple[dict[str, Any], dict[str, Any]]:
    families = load_profiles()
    catalogue = {probe["id"]: probe for probe in probes()}
    measured = measure()
    published = _published_set()

    report: dict[str, Any] = {
        "$comment": (
            "Issue #23, FR-077. Generated by `python_backend/runner/qualify.py`; "
            "never hand-edited. Every verdict cites the declared-toolchain "
            "fingerprint and the profile digest that produced it, and the "
            "fingerprint covers the declared pins only — no host-observed "
            "reading enters a byte-compared artefact."
        ),
        "verdicts": [],
    }
    gaps: dict[str, Any] = {
        "$comment": (
            "Issue #23, FR-077. One row per construct and affected family. A "
            "construct measured as lost with no row here fails the gate; "
            "removing a row fails the gate. No row may dispose a gap to a "
            "hand-written generator absent a recorded reviewed P0 decision."
        ),
        "gaps": [],
    }

    for profile in families:
        retained: list[str] = []
        lost: list[str] = []
        for probe_id, row in sorted(measured.items()):
            (retained if row[profile["id"]] else lost).append(probe_id)

        generated = generate(published, profile["id"])
        census = inspect_generated(
            generated.files, published.documents, "report"
        ).census

        conditions: list[dict[str, str]] = []
        if "closure-unevaluated" not in lost:
            conditions.append(
                {
                    "condition": (
                        "the FR-074 preparation pass rewrites"
                        " `unevaluatedProperties`"
                    ),
                    "grounding": (
                        "python_backend/adapter/prepare.py rule"
                        " `unevaluated-properties-to-additional`"
                    ),
                }
            )
        if "default-non-nullable" not in lost:
            conditions.append(
                {
                    "condition": "the profile declares `--strict-nullable`",
                    "grounding": (
                        "python_backend/profiles.json option `--strict-nullable`"
                    ),
                }
            )
        if "constraints-string" not in lost:
            conditions.append(
                {
                    "condition": (
                        "the profile declares `--field-constraints` and"
                        " `--use-annotated`"
                    ),
                    "grounding": (
                        "python_backend/profiles.json options"
                        " `--field-constraints`, `--use-annotated`"
                    ),
                }
            )

        # The verdict rule is stated, not arithmetic. A family is not qualified
        # when it cannot carry the constraint layer at all — the contract's
        # string and numeric constraints are the load-bearing case — because a
        # surface that keeps the shape and drops every bound is a schema-shaped
        # `dict` with better autocomplete. Everything else that loses something
        # is conditional, and the conditions and the losses are both recorded.
        constraint_layer = {"constraints-string", "constraints-numeric"}
        if not lost:
            verdict = QUALIFIED
        elif constraint_layer & set(lost):
            verdict = NOT_QUALIFIED
        else:
            verdict = CONDITIONAL

        report["verdicts"].append(
            {
                "profileId": profile["id"],
                "outputModelType": profile["outputModelType"],
                "runtimeValidation": profile["runtimeValidation"],
                "verdict": verdict,
                "profileDigest": profile_digest(profile),
                "toolchainFingerprint": toolchain_fingerprint(
                    profile, generated.input_digest
                ),
                "retained": retained,
                "lost": lost,
                "conditions": conditions if verdict == CONDITIONAL else [],
                "publishedSetCensus": census,
                "evidence": {
                    "probes": "python_backend/qualification/probes/",
                    "publishedSet": "schema/semantic/v1/*.schema.json",
                },
            }
        )

        for probe_id in lost:
            probe = catalogue[probe_id]
            closable = probe_id in {"closure-unevaluated"}
            gaps["gaps"].append(
                {
                    "construct": probe["construct"],
                    "probe": probe_id,
                    "family": profile["id"],
                    "severity": (
                        "high"
                        if probe_id
                        in {
                            "closure-additional",
                            "closure-unevaluated",
                            "constraints-string",
                            "constraints-numeric",
                            "alias",
                        }
                        else "medium"
                    ),
                    "closableByPreparation": closable,
                    "disposition": (
                        "recorded; the pinned generator does not carry this construct "
                        "into this family and no schema rewrite can add it. Upstream "
                        "is the place to fix it; this repository records the loss."
                    ),
                    "note": probe["note"],
                }
            )

    gaps["gaps"].append(
        {
            "construct": "absent versus null in the Pydantic families",
            "probe": "default-non-nullable",
            "family": "pydantic_v2_basemodel, pydantic_v2_dataclass",
            "severity": "medium",
            "closableByPreparation": False,
            "disposition": (
                "The generator's `--use-missing-sentinel` separates the two, and "
                "against pydantic 2.12.5 it renders `pydantic_core.MISSING` in a "
                "type position that mypy 1.19.1 rejects, which FR-080 forbids "
                "papering over. Recorded rather than adopted; the two obligations "
                "cannot both be met with this toolchain."
            ),
            "note": (
                "An optional non-nullable field renders `T | None = None`, so a "
                "consumer cannot distinguish an omitted member from an explicit null."
            ),
        }
    )
    gaps["gaps"].append(
        {
            "construct": (
                "GAP-011: a `reference` whose target no type, import, or lock"
                " export supplies"
            ),
            "probe": None,
            "family": "all",
            "severity": "medium",
            "closableByPreparation": False,
            "disposition": (
                "Deferred to the program owner, not decided here. "
                "`conformance/contract-gaps.json` GAP-011 records that "
                "`contracts-v1.md` states a resolution rule for relationship "
                "targets and none for a `reference` target, and its own "
                "consequence text says a generated-package backend must decide "
                "whether to emit a type for a reference it cannot resolve. The "
                "profile's `--strict-refs` governs an unresolved JSON Schema "
                "`$ref`, which is a different construct and does not answer it."
            ),
            "note": "Corpus cases REF-001..004 pin the oracle's reading.",
        }
    )
    return report, gaps


def _write(path: Path, document: dict[str, Any]) -> str:
    text = render(document)
    path.write_text(text, encoding="utf-8")
    return text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Measure the Python output families.")
    parser.add_argument(
        "--check", action="store_true", help="fail if a committed artefact differs"
    )
    args = parser.parse_args(argv)

    report, gaps = build()
    if args.check:
        for path, document in ((REPORT, report), (GAPS, gaps)):
            fresh = render(document)
            if not path.exists() or path.read_text(encoding="utf-8") != fresh:
                print(f"{path} differs from a fresh measurement", file=sys.stderr)
                return 1
        return 0
    _write(REPORT, report)
    _write(GAPS, gaps)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
