# generated by datamodel-codegen:
#   filename:  ClauseRef.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from .ClauseLanguage import ClauseLanguage
from .Identifier import Identifier
from .SourceLocus import SourceLocus


class ClauseRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    clauseId: Identifier
    language: ClauseLanguage
    sourceSpan: SourceLocus | None = None
