# generated by datamodel-codegen:
#   filename:  DecimalPolicy.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class DecimalPolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    precision: Annotated[int, Field(ge=1, le=2147483647)]
    scale: Annotated[int, Field(ge=0, le=2147483647)]
