# generated by datamodel-codegen:
#   filename:  DefaultDecl.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict

from .DefaultKind import DefaultKind


class DefaultDecl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: DefaultKind
    value: Any | None = None
