# generated by datamodel-codegen:
#   filename:  EdgeCategory.json

from __future__ import annotations

from enum import StrEnum


class EdgeCategory(StrEnum):
    structural = 'structural'
    behavioral = 'behavioral'
    dataflow = 'dataflow'
    dependency = 'dependency'
    realization = 'realization'
    governance = 'governance'
    traceability = 'traceability'
