# generated by datamodel-codegen:
#   filename:  EnumValue.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from .Identifier import Identifier


class EnumValue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    doc: str | None = None
    value: Identifier
