# generated by datamodel-codegen:
#   filename:  EnumValuesConstraint.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class EnumValuesConstraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    keyword: Literal['enumValues']
    values: Annotated[list[str | float | bool], Field(min_length=1)]
