# generated by datamodel-codegen:
#   filename:  ExclusiveMaxConstraint.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class ExclusiveMaxConstraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    keyword: Literal['exclusiveMax']
    value: float | str
