# generated by datamodel-codegen:
#   filename:  ExclusiveMinConstraint.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class ExclusiveMinConstraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    keyword: Literal['exclusiveMin']
    value: float | str
