# generated by datamodel-codegen:
#   filename:  FieldDecl.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from .ConstraintDecl import ConstraintDecl
from .DefaultDecl import DefaultDecl
from .Identifier import Identifier
from .TypeRef import TypeRef


class FieldDecl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    constraints: list[ConstraintDecl] | None = None
    default: DefaultDecl | None = None
    doc: str | None = None
    identity: bool | None = None
    name: Identifier
    nullable: bool | None = None
    type: TypeRef
