# generated by datamodel-codegen:
#   filename:  Identifier.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel


class Identifier(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='A declaration name: letters, digits, underscore; no leading digit.',
            pattern='^[A-Za-z_][A-Za-z0-9_]*$',
            title='Identifier',
        ),
    ]
