# generated by datamodel-codegen:
#   filename:  KernelScalar.json

from __future__ import annotations

from enum import StrEnum


class KernelScalar(StrEnum):
    UUID = 'UUID'
    Boolean = 'Boolean'
    Integer = 'Integer'
    Decimal = 'Decimal'
    Float32 = 'Float32'
    Float64 = 'Float64'
    String = 'String'
    Timestamp = 'Timestamp'
    Duration = 'Duration'
    Bytes = 'Bytes'
    JsonObject = 'JsonObject'
