# generated by datamodel-codegen:
#   filename:  MaxConstraint.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class MaxConstraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    keyword: Literal['max']
    value: float | str
