# generated by datamodel-codegen:
#   filename:  MinConstraint.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class MinConstraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    keyword: Literal['min']
    value: float | str
