# generated by datamodel-codegen:
#   filename:  MinLengthConstraint.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class MinLengthConstraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    keyword: Literal['minLength']
    value: Annotated[int, Field(ge=0, le=2147483647)]
