# generated by datamodel-codegen:
#   filename:  Multiplicity.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Multiplicity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lower: Annotated[int, Field(ge=0, le=2147483647)]
    ordered: bool
    unique: bool
    upper: Annotated[int | None, Field(ge=0, le=2147483647)] = None
