# generated by datamodel-codegen:
#   filename:  NonEmptyConstraint.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class NonEmptyConstraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    keyword: Literal['nonEmpty']
