# generated by datamodel-codegen:
#   filename:  OperationDecl.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from .ClauseRef import ClauseRef
from .FieldDecl import FieldDecl
from .Identifier import Identifier
from .TypeRef import TypeRef


class OperationDecl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Identifier
    params: list[FieldDecl]
    post: list[ClauseRef] | None = None
    pre: list[ClauseRef] | None = None
    returns: TypeRef | None = None
