# generated by datamodel-codegen:
#   filename:  PatternConstraint.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class PatternConstraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dialect: Literal['ecma-262']
    keyword: Literal['pattern']
    regex: Annotated[str, Field(min_length=1)]
