# generated by datamodel-codegen:
#   filename:  RelationDecl.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from .EdgeCategory import EdgeCategory
from .Identifier import Identifier
from .Multiplicity import Multiplicity
from .SemanticId import SemanticId


class RelationDecl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    category: EdgeCategory
    composite: bool | None = None
    multiplicity: Multiplicity | None = None
    target: SemanticId
    verb: Identifier
