# generated by datamodel-codegen:
#   filename:  TypeRef.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from .DecimalPolicy import DecimalPolicy
from .KernelScalar import KernelScalar
from .Multiplicity import Multiplicity
from .SemanticId import SemanticId
from .UnitSymbol import UnitSymbol


class TypeRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decimal: DecimalPolicy | None = None
    multiplicity: Multiplicity | None = None
    target: SemanticId | KernelScalar
    unit: UnitSymbol | None = None
