# generated by datamodel-codegen:
#   filename:  UniqueConstraint.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class UniqueConstraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    keyword: Literal['unique']
