# generated by datamodel-codegen:
#   filename:  UnitSymbol.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel


class UnitSymbol(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='UCUM case-sensitive symbol charset: printable ASCII, no whitespace. Membership is a consumer concern (FR-034-AC-4).',
            pattern='^[!-~]+$',
            title='UnitSymbol',
        ),
    ]
