# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Agent-IX

"""Rebase extraction fixture module schemas onto Quire's embedded core 0.3.

Only authored fixture modules and their schema digests change here. Golden
outputs are regenerated by the existing extraction-frontend-goldens gate.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
MODULES = ROOT / "crates/extraction-frontend/fixtures/modules"
CORE_REF = re.compile(r"(https://schemas\.agent-ix\.org/semantic-core/)0\.[12]\.0/")
SCHEMA_BINDING = re.compile(
    r"(?m)^(?P<schema>\s*schema:\s*)(?P<path>\S+)\n"
    r"(?P<digest>\s*digest:\s*sha256:)[0-9a-f]{64}"
)


def migrate_module(module: Path) -> None:
    for schema in sorted((module / "schemas").glob("*.json")):
        original = schema.read_text()
        migrated = CORE_REF.sub(r"\g<1>0.3.0/", original)
        if migrated != original:
            schema.write_text(migrated)

    manifest = module / "manifest.yaml"
    text = manifest.read_text()
    text = re.sub(r"(?m)^(\s*semantic_core: )0\.[12]\.0$", r"\g<1>0.3.0", text)

    def digest_binding(match: re.Match[str]) -> str:
        schema = module / match.group("path")
        digest = hashlib.sha256(schema.read_bytes()).hexdigest()
        return (
            f'{match.group("schema")}{match.group("path")}\n'
            f'{match.group("digest")}{digest}'
        )

    manifest.write_text(SCHEMA_BINDING.sub(digest_binding, text))


def main() -> None:
    for manifest in sorted(MODULES.glob("*/manifest.yaml")):
        migrate_module(manifest.parent)


if __name__ == "__main__":
    main()
